
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `tb_his_failed_login` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model tb_his_failed_login
 * This model or at least one of its fields has comments in the database, and requires an additional setup for migrations: Read more: https://pris.ly/d/database-comments
 */
export type tb_his_failed_loginModel = runtime.Types.Result.DefaultSelection<Prisma.$tb_his_failed_loginPayload>

export type AggregateTb_his_failed_login = {
  _count: Tb_his_failed_loginCountAggregateOutputType | null
  _avg: Tb_his_failed_loginAvgAggregateOutputType | null
  _sum: Tb_his_failed_loginSumAggregateOutputType | null
  _min: Tb_his_failed_loginMinAggregateOutputType | null
  _max: Tb_his_failed_loginMaxAggregateOutputType | null
}

export type Tb_his_failed_loginAvgAggregateOutputType = {
  channel_id: number | null
  login_method_id: number | null
}

export type Tb_his_failed_loginSumAggregateOutputType = {
  channel_id: bigint | null
  login_method_id: bigint | null
}

export type Tb_his_failed_loginMinAggregateOutputType = {
  failed_login_id: string | null
  account_id: string | null
  channel_id: bigint | null
  login_method_id: bigint | null
  username_input: string | null
  ip_address: string | null
  device_id: string | null
  failure_reason: string | null
  failed_at: Date | null
  created_at: Date | null
  created_by: string | null
  updated_at: Date | null
  update_by: string | null
  record_status: string | null
}

export type Tb_his_failed_loginMaxAggregateOutputType = {
  failed_login_id: string | null
  account_id: string | null
  channel_id: bigint | null
  login_method_id: bigint | null
  username_input: string | null
  ip_address: string | null
  device_id: string | null
  failure_reason: string | null
  failed_at: Date | null
  created_at: Date | null
  created_by: string | null
  updated_at: Date | null
  update_by: string | null
  record_status: string | null
}

export type Tb_his_failed_loginCountAggregateOutputType = {
  failed_login_id: number
  account_id: number
  channel_id: number
  login_method_id: number
  username_input: number
  ip_address: number
  device_id: number
  failure_reason: number
  failed_at: number
  created_at: number
  created_by: number
  updated_at: number
  update_by: number
  record_status: number
  _all: number
}


export type Tb_his_failed_loginAvgAggregateInputType = {
  channel_id?: true
  login_method_id?: true
}

export type Tb_his_failed_loginSumAggregateInputType = {
  channel_id?: true
  login_method_id?: true
}

export type Tb_his_failed_loginMinAggregateInputType = {
  failed_login_id?: true
  account_id?: true
  channel_id?: true
  login_method_id?: true
  username_input?: true
  ip_address?: true
  device_id?: true
  failure_reason?: true
  failed_at?: true
  created_at?: true
  created_by?: true
  updated_at?: true
  update_by?: true
  record_status?: true
}

export type Tb_his_failed_loginMaxAggregateInputType = {
  failed_login_id?: true
  account_id?: true
  channel_id?: true
  login_method_id?: true
  username_input?: true
  ip_address?: true
  device_id?: true
  failure_reason?: true
  failed_at?: true
  created_at?: true
  created_by?: true
  updated_at?: true
  update_by?: true
  record_status?: true
}

export type Tb_his_failed_loginCountAggregateInputType = {
  failed_login_id?: true
  account_id?: true
  channel_id?: true
  login_method_id?: true
  username_input?: true
  ip_address?: true
  device_id?: true
  failure_reason?: true
  failed_at?: true
  created_at?: true
  created_by?: true
  updated_at?: true
  update_by?: true
  record_status?: true
  _all?: true
}

export type Tb_his_failed_loginAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which tb_his_failed_login to aggregate.
   */
  where?: Prisma.tb_his_failed_loginWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of tb_his_failed_logins to fetch.
   */
  orderBy?: Prisma.tb_his_failed_loginOrderByWithRelationInput | Prisma.tb_his_failed_loginOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.tb_his_failed_loginWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` tb_his_failed_logins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` tb_his_failed_logins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned tb_his_failed_logins
  **/
  _count?: true | Tb_his_failed_loginCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Tb_his_failed_loginAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Tb_his_failed_loginSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Tb_his_failed_loginMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Tb_his_failed_loginMaxAggregateInputType
}

export type GetTb_his_failed_loginAggregateType<T extends Tb_his_failed_loginAggregateArgs> = {
      [P in keyof T & keyof AggregateTb_his_failed_login]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTb_his_failed_login[P]>
    : Prisma.GetScalarType<T[P], AggregateTb_his_failed_login[P]>
}




export type tb_his_failed_loginGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.tb_his_failed_loginWhereInput
  orderBy?: Prisma.tb_his_failed_loginOrderByWithAggregationInput | Prisma.tb_his_failed_loginOrderByWithAggregationInput[]
  by: Prisma.Tb_his_failed_loginScalarFieldEnum[] | Prisma.Tb_his_failed_loginScalarFieldEnum
  having?: Prisma.tb_his_failed_loginScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Tb_his_failed_loginCountAggregateInputType | true
  _avg?: Tb_his_failed_loginAvgAggregateInputType
  _sum?: Tb_his_failed_loginSumAggregateInputType
  _min?: Tb_his_failed_loginMinAggregateInputType
  _max?: Tb_his_failed_loginMaxAggregateInputType
}

export type Tb_his_failed_loginGroupByOutputType = {
  failed_login_id: string
  account_id: string
  channel_id: bigint | null
  login_method_id: bigint
  username_input: string
  ip_address: string | null
  device_id: string | null
  failure_reason: string | null
  failed_at: Date
  created_at: Date
  created_by: string
  updated_at: Date | null
  update_by: string | null
  record_status: string | null
  _count: Tb_his_failed_loginCountAggregateOutputType | null
  _avg: Tb_his_failed_loginAvgAggregateOutputType | null
  _sum: Tb_his_failed_loginSumAggregateOutputType | null
  _min: Tb_his_failed_loginMinAggregateOutputType | null
  _max: Tb_his_failed_loginMaxAggregateOutputType | null
}

export type GetTb_his_failed_loginGroupByPayload<T extends tb_his_failed_loginGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Tb_his_failed_loginGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Tb_his_failed_loginGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Tb_his_failed_loginGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Tb_his_failed_loginGroupByOutputType[P]>
      }
    >
  >



export type tb_his_failed_loginWhereInput = {
  AND?: Prisma.tb_his_failed_loginWhereInput | Prisma.tb_his_failed_loginWhereInput[]
  OR?: Prisma.tb_his_failed_loginWhereInput[]
  NOT?: Prisma.tb_his_failed_loginWhereInput | Prisma.tb_his_failed_loginWhereInput[]
  failed_login_id?: Prisma.UuidFilter<"tb_his_failed_login"> | string
  account_id?: Prisma.UuidFilter<"tb_his_failed_login"> | string
  channel_id?: Prisma.BigIntNullableFilter<"tb_his_failed_login"> | bigint | number | null
  login_method_id?: Prisma.BigIntFilter<"tb_his_failed_login"> | bigint | number
  username_input?: Prisma.StringFilter<"tb_his_failed_login"> | string
  ip_address?: Prisma.StringNullableFilter<"tb_his_failed_login"> | string | null
  device_id?: Prisma.StringNullableFilter<"tb_his_failed_login"> | string | null
  failure_reason?: Prisma.StringNullableFilter<"tb_his_failed_login"> | string | null
  failed_at?: Prisma.DateTimeFilter<"tb_his_failed_login"> | Date | string
  created_at?: Prisma.DateTimeFilter<"tb_his_failed_login"> | Date | string
  created_by?: Prisma.UuidFilter<"tb_his_failed_login"> | string
  updated_at?: Prisma.DateTimeNullableFilter<"tb_his_failed_login"> | Date | string | null
  update_by?: Prisma.UuidNullableFilter<"tb_his_failed_login"> | string | null
  record_status?: Prisma.StringNullableFilter<"tb_his_failed_login"> | string | null
  tb_account?: Prisma.XOR<Prisma.Tb_accountScalarRelationFilter, Prisma.tb_accountWhereInput>
  tb_ms_channel?: Prisma.XOR<Prisma.Tb_ms_channelNullableScalarRelationFilter, Prisma.tb_ms_channelWhereInput> | null
}

export type tb_his_failed_loginOrderByWithRelationInput = {
  failed_login_id?: Prisma.SortOrder
  account_id?: Prisma.SortOrder
  channel_id?: Prisma.SortOrderInput | Prisma.SortOrder
  login_method_id?: Prisma.SortOrder
  username_input?: Prisma.SortOrder
  ip_address?: Prisma.SortOrderInput | Prisma.SortOrder
  device_id?: Prisma.SortOrderInput | Prisma.SortOrder
  failure_reason?: Prisma.SortOrderInput | Prisma.SortOrder
  failed_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  created_by?: Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  update_by?: Prisma.SortOrderInput | Prisma.SortOrder
  record_status?: Prisma.SortOrderInput | Prisma.SortOrder
  tb_account?: Prisma.tb_accountOrderByWithRelationInput
  tb_ms_channel?: Prisma.tb_ms_channelOrderByWithRelationInput
}

export type tb_his_failed_loginWhereUniqueInput = Prisma.AtLeast<{
  failed_login_id?: string
  AND?: Prisma.tb_his_failed_loginWhereInput | Prisma.tb_his_failed_loginWhereInput[]
  OR?: Prisma.tb_his_failed_loginWhereInput[]
  NOT?: Prisma.tb_his_failed_loginWhereInput | Prisma.tb_his_failed_loginWhereInput[]
  account_id?: Prisma.UuidFilter<"tb_his_failed_login"> | string
  channel_id?: Prisma.BigIntNullableFilter<"tb_his_failed_login"> | bigint | number | null
  login_method_id?: Prisma.BigIntFilter<"tb_his_failed_login"> | bigint | number
  username_input?: Prisma.StringFilter<"tb_his_failed_login"> | string
  ip_address?: Prisma.StringNullableFilter<"tb_his_failed_login"> | string | null
  device_id?: Prisma.StringNullableFilter<"tb_his_failed_login"> | string | null
  failure_reason?: Prisma.StringNullableFilter<"tb_his_failed_login"> | string | null
  failed_at?: Prisma.DateTimeFilter<"tb_his_failed_login"> | Date | string
  created_at?: Prisma.DateTimeFilter<"tb_his_failed_login"> | Date | string
  created_by?: Prisma.UuidFilter<"tb_his_failed_login"> | string
  updated_at?: Prisma.DateTimeNullableFilter<"tb_his_failed_login"> | Date | string | null
  update_by?: Prisma.UuidNullableFilter<"tb_his_failed_login"> | string | null
  record_status?: Prisma.StringNullableFilter<"tb_his_failed_login"> | string | null
  tb_account?: Prisma.XOR<Prisma.Tb_accountScalarRelationFilter, Prisma.tb_accountWhereInput>
  tb_ms_channel?: Prisma.XOR<Prisma.Tb_ms_channelNullableScalarRelationFilter, Prisma.tb_ms_channelWhereInput> | null
}, "failed_login_id">

export type tb_his_failed_loginOrderByWithAggregationInput = {
  failed_login_id?: Prisma.SortOrder
  account_id?: Prisma.SortOrder
  channel_id?: Prisma.SortOrderInput | Prisma.SortOrder
  login_method_id?: Prisma.SortOrder
  username_input?: Prisma.SortOrder
  ip_address?: Prisma.SortOrderInput | Prisma.SortOrder
  device_id?: Prisma.SortOrderInput | Prisma.SortOrder
  failure_reason?: Prisma.SortOrderInput | Prisma.SortOrder
  failed_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  created_by?: Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  update_by?: Prisma.SortOrderInput | Prisma.SortOrder
  record_status?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.tb_his_failed_loginCountOrderByAggregateInput
  _avg?: Prisma.tb_his_failed_loginAvgOrderByAggregateInput
  _max?: Prisma.tb_his_failed_loginMaxOrderByAggregateInput
  _min?: Prisma.tb_his_failed_loginMinOrderByAggregateInput
  _sum?: Prisma.tb_his_failed_loginSumOrderByAggregateInput
}

export type tb_his_failed_loginScalarWhereWithAggregatesInput = {
  AND?: Prisma.tb_his_failed_loginScalarWhereWithAggregatesInput | Prisma.tb_his_failed_loginScalarWhereWithAggregatesInput[]
  OR?: Prisma.tb_his_failed_loginScalarWhereWithAggregatesInput[]
  NOT?: Prisma.tb_his_failed_loginScalarWhereWithAggregatesInput | Prisma.tb_his_failed_loginScalarWhereWithAggregatesInput[]
  failed_login_id?: Prisma.UuidWithAggregatesFilter<"tb_his_failed_login"> | string
  account_id?: Prisma.UuidWithAggregatesFilter<"tb_his_failed_login"> | string
  channel_id?: Prisma.BigIntNullableWithAggregatesFilter<"tb_his_failed_login"> | bigint | number | null
  login_method_id?: Prisma.BigIntWithAggregatesFilter<"tb_his_failed_login"> | bigint | number
  username_input?: Prisma.StringWithAggregatesFilter<"tb_his_failed_login"> | string
  ip_address?: Prisma.StringNullableWithAggregatesFilter<"tb_his_failed_login"> | string | null
  device_id?: Prisma.StringNullableWithAggregatesFilter<"tb_his_failed_login"> | string | null
  failure_reason?: Prisma.StringNullableWithAggregatesFilter<"tb_his_failed_login"> | string | null
  failed_at?: Prisma.DateTimeWithAggregatesFilter<"tb_his_failed_login"> | Date | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"tb_his_failed_login"> | Date | string
  created_by?: Prisma.UuidWithAggregatesFilter<"tb_his_failed_login"> | string
  updated_at?: Prisma.DateTimeNullableWithAggregatesFilter<"tb_his_failed_login"> | Date | string | null
  update_by?: Prisma.UuidNullableWithAggregatesFilter<"tb_his_failed_login"> | string | null
  record_status?: Prisma.StringNullableWithAggregatesFilter<"tb_his_failed_login"> | string | null
}

export type tb_his_failed_loginCreateInput = {
  failed_login_id?: string
  login_method_id: bigint | number
  username_input: string
  ip_address?: string | null
  device_id?: string | null
  failure_reason?: string | null
  failed_at?: Date | string
  created_at?: Date | string
  created_by: string
  updated_at?: Date | string | null
  update_by?: string | null
  record_status?: string | null
  tb_account: Prisma.tb_accountCreateNestedOneWithoutTb_his_failed_loginInput
  tb_ms_channel?: Prisma.tb_ms_channelCreateNestedOneWithoutTb_his_failed_loginInput
}

export type tb_his_failed_loginUncheckedCreateInput = {
  failed_login_id?: string
  account_id: string
  channel_id?: bigint | number | null
  login_method_id: bigint | number
  username_input: string
  ip_address?: string | null
  device_id?: string | null
  failure_reason?: string | null
  failed_at?: Date | string
  created_at?: Date | string
  created_by: string
  updated_at?: Date | string | null
  update_by?: string | null
  record_status?: string | null
}

export type tb_his_failed_loginUpdateInput = {
  failed_login_id?: Prisma.StringFieldUpdateOperationsInput | string
  login_method_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  username_input?: Prisma.StringFieldUpdateOperationsInput | string
  ip_address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  device_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  failure_reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  failed_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_by?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tb_account?: Prisma.tb_accountUpdateOneRequiredWithoutTb_his_failed_loginNestedInput
  tb_ms_channel?: Prisma.tb_ms_channelUpdateOneWithoutTb_his_failed_loginNestedInput
}

export type tb_his_failed_loginUncheckedUpdateInput = {
  failed_login_id?: Prisma.StringFieldUpdateOperationsInput | string
  account_id?: Prisma.StringFieldUpdateOperationsInput | string
  channel_id?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  login_method_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  username_input?: Prisma.StringFieldUpdateOperationsInput | string
  ip_address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  device_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  failure_reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  failed_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_by?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type tb_his_failed_loginCreateManyInput = {
  failed_login_id?: string
  account_id: string
  channel_id?: bigint | number | null
  login_method_id: bigint | number
  username_input: string
  ip_address?: string | null
  device_id?: string | null
  failure_reason?: string | null
  failed_at?: Date | string
  created_at?: Date | string
  created_by: string
  updated_at?: Date | string | null
  update_by?: string | null
  record_status?: string | null
}

export type tb_his_failed_loginUpdateManyMutationInput = {
  failed_login_id?: Prisma.StringFieldUpdateOperationsInput | string
  login_method_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  username_input?: Prisma.StringFieldUpdateOperationsInput | string
  ip_address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  device_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  failure_reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  failed_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_by?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type tb_his_failed_loginUncheckedUpdateManyInput = {
  failed_login_id?: Prisma.StringFieldUpdateOperationsInput | string
  account_id?: Prisma.StringFieldUpdateOperationsInput | string
  channel_id?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  login_method_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  username_input?: Prisma.StringFieldUpdateOperationsInput | string
  ip_address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  device_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  failure_reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  failed_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_by?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type Tb_his_failed_loginListRelationFilter = {
  every?: Prisma.tb_his_failed_loginWhereInput
  some?: Prisma.tb_his_failed_loginWhereInput
  none?: Prisma.tb_his_failed_loginWhereInput
}

export type tb_his_failed_loginOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type tb_his_failed_loginCountOrderByAggregateInput = {
  failed_login_id?: Prisma.SortOrder
  account_id?: Prisma.SortOrder
  channel_id?: Prisma.SortOrder
  login_method_id?: Prisma.SortOrder
  username_input?: Prisma.SortOrder
  ip_address?: Prisma.SortOrder
  device_id?: Prisma.SortOrder
  failure_reason?: Prisma.SortOrder
  failed_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  created_by?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  update_by?: Prisma.SortOrder
  record_status?: Prisma.SortOrder
}

export type tb_his_failed_loginAvgOrderByAggregateInput = {
  channel_id?: Prisma.SortOrder
  login_method_id?: Prisma.SortOrder
}

export type tb_his_failed_loginMaxOrderByAggregateInput = {
  failed_login_id?: Prisma.SortOrder
  account_id?: Prisma.SortOrder
  channel_id?: Prisma.SortOrder
  login_method_id?: Prisma.SortOrder
  username_input?: Prisma.SortOrder
  ip_address?: Prisma.SortOrder
  device_id?: Prisma.SortOrder
  failure_reason?: Prisma.SortOrder
  failed_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  created_by?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  update_by?: Prisma.SortOrder
  record_status?: Prisma.SortOrder
}

export type tb_his_failed_loginMinOrderByAggregateInput = {
  failed_login_id?: Prisma.SortOrder
  account_id?: Prisma.SortOrder
  channel_id?: Prisma.SortOrder
  login_method_id?: Prisma.SortOrder
  username_input?: Prisma.SortOrder
  ip_address?: Prisma.SortOrder
  device_id?: Prisma.SortOrder
  failure_reason?: Prisma.SortOrder
  failed_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  created_by?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  update_by?: Prisma.SortOrder
  record_status?: Prisma.SortOrder
}

export type tb_his_failed_loginSumOrderByAggregateInput = {
  channel_id?: Prisma.SortOrder
  login_method_id?: Prisma.SortOrder
}

export type tb_his_failed_loginCreateNestedManyWithoutTb_accountInput = {
  create?: Prisma.XOR<Prisma.tb_his_failed_loginCreateWithoutTb_accountInput, Prisma.tb_his_failed_loginUncheckedCreateWithoutTb_accountInput> | Prisma.tb_his_failed_loginCreateWithoutTb_accountInput[] | Prisma.tb_his_failed_loginUncheckedCreateWithoutTb_accountInput[]
  connectOrCreate?: Prisma.tb_his_failed_loginCreateOrConnectWithoutTb_accountInput | Prisma.tb_his_failed_loginCreateOrConnectWithoutTb_accountInput[]
  createMany?: Prisma.tb_his_failed_loginCreateManyTb_accountInputEnvelope
  connect?: Prisma.tb_his_failed_loginWhereUniqueInput | Prisma.tb_his_failed_loginWhereUniqueInput[]
}

export type tb_his_failed_loginUncheckedCreateNestedManyWithoutTb_accountInput = {
  create?: Prisma.XOR<Prisma.tb_his_failed_loginCreateWithoutTb_accountInput, Prisma.tb_his_failed_loginUncheckedCreateWithoutTb_accountInput> | Prisma.tb_his_failed_loginCreateWithoutTb_accountInput[] | Prisma.tb_his_failed_loginUncheckedCreateWithoutTb_accountInput[]
  connectOrCreate?: Prisma.tb_his_failed_loginCreateOrConnectWithoutTb_accountInput | Prisma.tb_his_failed_loginCreateOrConnectWithoutTb_accountInput[]
  createMany?: Prisma.tb_his_failed_loginCreateManyTb_accountInputEnvelope
  connect?: Prisma.tb_his_failed_loginWhereUniqueInput | Prisma.tb_his_failed_loginWhereUniqueInput[]
}

export type tb_his_failed_loginUpdateManyWithoutTb_accountNestedInput = {
  create?: Prisma.XOR<Prisma.tb_his_failed_loginCreateWithoutTb_accountInput, Prisma.tb_his_failed_loginUncheckedCreateWithoutTb_accountInput> | Prisma.tb_his_failed_loginCreateWithoutTb_accountInput[] | Prisma.tb_his_failed_loginUncheckedCreateWithoutTb_accountInput[]
  connectOrCreate?: Prisma.tb_his_failed_loginCreateOrConnectWithoutTb_accountInput | Prisma.tb_his_failed_loginCreateOrConnectWithoutTb_accountInput[]
  upsert?: Prisma.tb_his_failed_loginUpsertWithWhereUniqueWithoutTb_accountInput | Prisma.tb_his_failed_loginUpsertWithWhereUniqueWithoutTb_accountInput[]
  createMany?: Prisma.tb_his_failed_loginCreateManyTb_accountInputEnvelope
  set?: Prisma.tb_his_failed_loginWhereUniqueInput | Prisma.tb_his_failed_loginWhereUniqueInput[]
  disconnect?: Prisma.tb_his_failed_loginWhereUniqueInput | Prisma.tb_his_failed_loginWhereUniqueInput[]
  delete?: Prisma.tb_his_failed_loginWhereUniqueInput | Prisma.tb_his_failed_loginWhereUniqueInput[]
  connect?: Prisma.tb_his_failed_loginWhereUniqueInput | Prisma.tb_his_failed_loginWhereUniqueInput[]
  update?: Prisma.tb_his_failed_loginUpdateWithWhereUniqueWithoutTb_accountInput | Prisma.tb_his_failed_loginUpdateWithWhereUniqueWithoutTb_accountInput[]
  updateMany?: Prisma.tb_his_failed_loginUpdateManyWithWhereWithoutTb_accountInput | Prisma.tb_his_failed_loginUpdateManyWithWhereWithoutTb_accountInput[]
  deleteMany?: Prisma.tb_his_failed_loginScalarWhereInput | Prisma.tb_his_failed_loginScalarWhereInput[]
}

export type tb_his_failed_loginUncheckedUpdateManyWithoutTb_accountNestedInput = {
  create?: Prisma.XOR<Prisma.tb_his_failed_loginCreateWithoutTb_accountInput, Prisma.tb_his_failed_loginUncheckedCreateWithoutTb_accountInput> | Prisma.tb_his_failed_loginCreateWithoutTb_accountInput[] | Prisma.tb_his_failed_loginUncheckedCreateWithoutTb_accountInput[]
  connectOrCreate?: Prisma.tb_his_failed_loginCreateOrConnectWithoutTb_accountInput | Prisma.tb_his_failed_loginCreateOrConnectWithoutTb_accountInput[]
  upsert?: Prisma.tb_his_failed_loginUpsertWithWhereUniqueWithoutTb_accountInput | Prisma.tb_his_failed_loginUpsertWithWhereUniqueWithoutTb_accountInput[]
  createMany?: Prisma.tb_his_failed_loginCreateManyTb_accountInputEnvelope
  set?: Prisma.tb_his_failed_loginWhereUniqueInput | Prisma.tb_his_failed_loginWhereUniqueInput[]
  disconnect?: Prisma.tb_his_failed_loginWhereUniqueInput | Prisma.tb_his_failed_loginWhereUniqueInput[]
  delete?: Prisma.tb_his_failed_loginWhereUniqueInput | Prisma.tb_his_failed_loginWhereUniqueInput[]
  connect?: Prisma.tb_his_failed_loginWhereUniqueInput | Prisma.tb_his_failed_loginWhereUniqueInput[]
  update?: Prisma.tb_his_failed_loginUpdateWithWhereUniqueWithoutTb_accountInput | Prisma.tb_his_failed_loginUpdateWithWhereUniqueWithoutTb_accountInput[]
  updateMany?: Prisma.tb_his_failed_loginUpdateManyWithWhereWithoutTb_accountInput | Prisma.tb_his_failed_loginUpdateManyWithWhereWithoutTb_accountInput[]
  deleteMany?: Prisma.tb_his_failed_loginScalarWhereInput | Prisma.tb_his_failed_loginScalarWhereInput[]
}

export type BigIntFieldUpdateOperationsInput = {
  set?: bigint | number
  increment?: bigint | number
  decrement?: bigint | number
  multiply?: bigint | number
  divide?: bigint | number
}

export type tb_his_failed_loginCreateNestedManyWithoutTb_ms_channelInput = {
  create?: Prisma.XOR<Prisma.tb_his_failed_loginCreateWithoutTb_ms_channelInput, Prisma.tb_his_failed_loginUncheckedCreateWithoutTb_ms_channelInput> | Prisma.tb_his_failed_loginCreateWithoutTb_ms_channelInput[] | Prisma.tb_his_failed_loginUncheckedCreateWithoutTb_ms_channelInput[]
  connectOrCreate?: Prisma.tb_his_failed_loginCreateOrConnectWithoutTb_ms_channelInput | Prisma.tb_his_failed_loginCreateOrConnectWithoutTb_ms_channelInput[]
  createMany?: Prisma.tb_his_failed_loginCreateManyTb_ms_channelInputEnvelope
  connect?: Prisma.tb_his_failed_loginWhereUniqueInput | Prisma.tb_his_failed_loginWhereUniqueInput[]
}

export type tb_his_failed_loginUncheckedCreateNestedManyWithoutTb_ms_channelInput = {
  create?: Prisma.XOR<Prisma.tb_his_failed_loginCreateWithoutTb_ms_channelInput, Prisma.tb_his_failed_loginUncheckedCreateWithoutTb_ms_channelInput> | Prisma.tb_his_failed_loginCreateWithoutTb_ms_channelInput[] | Prisma.tb_his_failed_loginUncheckedCreateWithoutTb_ms_channelInput[]
  connectOrCreate?: Prisma.tb_his_failed_loginCreateOrConnectWithoutTb_ms_channelInput | Prisma.tb_his_failed_loginCreateOrConnectWithoutTb_ms_channelInput[]
  createMany?: Prisma.tb_his_failed_loginCreateManyTb_ms_channelInputEnvelope
  connect?: Prisma.tb_his_failed_loginWhereUniqueInput | Prisma.tb_his_failed_loginWhereUniqueInput[]
}

export type tb_his_failed_loginUpdateManyWithoutTb_ms_channelNestedInput = {
  create?: Prisma.XOR<Prisma.tb_his_failed_loginCreateWithoutTb_ms_channelInput, Prisma.tb_his_failed_loginUncheckedCreateWithoutTb_ms_channelInput> | Prisma.tb_his_failed_loginCreateWithoutTb_ms_channelInput[] | Prisma.tb_his_failed_loginUncheckedCreateWithoutTb_ms_channelInput[]
  connectOrCreate?: Prisma.tb_his_failed_loginCreateOrConnectWithoutTb_ms_channelInput | Prisma.tb_his_failed_loginCreateOrConnectWithoutTb_ms_channelInput[]
  upsert?: Prisma.tb_his_failed_loginUpsertWithWhereUniqueWithoutTb_ms_channelInput | Prisma.tb_his_failed_loginUpsertWithWhereUniqueWithoutTb_ms_channelInput[]
  createMany?: Prisma.tb_his_failed_loginCreateManyTb_ms_channelInputEnvelope
  set?: Prisma.tb_his_failed_loginWhereUniqueInput | Prisma.tb_his_failed_loginWhereUniqueInput[]
  disconnect?: Prisma.tb_his_failed_loginWhereUniqueInput | Prisma.tb_his_failed_loginWhereUniqueInput[]
  delete?: Prisma.tb_his_failed_loginWhereUniqueInput | Prisma.tb_his_failed_loginWhereUniqueInput[]
  connect?: Prisma.tb_his_failed_loginWhereUniqueInput | Prisma.tb_his_failed_loginWhereUniqueInput[]
  update?: Prisma.tb_his_failed_loginUpdateWithWhereUniqueWithoutTb_ms_channelInput | Prisma.tb_his_failed_loginUpdateWithWhereUniqueWithoutTb_ms_channelInput[]
  updateMany?: Prisma.tb_his_failed_loginUpdateManyWithWhereWithoutTb_ms_channelInput | Prisma.tb_his_failed_loginUpdateManyWithWhereWithoutTb_ms_channelInput[]
  deleteMany?: Prisma.tb_his_failed_loginScalarWhereInput | Prisma.tb_his_failed_loginScalarWhereInput[]
}

export type tb_his_failed_loginUncheckedUpdateManyWithoutTb_ms_channelNestedInput = {
  create?: Prisma.XOR<Prisma.tb_his_failed_loginCreateWithoutTb_ms_channelInput, Prisma.tb_his_failed_loginUncheckedCreateWithoutTb_ms_channelInput> | Prisma.tb_his_failed_loginCreateWithoutTb_ms_channelInput[] | Prisma.tb_his_failed_loginUncheckedCreateWithoutTb_ms_channelInput[]
  connectOrCreate?: Prisma.tb_his_failed_loginCreateOrConnectWithoutTb_ms_channelInput | Prisma.tb_his_failed_loginCreateOrConnectWithoutTb_ms_channelInput[]
  upsert?: Prisma.tb_his_failed_loginUpsertWithWhereUniqueWithoutTb_ms_channelInput | Prisma.tb_his_failed_loginUpsertWithWhereUniqueWithoutTb_ms_channelInput[]
  createMany?: Prisma.tb_his_failed_loginCreateManyTb_ms_channelInputEnvelope
  set?: Prisma.tb_his_failed_loginWhereUniqueInput | Prisma.tb_his_failed_loginWhereUniqueInput[]
  disconnect?: Prisma.tb_his_failed_loginWhereUniqueInput | Prisma.tb_his_failed_loginWhereUniqueInput[]
  delete?: Prisma.tb_his_failed_loginWhereUniqueInput | Prisma.tb_his_failed_loginWhereUniqueInput[]
  connect?: Prisma.tb_his_failed_loginWhereUniqueInput | Prisma.tb_his_failed_loginWhereUniqueInput[]
  update?: Prisma.tb_his_failed_loginUpdateWithWhereUniqueWithoutTb_ms_channelInput | Prisma.tb_his_failed_loginUpdateWithWhereUniqueWithoutTb_ms_channelInput[]
  updateMany?: Prisma.tb_his_failed_loginUpdateManyWithWhereWithoutTb_ms_channelInput | Prisma.tb_his_failed_loginUpdateManyWithWhereWithoutTb_ms_channelInput[]
  deleteMany?: Prisma.tb_his_failed_loginScalarWhereInput | Prisma.tb_his_failed_loginScalarWhereInput[]
}

export type tb_his_failed_loginCreateWithoutTb_accountInput = {
  failed_login_id?: string
  login_method_id: bigint | number
  username_input: string
  ip_address?: string | null
  device_id?: string | null
  failure_reason?: string | null
  failed_at?: Date | string
  created_at?: Date | string
  created_by: string
  updated_at?: Date | string | null
  update_by?: string | null
  record_status?: string | null
  tb_ms_channel?: Prisma.tb_ms_channelCreateNestedOneWithoutTb_his_failed_loginInput
}

export type tb_his_failed_loginUncheckedCreateWithoutTb_accountInput = {
  failed_login_id?: string
  channel_id?: bigint | number | null
  login_method_id: bigint | number
  username_input: string
  ip_address?: string | null
  device_id?: string | null
  failure_reason?: string | null
  failed_at?: Date | string
  created_at?: Date | string
  created_by: string
  updated_at?: Date | string | null
  update_by?: string | null
  record_status?: string | null
}

export type tb_his_failed_loginCreateOrConnectWithoutTb_accountInput = {
  where: Prisma.tb_his_failed_loginWhereUniqueInput
  create: Prisma.XOR<Prisma.tb_his_failed_loginCreateWithoutTb_accountInput, Prisma.tb_his_failed_loginUncheckedCreateWithoutTb_accountInput>
}

export type tb_his_failed_loginCreateManyTb_accountInputEnvelope = {
  data: Prisma.tb_his_failed_loginCreateManyTb_accountInput | Prisma.tb_his_failed_loginCreateManyTb_accountInput[]
  skipDuplicates?: boolean
}

export type tb_his_failed_loginUpsertWithWhereUniqueWithoutTb_accountInput = {
  where: Prisma.tb_his_failed_loginWhereUniqueInput
  update: Prisma.XOR<Prisma.tb_his_failed_loginUpdateWithoutTb_accountInput, Prisma.tb_his_failed_loginUncheckedUpdateWithoutTb_accountInput>
  create: Prisma.XOR<Prisma.tb_his_failed_loginCreateWithoutTb_accountInput, Prisma.tb_his_failed_loginUncheckedCreateWithoutTb_accountInput>
}

export type tb_his_failed_loginUpdateWithWhereUniqueWithoutTb_accountInput = {
  where: Prisma.tb_his_failed_loginWhereUniqueInput
  data: Prisma.XOR<Prisma.tb_his_failed_loginUpdateWithoutTb_accountInput, Prisma.tb_his_failed_loginUncheckedUpdateWithoutTb_accountInput>
}

export type tb_his_failed_loginUpdateManyWithWhereWithoutTb_accountInput = {
  where: Prisma.tb_his_failed_loginScalarWhereInput
  data: Prisma.XOR<Prisma.tb_his_failed_loginUpdateManyMutationInput, Prisma.tb_his_failed_loginUncheckedUpdateManyWithoutTb_accountInput>
}

export type tb_his_failed_loginScalarWhereInput = {
  AND?: Prisma.tb_his_failed_loginScalarWhereInput | Prisma.tb_his_failed_loginScalarWhereInput[]
  OR?: Prisma.tb_his_failed_loginScalarWhereInput[]
  NOT?: Prisma.tb_his_failed_loginScalarWhereInput | Prisma.tb_his_failed_loginScalarWhereInput[]
  failed_login_id?: Prisma.UuidFilter<"tb_his_failed_login"> | string
  account_id?: Prisma.UuidFilter<"tb_his_failed_login"> | string
  channel_id?: Prisma.BigIntNullableFilter<"tb_his_failed_login"> | bigint | number | null
  login_method_id?: Prisma.BigIntFilter<"tb_his_failed_login"> | bigint | number
  username_input?: Prisma.StringFilter<"tb_his_failed_login"> | string
  ip_address?: Prisma.StringNullableFilter<"tb_his_failed_login"> | string | null
  device_id?: Prisma.StringNullableFilter<"tb_his_failed_login"> | string | null
  failure_reason?: Prisma.StringNullableFilter<"tb_his_failed_login"> | string | null
  failed_at?: Prisma.DateTimeFilter<"tb_his_failed_login"> | Date | string
  created_at?: Prisma.DateTimeFilter<"tb_his_failed_login"> | Date | string
  created_by?: Prisma.UuidFilter<"tb_his_failed_login"> | string
  updated_at?: Prisma.DateTimeNullableFilter<"tb_his_failed_login"> | Date | string | null
  update_by?: Prisma.UuidNullableFilter<"tb_his_failed_login"> | string | null
  record_status?: Prisma.StringNullableFilter<"tb_his_failed_login"> | string | null
}

export type tb_his_failed_loginCreateWithoutTb_ms_channelInput = {
  failed_login_id?: string
  login_method_id: bigint | number
  username_input: string
  ip_address?: string | null
  device_id?: string | null
  failure_reason?: string | null
  failed_at?: Date | string
  created_at?: Date | string
  created_by: string
  updated_at?: Date | string | null
  update_by?: string | null
  record_status?: string | null
  tb_account: Prisma.tb_accountCreateNestedOneWithoutTb_his_failed_loginInput
}

export type tb_his_failed_loginUncheckedCreateWithoutTb_ms_channelInput = {
  failed_login_id?: string
  account_id: string
  login_method_id: bigint | number
  username_input: string
  ip_address?: string | null
  device_id?: string | null
  failure_reason?: string | null
  failed_at?: Date | string
  created_at?: Date | string
  created_by: string
  updated_at?: Date | string | null
  update_by?: string | null
  record_status?: string | null
}

export type tb_his_failed_loginCreateOrConnectWithoutTb_ms_channelInput = {
  where: Prisma.tb_his_failed_loginWhereUniqueInput
  create: Prisma.XOR<Prisma.tb_his_failed_loginCreateWithoutTb_ms_channelInput, Prisma.tb_his_failed_loginUncheckedCreateWithoutTb_ms_channelInput>
}

export type tb_his_failed_loginCreateManyTb_ms_channelInputEnvelope = {
  data: Prisma.tb_his_failed_loginCreateManyTb_ms_channelInput | Prisma.tb_his_failed_loginCreateManyTb_ms_channelInput[]
  skipDuplicates?: boolean
}

export type tb_his_failed_loginUpsertWithWhereUniqueWithoutTb_ms_channelInput = {
  where: Prisma.tb_his_failed_loginWhereUniqueInput
  update: Prisma.XOR<Prisma.tb_his_failed_loginUpdateWithoutTb_ms_channelInput, Prisma.tb_his_failed_loginUncheckedUpdateWithoutTb_ms_channelInput>
  create: Prisma.XOR<Prisma.tb_his_failed_loginCreateWithoutTb_ms_channelInput, Prisma.tb_his_failed_loginUncheckedCreateWithoutTb_ms_channelInput>
}

export type tb_his_failed_loginUpdateWithWhereUniqueWithoutTb_ms_channelInput = {
  where: Prisma.tb_his_failed_loginWhereUniqueInput
  data: Prisma.XOR<Prisma.tb_his_failed_loginUpdateWithoutTb_ms_channelInput, Prisma.tb_his_failed_loginUncheckedUpdateWithoutTb_ms_channelInput>
}

export type tb_his_failed_loginUpdateManyWithWhereWithoutTb_ms_channelInput = {
  where: Prisma.tb_his_failed_loginScalarWhereInput
  data: Prisma.XOR<Prisma.tb_his_failed_loginUpdateManyMutationInput, Prisma.tb_his_failed_loginUncheckedUpdateManyWithoutTb_ms_channelInput>
}

export type tb_his_failed_loginCreateManyTb_accountInput = {
  failed_login_id?: string
  channel_id?: bigint | number | null
  login_method_id: bigint | number
  username_input: string
  ip_address?: string | null
  device_id?: string | null
  failure_reason?: string | null
  failed_at?: Date | string
  created_at?: Date | string
  created_by: string
  updated_at?: Date | string | null
  update_by?: string | null
  record_status?: string | null
}

export type tb_his_failed_loginUpdateWithoutTb_accountInput = {
  failed_login_id?: Prisma.StringFieldUpdateOperationsInput | string
  login_method_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  username_input?: Prisma.StringFieldUpdateOperationsInput | string
  ip_address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  device_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  failure_reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  failed_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_by?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tb_ms_channel?: Prisma.tb_ms_channelUpdateOneWithoutTb_his_failed_loginNestedInput
}

export type tb_his_failed_loginUncheckedUpdateWithoutTb_accountInput = {
  failed_login_id?: Prisma.StringFieldUpdateOperationsInput | string
  channel_id?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  login_method_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  username_input?: Prisma.StringFieldUpdateOperationsInput | string
  ip_address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  device_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  failure_reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  failed_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_by?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type tb_his_failed_loginUncheckedUpdateManyWithoutTb_accountInput = {
  failed_login_id?: Prisma.StringFieldUpdateOperationsInput | string
  channel_id?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  login_method_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  username_input?: Prisma.StringFieldUpdateOperationsInput | string
  ip_address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  device_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  failure_reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  failed_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_by?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type tb_his_failed_loginCreateManyTb_ms_channelInput = {
  failed_login_id?: string
  account_id: string
  login_method_id: bigint | number
  username_input: string
  ip_address?: string | null
  device_id?: string | null
  failure_reason?: string | null
  failed_at?: Date | string
  created_at?: Date | string
  created_by: string
  updated_at?: Date | string | null
  update_by?: string | null
  record_status?: string | null
}

export type tb_his_failed_loginUpdateWithoutTb_ms_channelInput = {
  failed_login_id?: Prisma.StringFieldUpdateOperationsInput | string
  login_method_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  username_input?: Prisma.StringFieldUpdateOperationsInput | string
  ip_address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  device_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  failure_reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  failed_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_by?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tb_account?: Prisma.tb_accountUpdateOneRequiredWithoutTb_his_failed_loginNestedInput
}

export type tb_his_failed_loginUncheckedUpdateWithoutTb_ms_channelInput = {
  failed_login_id?: Prisma.StringFieldUpdateOperationsInput | string
  account_id?: Prisma.StringFieldUpdateOperationsInput | string
  login_method_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  username_input?: Prisma.StringFieldUpdateOperationsInput | string
  ip_address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  device_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  failure_reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  failed_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_by?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type tb_his_failed_loginUncheckedUpdateManyWithoutTb_ms_channelInput = {
  failed_login_id?: Prisma.StringFieldUpdateOperationsInput | string
  account_id?: Prisma.StringFieldUpdateOperationsInput | string
  login_method_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  username_input?: Prisma.StringFieldUpdateOperationsInput | string
  ip_address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  device_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  failure_reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  failed_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_by?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type tb_his_failed_loginSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  failed_login_id?: boolean
  account_id?: boolean
  channel_id?: boolean
  login_method_id?: boolean
  username_input?: boolean
  ip_address?: boolean
  device_id?: boolean
  failure_reason?: boolean
  failed_at?: boolean
  created_at?: boolean
  created_by?: boolean
  updated_at?: boolean
  update_by?: boolean
  record_status?: boolean
  tb_account?: boolean | Prisma.tb_accountDefaultArgs<ExtArgs>
  tb_ms_channel?: boolean | Prisma.tb_his_failed_login$tb_ms_channelArgs<ExtArgs>
}, ExtArgs["result"]["tb_his_failed_login"]>

export type tb_his_failed_loginSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  failed_login_id?: boolean
  account_id?: boolean
  channel_id?: boolean
  login_method_id?: boolean
  username_input?: boolean
  ip_address?: boolean
  device_id?: boolean
  failure_reason?: boolean
  failed_at?: boolean
  created_at?: boolean
  created_by?: boolean
  updated_at?: boolean
  update_by?: boolean
  record_status?: boolean
  tb_account?: boolean | Prisma.tb_accountDefaultArgs<ExtArgs>
  tb_ms_channel?: boolean | Prisma.tb_his_failed_login$tb_ms_channelArgs<ExtArgs>
}, ExtArgs["result"]["tb_his_failed_login"]>

export type tb_his_failed_loginSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  failed_login_id?: boolean
  account_id?: boolean
  channel_id?: boolean
  login_method_id?: boolean
  username_input?: boolean
  ip_address?: boolean
  device_id?: boolean
  failure_reason?: boolean
  failed_at?: boolean
  created_at?: boolean
  created_by?: boolean
  updated_at?: boolean
  update_by?: boolean
  record_status?: boolean
  tb_account?: boolean | Prisma.tb_accountDefaultArgs<ExtArgs>
  tb_ms_channel?: boolean | Prisma.tb_his_failed_login$tb_ms_channelArgs<ExtArgs>
}, ExtArgs["result"]["tb_his_failed_login"]>

export type tb_his_failed_loginSelectScalar = {
  failed_login_id?: boolean
  account_id?: boolean
  channel_id?: boolean
  login_method_id?: boolean
  username_input?: boolean
  ip_address?: boolean
  device_id?: boolean
  failure_reason?: boolean
  failed_at?: boolean
  created_at?: boolean
  created_by?: boolean
  updated_at?: boolean
  update_by?: boolean
  record_status?: boolean
}

export type tb_his_failed_loginOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"failed_login_id" | "account_id" | "channel_id" | "login_method_id" | "username_input" | "ip_address" | "device_id" | "failure_reason" | "failed_at" | "created_at" | "created_by" | "updated_at" | "update_by" | "record_status", ExtArgs["result"]["tb_his_failed_login"]>
export type tb_his_failed_loginInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tb_account?: boolean | Prisma.tb_accountDefaultArgs<ExtArgs>
  tb_ms_channel?: boolean | Prisma.tb_his_failed_login$tb_ms_channelArgs<ExtArgs>
}
export type tb_his_failed_loginIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tb_account?: boolean | Prisma.tb_accountDefaultArgs<ExtArgs>
  tb_ms_channel?: boolean | Prisma.tb_his_failed_login$tb_ms_channelArgs<ExtArgs>
}
export type tb_his_failed_loginIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tb_account?: boolean | Prisma.tb_accountDefaultArgs<ExtArgs>
  tb_ms_channel?: boolean | Prisma.tb_his_failed_login$tb_ms_channelArgs<ExtArgs>
}

export type $tb_his_failed_loginPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "tb_his_failed_login"
  objects: {
    tb_account: Prisma.$tb_accountPayload<ExtArgs>
    tb_ms_channel: Prisma.$tb_ms_channelPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    failed_login_id: string
    account_id: string
    channel_id: bigint | null
    login_method_id: bigint
    username_input: string
    ip_address: string | null
    device_id: string | null
    failure_reason: string | null
    failed_at: Date
    created_at: Date
    created_by: string
    updated_at: Date | null
    update_by: string | null
    record_status: string | null
  }, ExtArgs["result"]["tb_his_failed_login"]>
  composites: {}
}

export type tb_his_failed_loginGetPayload<S extends boolean | null | undefined | tb_his_failed_loginDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$tb_his_failed_loginPayload, S>

export type tb_his_failed_loginCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<tb_his_failed_loginFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Tb_his_failed_loginCountAggregateInputType | true
  }

export interface tb_his_failed_loginDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['tb_his_failed_login'], meta: { name: 'tb_his_failed_login' } }
  /**
   * Find zero or one Tb_his_failed_login that matches the filter.
   * @param {tb_his_failed_loginFindUniqueArgs} args - Arguments to find a Tb_his_failed_login
   * @example
   * // Get one Tb_his_failed_login
   * const tb_his_failed_login = await prisma.tb_his_failed_login.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends tb_his_failed_loginFindUniqueArgs>(args: Prisma.SelectSubset<T, tb_his_failed_loginFindUniqueArgs<ExtArgs>>): Prisma.Prisma__tb_his_failed_loginClient<runtime.Types.Result.GetResult<Prisma.$tb_his_failed_loginPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Tb_his_failed_login that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {tb_his_failed_loginFindUniqueOrThrowArgs} args - Arguments to find a Tb_his_failed_login
   * @example
   * // Get one Tb_his_failed_login
   * const tb_his_failed_login = await prisma.tb_his_failed_login.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends tb_his_failed_loginFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, tb_his_failed_loginFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__tb_his_failed_loginClient<runtime.Types.Result.GetResult<Prisma.$tb_his_failed_loginPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tb_his_failed_login that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {tb_his_failed_loginFindFirstArgs} args - Arguments to find a Tb_his_failed_login
   * @example
   * // Get one Tb_his_failed_login
   * const tb_his_failed_login = await prisma.tb_his_failed_login.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends tb_his_failed_loginFindFirstArgs>(args?: Prisma.SelectSubset<T, tb_his_failed_loginFindFirstArgs<ExtArgs>>): Prisma.Prisma__tb_his_failed_loginClient<runtime.Types.Result.GetResult<Prisma.$tb_his_failed_loginPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tb_his_failed_login that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {tb_his_failed_loginFindFirstOrThrowArgs} args - Arguments to find a Tb_his_failed_login
   * @example
   * // Get one Tb_his_failed_login
   * const tb_his_failed_login = await prisma.tb_his_failed_login.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends tb_his_failed_loginFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, tb_his_failed_loginFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__tb_his_failed_loginClient<runtime.Types.Result.GetResult<Prisma.$tb_his_failed_loginPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Tb_his_failed_logins that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {tb_his_failed_loginFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Tb_his_failed_logins
   * const tb_his_failed_logins = await prisma.tb_his_failed_login.findMany()
   * 
   * // Get first 10 Tb_his_failed_logins
   * const tb_his_failed_logins = await prisma.tb_his_failed_login.findMany({ take: 10 })
   * 
   * // Only select the `failed_login_id`
   * const tb_his_failed_loginWithFailed_login_idOnly = await prisma.tb_his_failed_login.findMany({ select: { failed_login_id: true } })
   * 
   */
  findMany<T extends tb_his_failed_loginFindManyArgs>(args?: Prisma.SelectSubset<T, tb_his_failed_loginFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$tb_his_failed_loginPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Tb_his_failed_login.
   * @param {tb_his_failed_loginCreateArgs} args - Arguments to create a Tb_his_failed_login.
   * @example
   * // Create one Tb_his_failed_login
   * const Tb_his_failed_login = await prisma.tb_his_failed_login.create({
   *   data: {
   *     // ... data to create a Tb_his_failed_login
   *   }
   * })
   * 
   */
  create<T extends tb_his_failed_loginCreateArgs>(args: Prisma.SelectSubset<T, tb_his_failed_loginCreateArgs<ExtArgs>>): Prisma.Prisma__tb_his_failed_loginClient<runtime.Types.Result.GetResult<Prisma.$tb_his_failed_loginPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Tb_his_failed_logins.
   * @param {tb_his_failed_loginCreateManyArgs} args - Arguments to create many Tb_his_failed_logins.
   * @example
   * // Create many Tb_his_failed_logins
   * const tb_his_failed_login = await prisma.tb_his_failed_login.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends tb_his_failed_loginCreateManyArgs>(args?: Prisma.SelectSubset<T, tb_his_failed_loginCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Tb_his_failed_logins and returns the data saved in the database.
   * @param {tb_his_failed_loginCreateManyAndReturnArgs} args - Arguments to create many Tb_his_failed_logins.
   * @example
   * // Create many Tb_his_failed_logins
   * const tb_his_failed_login = await prisma.tb_his_failed_login.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Tb_his_failed_logins and only return the `failed_login_id`
   * const tb_his_failed_loginWithFailed_login_idOnly = await prisma.tb_his_failed_login.createManyAndReturn({
   *   select: { failed_login_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends tb_his_failed_loginCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, tb_his_failed_loginCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$tb_his_failed_loginPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Tb_his_failed_login.
   * @param {tb_his_failed_loginDeleteArgs} args - Arguments to delete one Tb_his_failed_login.
   * @example
   * // Delete one Tb_his_failed_login
   * const Tb_his_failed_login = await prisma.tb_his_failed_login.delete({
   *   where: {
   *     // ... filter to delete one Tb_his_failed_login
   *   }
   * })
   * 
   */
  delete<T extends tb_his_failed_loginDeleteArgs>(args: Prisma.SelectSubset<T, tb_his_failed_loginDeleteArgs<ExtArgs>>): Prisma.Prisma__tb_his_failed_loginClient<runtime.Types.Result.GetResult<Prisma.$tb_his_failed_loginPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Tb_his_failed_login.
   * @param {tb_his_failed_loginUpdateArgs} args - Arguments to update one Tb_his_failed_login.
   * @example
   * // Update one Tb_his_failed_login
   * const tb_his_failed_login = await prisma.tb_his_failed_login.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends tb_his_failed_loginUpdateArgs>(args: Prisma.SelectSubset<T, tb_his_failed_loginUpdateArgs<ExtArgs>>): Prisma.Prisma__tb_his_failed_loginClient<runtime.Types.Result.GetResult<Prisma.$tb_his_failed_loginPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Tb_his_failed_logins.
   * @param {tb_his_failed_loginDeleteManyArgs} args - Arguments to filter Tb_his_failed_logins to delete.
   * @example
   * // Delete a few Tb_his_failed_logins
   * const { count } = await prisma.tb_his_failed_login.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends tb_his_failed_loginDeleteManyArgs>(args?: Prisma.SelectSubset<T, tb_his_failed_loginDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tb_his_failed_logins.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {tb_his_failed_loginUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Tb_his_failed_logins
   * const tb_his_failed_login = await prisma.tb_his_failed_login.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends tb_his_failed_loginUpdateManyArgs>(args: Prisma.SelectSubset<T, tb_his_failed_loginUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tb_his_failed_logins and returns the data updated in the database.
   * @param {tb_his_failed_loginUpdateManyAndReturnArgs} args - Arguments to update many Tb_his_failed_logins.
   * @example
   * // Update many Tb_his_failed_logins
   * const tb_his_failed_login = await prisma.tb_his_failed_login.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Tb_his_failed_logins and only return the `failed_login_id`
   * const tb_his_failed_loginWithFailed_login_idOnly = await prisma.tb_his_failed_login.updateManyAndReturn({
   *   select: { failed_login_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends tb_his_failed_loginUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, tb_his_failed_loginUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$tb_his_failed_loginPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Tb_his_failed_login.
   * @param {tb_his_failed_loginUpsertArgs} args - Arguments to update or create a Tb_his_failed_login.
   * @example
   * // Update or create a Tb_his_failed_login
   * const tb_his_failed_login = await prisma.tb_his_failed_login.upsert({
   *   create: {
   *     // ... data to create a Tb_his_failed_login
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Tb_his_failed_login we want to update
   *   }
   * })
   */
  upsert<T extends tb_his_failed_loginUpsertArgs>(args: Prisma.SelectSubset<T, tb_his_failed_loginUpsertArgs<ExtArgs>>): Prisma.Prisma__tb_his_failed_loginClient<runtime.Types.Result.GetResult<Prisma.$tb_his_failed_loginPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Tb_his_failed_logins.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {tb_his_failed_loginCountArgs} args - Arguments to filter Tb_his_failed_logins to count.
   * @example
   * // Count the number of Tb_his_failed_logins
   * const count = await prisma.tb_his_failed_login.count({
   *   where: {
   *     // ... the filter for the Tb_his_failed_logins we want to count
   *   }
   * })
  **/
  count<T extends tb_his_failed_loginCountArgs>(
    args?: Prisma.Subset<T, tb_his_failed_loginCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Tb_his_failed_loginCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Tb_his_failed_login.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Tb_his_failed_loginAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Tb_his_failed_loginAggregateArgs>(args: Prisma.Subset<T, Tb_his_failed_loginAggregateArgs>): Prisma.PrismaPromise<GetTb_his_failed_loginAggregateType<T>>

  /**
   * Group by Tb_his_failed_login.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {tb_his_failed_loginGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends tb_his_failed_loginGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: tb_his_failed_loginGroupByArgs['orderBy'] }
      : { orderBy?: tb_his_failed_loginGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, tb_his_failed_loginGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTb_his_failed_loginGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the tb_his_failed_login model
 */
readonly fields: tb_his_failed_loginFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for tb_his_failed_login.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__tb_his_failed_loginClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tb_account<T extends Prisma.tb_accountDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.tb_accountDefaultArgs<ExtArgs>>): Prisma.Prisma__tb_accountClient<runtime.Types.Result.GetResult<Prisma.$tb_accountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  tb_ms_channel<T extends Prisma.tb_his_failed_login$tb_ms_channelArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.tb_his_failed_login$tb_ms_channelArgs<ExtArgs>>): Prisma.Prisma__tb_ms_channelClient<runtime.Types.Result.GetResult<Prisma.$tb_ms_channelPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the tb_his_failed_login model
 */
export interface tb_his_failed_loginFieldRefs {
  readonly failed_login_id: Prisma.FieldRef<"tb_his_failed_login", 'String'>
  readonly account_id: Prisma.FieldRef<"tb_his_failed_login", 'String'>
  readonly channel_id: Prisma.FieldRef<"tb_his_failed_login", 'BigInt'>
  readonly login_method_id: Prisma.FieldRef<"tb_his_failed_login", 'BigInt'>
  readonly username_input: Prisma.FieldRef<"tb_his_failed_login", 'String'>
  readonly ip_address: Prisma.FieldRef<"tb_his_failed_login", 'String'>
  readonly device_id: Prisma.FieldRef<"tb_his_failed_login", 'String'>
  readonly failure_reason: Prisma.FieldRef<"tb_his_failed_login", 'String'>
  readonly failed_at: Prisma.FieldRef<"tb_his_failed_login", 'DateTime'>
  readonly created_at: Prisma.FieldRef<"tb_his_failed_login", 'DateTime'>
  readonly created_by: Prisma.FieldRef<"tb_his_failed_login", 'String'>
  readonly updated_at: Prisma.FieldRef<"tb_his_failed_login", 'DateTime'>
  readonly update_by: Prisma.FieldRef<"tb_his_failed_login", 'String'>
  readonly record_status: Prisma.FieldRef<"tb_his_failed_login", 'String'>
}
    

// Custom InputTypes
/**
 * tb_his_failed_login findUnique
 */
export type tb_his_failed_loginFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_his_failed_login
   */
  select?: Prisma.tb_his_failed_loginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_his_failed_login
   */
  omit?: Prisma.tb_his_failed_loginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_his_failed_loginInclude<ExtArgs> | null
  /**
   * Filter, which tb_his_failed_login to fetch.
   */
  where: Prisma.tb_his_failed_loginWhereUniqueInput
}

/**
 * tb_his_failed_login findUniqueOrThrow
 */
export type tb_his_failed_loginFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_his_failed_login
   */
  select?: Prisma.tb_his_failed_loginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_his_failed_login
   */
  omit?: Prisma.tb_his_failed_loginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_his_failed_loginInclude<ExtArgs> | null
  /**
   * Filter, which tb_his_failed_login to fetch.
   */
  where: Prisma.tb_his_failed_loginWhereUniqueInput
}

/**
 * tb_his_failed_login findFirst
 */
export type tb_his_failed_loginFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_his_failed_login
   */
  select?: Prisma.tb_his_failed_loginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_his_failed_login
   */
  omit?: Prisma.tb_his_failed_loginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_his_failed_loginInclude<ExtArgs> | null
  /**
   * Filter, which tb_his_failed_login to fetch.
   */
  where?: Prisma.tb_his_failed_loginWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of tb_his_failed_logins to fetch.
   */
  orderBy?: Prisma.tb_his_failed_loginOrderByWithRelationInput | Prisma.tb_his_failed_loginOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for tb_his_failed_logins.
   */
  cursor?: Prisma.tb_his_failed_loginWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` tb_his_failed_logins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` tb_his_failed_logins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of tb_his_failed_logins.
   */
  distinct?: Prisma.Tb_his_failed_loginScalarFieldEnum | Prisma.Tb_his_failed_loginScalarFieldEnum[]
}

/**
 * tb_his_failed_login findFirstOrThrow
 */
export type tb_his_failed_loginFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_his_failed_login
   */
  select?: Prisma.tb_his_failed_loginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_his_failed_login
   */
  omit?: Prisma.tb_his_failed_loginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_his_failed_loginInclude<ExtArgs> | null
  /**
   * Filter, which tb_his_failed_login to fetch.
   */
  where?: Prisma.tb_his_failed_loginWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of tb_his_failed_logins to fetch.
   */
  orderBy?: Prisma.tb_his_failed_loginOrderByWithRelationInput | Prisma.tb_his_failed_loginOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for tb_his_failed_logins.
   */
  cursor?: Prisma.tb_his_failed_loginWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` tb_his_failed_logins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` tb_his_failed_logins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of tb_his_failed_logins.
   */
  distinct?: Prisma.Tb_his_failed_loginScalarFieldEnum | Prisma.Tb_his_failed_loginScalarFieldEnum[]
}

/**
 * tb_his_failed_login findMany
 */
export type tb_his_failed_loginFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_his_failed_login
   */
  select?: Prisma.tb_his_failed_loginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_his_failed_login
   */
  omit?: Prisma.tb_his_failed_loginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_his_failed_loginInclude<ExtArgs> | null
  /**
   * Filter, which tb_his_failed_logins to fetch.
   */
  where?: Prisma.tb_his_failed_loginWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of tb_his_failed_logins to fetch.
   */
  orderBy?: Prisma.tb_his_failed_loginOrderByWithRelationInput | Prisma.tb_his_failed_loginOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing tb_his_failed_logins.
   */
  cursor?: Prisma.tb_his_failed_loginWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` tb_his_failed_logins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` tb_his_failed_logins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of tb_his_failed_logins.
   */
  distinct?: Prisma.Tb_his_failed_loginScalarFieldEnum | Prisma.Tb_his_failed_loginScalarFieldEnum[]
}

/**
 * tb_his_failed_login create
 */
export type tb_his_failed_loginCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_his_failed_login
   */
  select?: Prisma.tb_his_failed_loginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_his_failed_login
   */
  omit?: Prisma.tb_his_failed_loginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_his_failed_loginInclude<ExtArgs> | null
  /**
   * The data needed to create a tb_his_failed_login.
   */
  data: Prisma.XOR<Prisma.tb_his_failed_loginCreateInput, Prisma.tb_his_failed_loginUncheckedCreateInput>
}

/**
 * tb_his_failed_login createMany
 */
export type tb_his_failed_loginCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many tb_his_failed_logins.
   */
  data: Prisma.tb_his_failed_loginCreateManyInput | Prisma.tb_his_failed_loginCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * tb_his_failed_login createManyAndReturn
 */
export type tb_his_failed_loginCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_his_failed_login
   */
  select?: Prisma.tb_his_failed_loginSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the tb_his_failed_login
   */
  omit?: Prisma.tb_his_failed_loginOmit<ExtArgs> | null
  /**
   * The data used to create many tb_his_failed_logins.
   */
  data: Prisma.tb_his_failed_loginCreateManyInput | Prisma.tb_his_failed_loginCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_his_failed_loginIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * tb_his_failed_login update
 */
export type tb_his_failed_loginUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_his_failed_login
   */
  select?: Prisma.tb_his_failed_loginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_his_failed_login
   */
  omit?: Prisma.tb_his_failed_loginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_his_failed_loginInclude<ExtArgs> | null
  /**
   * The data needed to update a tb_his_failed_login.
   */
  data: Prisma.XOR<Prisma.tb_his_failed_loginUpdateInput, Prisma.tb_his_failed_loginUncheckedUpdateInput>
  /**
   * Choose, which tb_his_failed_login to update.
   */
  where: Prisma.tb_his_failed_loginWhereUniqueInput
}

/**
 * tb_his_failed_login updateMany
 */
export type tb_his_failed_loginUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update tb_his_failed_logins.
   */
  data: Prisma.XOR<Prisma.tb_his_failed_loginUpdateManyMutationInput, Prisma.tb_his_failed_loginUncheckedUpdateManyInput>
  /**
   * Filter which tb_his_failed_logins to update
   */
  where?: Prisma.tb_his_failed_loginWhereInput
  /**
   * Limit how many tb_his_failed_logins to update.
   */
  limit?: number
}

/**
 * tb_his_failed_login updateManyAndReturn
 */
export type tb_his_failed_loginUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_his_failed_login
   */
  select?: Prisma.tb_his_failed_loginSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the tb_his_failed_login
   */
  omit?: Prisma.tb_his_failed_loginOmit<ExtArgs> | null
  /**
   * The data used to update tb_his_failed_logins.
   */
  data: Prisma.XOR<Prisma.tb_his_failed_loginUpdateManyMutationInput, Prisma.tb_his_failed_loginUncheckedUpdateManyInput>
  /**
   * Filter which tb_his_failed_logins to update
   */
  where?: Prisma.tb_his_failed_loginWhereInput
  /**
   * Limit how many tb_his_failed_logins to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_his_failed_loginIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * tb_his_failed_login upsert
 */
export type tb_his_failed_loginUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_his_failed_login
   */
  select?: Prisma.tb_his_failed_loginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_his_failed_login
   */
  omit?: Prisma.tb_his_failed_loginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_his_failed_loginInclude<ExtArgs> | null
  /**
   * The filter to search for the tb_his_failed_login to update in case it exists.
   */
  where: Prisma.tb_his_failed_loginWhereUniqueInput
  /**
   * In case the tb_his_failed_login found by the `where` argument doesn't exist, create a new tb_his_failed_login with this data.
   */
  create: Prisma.XOR<Prisma.tb_his_failed_loginCreateInput, Prisma.tb_his_failed_loginUncheckedCreateInput>
  /**
   * In case the tb_his_failed_login was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.tb_his_failed_loginUpdateInput, Prisma.tb_his_failed_loginUncheckedUpdateInput>
}

/**
 * tb_his_failed_login delete
 */
export type tb_his_failed_loginDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_his_failed_login
   */
  select?: Prisma.tb_his_failed_loginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_his_failed_login
   */
  omit?: Prisma.tb_his_failed_loginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_his_failed_loginInclude<ExtArgs> | null
  /**
   * Filter which tb_his_failed_login to delete.
   */
  where: Prisma.tb_his_failed_loginWhereUniqueInput
}

/**
 * tb_his_failed_login deleteMany
 */
export type tb_his_failed_loginDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which tb_his_failed_logins to delete
   */
  where?: Prisma.tb_his_failed_loginWhereInput
  /**
   * Limit how many tb_his_failed_logins to delete.
   */
  limit?: number
}

/**
 * tb_his_failed_login.tb_ms_channel
 */
export type tb_his_failed_login$tb_ms_channelArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_channel
   */
  select?: Prisma.tb_ms_channelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_channel
   */
  omit?: Prisma.tb_ms_channelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_channelInclude<ExtArgs> | null
  where?: Prisma.tb_ms_channelWhereInput
}

/**
 * tb_his_failed_login without action
 */
export type tb_his_failed_loginDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_his_failed_login
   */
  select?: Prisma.tb_his_failed_loginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_his_failed_login
   */
  omit?: Prisma.tb_his_failed_loginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_his_failed_loginInclude<ExtArgs> | null
}
