
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `tb_ms_user_type` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model tb_ms_user_type
 * This model or at least one of its fields has comments in the database, and requires an additional setup for migrations: Read more: https://pris.ly/d/database-comments
 */
export type tb_ms_user_typeModel = runtime.Types.Result.DefaultSelection<Prisma.$tb_ms_user_typePayload>

export type AggregateTb_ms_user_type = {
  _count: Tb_ms_user_typeCountAggregateOutputType | null
  _avg: Tb_ms_user_typeAvgAggregateOutputType | null
  _sum: Tb_ms_user_typeSumAggregateOutputType | null
  _min: Tb_ms_user_typeMinAggregateOutputType | null
  _max: Tb_ms_user_typeMaxAggregateOutputType | null
}

export type Tb_ms_user_typeAvgAggregateOutputType = {
  user_type_id: number | null
  display_order: number | null
}

export type Tb_ms_user_typeSumAggregateOutputType = {
  user_type_id: bigint | null
  display_order: number | null
}

export type Tb_ms_user_typeMinAggregateOutputType = {
  user_type_id: bigint | null
  user_type_code: string | null
  user_type_name: string | null
  description: string | null
  default_role_code: string | null
  registration_allowed: boolean | null
  login_allowed: boolean | null
  require_identity_verify: boolean | null
  require_document: boolean | null
  is_internal_user: boolean | null
  record_status: string | null
  require_office_verify: boolean | null
  display_order: number | null
  created_at: Date | null
  updated_at: Date | null
  update_by: string | null
  created_by: string | null
}

export type Tb_ms_user_typeMaxAggregateOutputType = {
  user_type_id: bigint | null
  user_type_code: string | null
  user_type_name: string | null
  description: string | null
  default_role_code: string | null
  registration_allowed: boolean | null
  login_allowed: boolean | null
  require_identity_verify: boolean | null
  require_document: boolean | null
  is_internal_user: boolean | null
  record_status: string | null
  require_office_verify: boolean | null
  display_order: number | null
  created_at: Date | null
  updated_at: Date | null
  update_by: string | null
  created_by: string | null
}

export type Tb_ms_user_typeCountAggregateOutputType = {
  user_type_id: number
  user_type_code: number
  user_type_name: number
  description: number
  default_role_code: number
  registration_allowed: number
  login_allowed: number
  require_identity_verify: number
  require_document: number
  is_internal_user: number
  record_status: number
  require_office_verify: number
  display_order: number
  created_at: number
  updated_at: number
  update_by: number
  created_by: number
  _all: number
}


export type Tb_ms_user_typeAvgAggregateInputType = {
  user_type_id?: true
  display_order?: true
}

export type Tb_ms_user_typeSumAggregateInputType = {
  user_type_id?: true
  display_order?: true
}

export type Tb_ms_user_typeMinAggregateInputType = {
  user_type_id?: true
  user_type_code?: true
  user_type_name?: true
  description?: true
  default_role_code?: true
  registration_allowed?: true
  login_allowed?: true
  require_identity_verify?: true
  require_document?: true
  is_internal_user?: true
  record_status?: true
  require_office_verify?: true
  display_order?: true
  created_at?: true
  updated_at?: true
  update_by?: true
  created_by?: true
}

export type Tb_ms_user_typeMaxAggregateInputType = {
  user_type_id?: true
  user_type_code?: true
  user_type_name?: true
  description?: true
  default_role_code?: true
  registration_allowed?: true
  login_allowed?: true
  require_identity_verify?: true
  require_document?: true
  is_internal_user?: true
  record_status?: true
  require_office_verify?: true
  display_order?: true
  created_at?: true
  updated_at?: true
  update_by?: true
  created_by?: true
}

export type Tb_ms_user_typeCountAggregateInputType = {
  user_type_id?: true
  user_type_code?: true
  user_type_name?: true
  description?: true
  default_role_code?: true
  registration_allowed?: true
  login_allowed?: true
  require_identity_verify?: true
  require_document?: true
  is_internal_user?: true
  record_status?: true
  require_office_verify?: true
  display_order?: true
  created_at?: true
  updated_at?: true
  update_by?: true
  created_by?: true
  _all?: true
}

export type Tb_ms_user_typeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which tb_ms_user_type to aggregate.
   */
  where?: Prisma.tb_ms_user_typeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of tb_ms_user_types to fetch.
   */
  orderBy?: Prisma.tb_ms_user_typeOrderByWithRelationInput | Prisma.tb_ms_user_typeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.tb_ms_user_typeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` tb_ms_user_types from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` tb_ms_user_types.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned tb_ms_user_types
  **/
  _count?: true | Tb_ms_user_typeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Tb_ms_user_typeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Tb_ms_user_typeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Tb_ms_user_typeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Tb_ms_user_typeMaxAggregateInputType
}

export type GetTb_ms_user_typeAggregateType<T extends Tb_ms_user_typeAggregateArgs> = {
      [P in keyof T & keyof AggregateTb_ms_user_type]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTb_ms_user_type[P]>
    : Prisma.GetScalarType<T[P], AggregateTb_ms_user_type[P]>
}




export type tb_ms_user_typeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.tb_ms_user_typeWhereInput
  orderBy?: Prisma.tb_ms_user_typeOrderByWithAggregationInput | Prisma.tb_ms_user_typeOrderByWithAggregationInput[]
  by: Prisma.Tb_ms_user_typeScalarFieldEnum[] | Prisma.Tb_ms_user_typeScalarFieldEnum
  having?: Prisma.tb_ms_user_typeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Tb_ms_user_typeCountAggregateInputType | true
  _avg?: Tb_ms_user_typeAvgAggregateInputType
  _sum?: Tb_ms_user_typeSumAggregateInputType
  _min?: Tb_ms_user_typeMinAggregateInputType
  _max?: Tb_ms_user_typeMaxAggregateInputType
}

export type Tb_ms_user_typeGroupByOutputType = {
  user_type_id: bigint
  user_type_code: string
  user_type_name: string
  description: string | null
  default_role_code: string | null
  registration_allowed: boolean
  login_allowed: boolean
  require_identity_verify: boolean
  require_document: boolean
  is_internal_user: boolean
  record_status: string | null
  require_office_verify: boolean | null
  display_order: number | null
  created_at: Date
  updated_at: Date | null
  update_by: string | null
  created_by: string | null
  _count: Tb_ms_user_typeCountAggregateOutputType | null
  _avg: Tb_ms_user_typeAvgAggregateOutputType | null
  _sum: Tb_ms_user_typeSumAggregateOutputType | null
  _min: Tb_ms_user_typeMinAggregateOutputType | null
  _max: Tb_ms_user_typeMaxAggregateOutputType | null
}

export type GetTb_ms_user_typeGroupByPayload<T extends tb_ms_user_typeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Tb_ms_user_typeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Tb_ms_user_typeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Tb_ms_user_typeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Tb_ms_user_typeGroupByOutputType[P]>
      }
    >
  >



export type tb_ms_user_typeWhereInput = {
  AND?: Prisma.tb_ms_user_typeWhereInput | Prisma.tb_ms_user_typeWhereInput[]
  OR?: Prisma.tb_ms_user_typeWhereInput[]
  NOT?: Prisma.tb_ms_user_typeWhereInput | Prisma.tb_ms_user_typeWhereInput[]
  user_type_id?: Prisma.BigIntFilter<"tb_ms_user_type"> | bigint | number
  user_type_code?: Prisma.StringFilter<"tb_ms_user_type"> | string
  user_type_name?: Prisma.StringFilter<"tb_ms_user_type"> | string
  description?: Prisma.StringNullableFilter<"tb_ms_user_type"> | string | null
  default_role_code?: Prisma.StringNullableFilter<"tb_ms_user_type"> | string | null
  registration_allowed?: Prisma.BoolFilter<"tb_ms_user_type"> | boolean
  login_allowed?: Prisma.BoolFilter<"tb_ms_user_type"> | boolean
  require_identity_verify?: Prisma.BoolFilter<"tb_ms_user_type"> | boolean
  require_document?: Prisma.BoolFilter<"tb_ms_user_type"> | boolean
  is_internal_user?: Prisma.BoolFilter<"tb_ms_user_type"> | boolean
  record_status?: Prisma.StringNullableFilter<"tb_ms_user_type"> | string | null
  require_office_verify?: Prisma.BoolNullableFilter<"tb_ms_user_type"> | boolean | null
  display_order?: Prisma.IntNullableFilter<"tb_ms_user_type"> | number | null
  created_at?: Prisma.DateTimeFilter<"tb_ms_user_type"> | Date | string
  updated_at?: Prisma.DateTimeNullableFilter<"tb_ms_user_type"> | Date | string | null
  update_by?: Prisma.UuidNullableFilter<"tb_ms_user_type"> | string | null
  created_by?: Prisma.UuidNullableFilter<"tb_ms_user_type"> | string | null
  tb_user?: Prisma.Tb_userListRelationFilter
}

export type tb_ms_user_typeOrderByWithRelationInput = {
  user_type_id?: Prisma.SortOrder
  user_type_code?: Prisma.SortOrder
  user_type_name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  default_role_code?: Prisma.SortOrderInput | Prisma.SortOrder
  registration_allowed?: Prisma.SortOrder
  login_allowed?: Prisma.SortOrder
  require_identity_verify?: Prisma.SortOrder
  require_document?: Prisma.SortOrder
  is_internal_user?: Prisma.SortOrder
  record_status?: Prisma.SortOrderInput | Prisma.SortOrder
  require_office_verify?: Prisma.SortOrderInput | Prisma.SortOrder
  display_order?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  update_by?: Prisma.SortOrderInput | Prisma.SortOrder
  created_by?: Prisma.SortOrderInput | Prisma.SortOrder
  tb_user?: Prisma.tb_userOrderByRelationAggregateInput
}

export type tb_ms_user_typeWhereUniqueInput = Prisma.AtLeast<{
  user_type_id?: bigint | number
  AND?: Prisma.tb_ms_user_typeWhereInput | Prisma.tb_ms_user_typeWhereInput[]
  OR?: Prisma.tb_ms_user_typeWhereInput[]
  NOT?: Prisma.tb_ms_user_typeWhereInput | Prisma.tb_ms_user_typeWhereInput[]
  user_type_code?: Prisma.StringFilter<"tb_ms_user_type"> | string
  user_type_name?: Prisma.StringFilter<"tb_ms_user_type"> | string
  description?: Prisma.StringNullableFilter<"tb_ms_user_type"> | string | null
  default_role_code?: Prisma.StringNullableFilter<"tb_ms_user_type"> | string | null
  registration_allowed?: Prisma.BoolFilter<"tb_ms_user_type"> | boolean
  login_allowed?: Prisma.BoolFilter<"tb_ms_user_type"> | boolean
  require_identity_verify?: Prisma.BoolFilter<"tb_ms_user_type"> | boolean
  require_document?: Prisma.BoolFilter<"tb_ms_user_type"> | boolean
  is_internal_user?: Prisma.BoolFilter<"tb_ms_user_type"> | boolean
  record_status?: Prisma.StringNullableFilter<"tb_ms_user_type"> | string | null
  require_office_verify?: Prisma.BoolNullableFilter<"tb_ms_user_type"> | boolean | null
  display_order?: Prisma.IntNullableFilter<"tb_ms_user_type"> | number | null
  created_at?: Prisma.DateTimeFilter<"tb_ms_user_type"> | Date | string
  updated_at?: Prisma.DateTimeNullableFilter<"tb_ms_user_type"> | Date | string | null
  update_by?: Prisma.UuidNullableFilter<"tb_ms_user_type"> | string | null
  created_by?: Prisma.UuidNullableFilter<"tb_ms_user_type"> | string | null
  tb_user?: Prisma.Tb_userListRelationFilter
}, "user_type_id">

export type tb_ms_user_typeOrderByWithAggregationInput = {
  user_type_id?: Prisma.SortOrder
  user_type_code?: Prisma.SortOrder
  user_type_name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  default_role_code?: Prisma.SortOrderInput | Prisma.SortOrder
  registration_allowed?: Prisma.SortOrder
  login_allowed?: Prisma.SortOrder
  require_identity_verify?: Prisma.SortOrder
  require_document?: Prisma.SortOrder
  is_internal_user?: Prisma.SortOrder
  record_status?: Prisma.SortOrderInput | Prisma.SortOrder
  require_office_verify?: Prisma.SortOrderInput | Prisma.SortOrder
  display_order?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  update_by?: Prisma.SortOrderInput | Prisma.SortOrder
  created_by?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.tb_ms_user_typeCountOrderByAggregateInput
  _avg?: Prisma.tb_ms_user_typeAvgOrderByAggregateInput
  _max?: Prisma.tb_ms_user_typeMaxOrderByAggregateInput
  _min?: Prisma.tb_ms_user_typeMinOrderByAggregateInput
  _sum?: Prisma.tb_ms_user_typeSumOrderByAggregateInput
}

export type tb_ms_user_typeScalarWhereWithAggregatesInput = {
  AND?: Prisma.tb_ms_user_typeScalarWhereWithAggregatesInput | Prisma.tb_ms_user_typeScalarWhereWithAggregatesInput[]
  OR?: Prisma.tb_ms_user_typeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.tb_ms_user_typeScalarWhereWithAggregatesInput | Prisma.tb_ms_user_typeScalarWhereWithAggregatesInput[]
  user_type_id?: Prisma.BigIntWithAggregatesFilter<"tb_ms_user_type"> | bigint | number
  user_type_code?: Prisma.StringWithAggregatesFilter<"tb_ms_user_type"> | string
  user_type_name?: Prisma.StringWithAggregatesFilter<"tb_ms_user_type"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"tb_ms_user_type"> | string | null
  default_role_code?: Prisma.StringNullableWithAggregatesFilter<"tb_ms_user_type"> | string | null
  registration_allowed?: Prisma.BoolWithAggregatesFilter<"tb_ms_user_type"> | boolean
  login_allowed?: Prisma.BoolWithAggregatesFilter<"tb_ms_user_type"> | boolean
  require_identity_verify?: Prisma.BoolWithAggregatesFilter<"tb_ms_user_type"> | boolean
  require_document?: Prisma.BoolWithAggregatesFilter<"tb_ms_user_type"> | boolean
  is_internal_user?: Prisma.BoolWithAggregatesFilter<"tb_ms_user_type"> | boolean
  record_status?: Prisma.StringNullableWithAggregatesFilter<"tb_ms_user_type"> | string | null
  require_office_verify?: Prisma.BoolNullableWithAggregatesFilter<"tb_ms_user_type"> | boolean | null
  display_order?: Prisma.IntNullableWithAggregatesFilter<"tb_ms_user_type"> | number | null
  created_at?: Prisma.DateTimeWithAggregatesFilter<"tb_ms_user_type"> | Date | string
  updated_at?: Prisma.DateTimeNullableWithAggregatesFilter<"tb_ms_user_type"> | Date | string | null
  update_by?: Prisma.UuidNullableWithAggregatesFilter<"tb_ms_user_type"> | string | null
  created_by?: Prisma.UuidNullableWithAggregatesFilter<"tb_ms_user_type"> | string | null
}

export type tb_ms_user_typeCreateInput = {
  user_type_id?: bigint | number
  user_type_code: string
  user_type_name: string
  description?: string | null
  default_role_code?: string | null
  registration_allowed?: boolean
  login_allowed?: boolean
  require_identity_verify?: boolean
  require_document?: boolean
  is_internal_user?: boolean
  record_status?: string | null
  require_office_verify?: boolean | null
  display_order?: number | null
  created_at?: Date | string
  updated_at?: Date | string | null
  update_by?: string | null
  created_by?: string | null
  tb_user?: Prisma.tb_userCreateNestedManyWithoutTb_ms_user_typeInput
}

export type tb_ms_user_typeUncheckedCreateInput = {
  user_type_id?: bigint | number
  user_type_code: string
  user_type_name: string
  description?: string | null
  default_role_code?: string | null
  registration_allowed?: boolean
  login_allowed?: boolean
  require_identity_verify?: boolean
  require_document?: boolean
  is_internal_user?: boolean
  record_status?: string | null
  require_office_verify?: boolean | null
  display_order?: number | null
  created_at?: Date | string
  updated_at?: Date | string | null
  update_by?: string | null
  created_by?: string | null
  tb_user?: Prisma.tb_userUncheckedCreateNestedManyWithoutTb_ms_user_typeInput
}

export type tb_ms_user_typeUpdateInput = {
  user_type_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  user_type_code?: Prisma.StringFieldUpdateOperationsInput | string
  user_type_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  default_role_code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  registration_allowed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  login_allowed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  require_identity_verify?: Prisma.BoolFieldUpdateOperationsInput | boolean
  require_document?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_internal_user?: Prisma.BoolFieldUpdateOperationsInput | boolean
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  require_office_verify?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  display_order?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tb_user?: Prisma.tb_userUpdateManyWithoutTb_ms_user_typeNestedInput
}

export type tb_ms_user_typeUncheckedUpdateInput = {
  user_type_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  user_type_code?: Prisma.StringFieldUpdateOperationsInput | string
  user_type_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  default_role_code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  registration_allowed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  login_allowed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  require_identity_verify?: Prisma.BoolFieldUpdateOperationsInput | boolean
  require_document?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_internal_user?: Prisma.BoolFieldUpdateOperationsInput | boolean
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  require_office_verify?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  display_order?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tb_user?: Prisma.tb_userUncheckedUpdateManyWithoutTb_ms_user_typeNestedInput
}

export type tb_ms_user_typeCreateManyInput = {
  user_type_id?: bigint | number
  user_type_code: string
  user_type_name: string
  description?: string | null
  default_role_code?: string | null
  registration_allowed?: boolean
  login_allowed?: boolean
  require_identity_verify?: boolean
  require_document?: boolean
  is_internal_user?: boolean
  record_status?: string | null
  require_office_verify?: boolean | null
  display_order?: number | null
  created_at?: Date | string
  updated_at?: Date | string | null
  update_by?: string | null
  created_by?: string | null
}

export type tb_ms_user_typeUpdateManyMutationInput = {
  user_type_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  user_type_code?: Prisma.StringFieldUpdateOperationsInput | string
  user_type_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  default_role_code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  registration_allowed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  login_allowed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  require_identity_verify?: Prisma.BoolFieldUpdateOperationsInput | boolean
  require_document?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_internal_user?: Prisma.BoolFieldUpdateOperationsInput | boolean
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  require_office_verify?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  display_order?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type tb_ms_user_typeUncheckedUpdateManyInput = {
  user_type_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  user_type_code?: Prisma.StringFieldUpdateOperationsInput | string
  user_type_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  default_role_code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  registration_allowed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  login_allowed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  require_identity_verify?: Prisma.BoolFieldUpdateOperationsInput | boolean
  require_document?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_internal_user?: Prisma.BoolFieldUpdateOperationsInput | boolean
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  require_office_verify?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  display_order?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type tb_ms_user_typeCountOrderByAggregateInput = {
  user_type_id?: Prisma.SortOrder
  user_type_code?: Prisma.SortOrder
  user_type_name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  default_role_code?: Prisma.SortOrder
  registration_allowed?: Prisma.SortOrder
  login_allowed?: Prisma.SortOrder
  require_identity_verify?: Prisma.SortOrder
  require_document?: Prisma.SortOrder
  is_internal_user?: Prisma.SortOrder
  record_status?: Prisma.SortOrder
  require_office_verify?: Prisma.SortOrder
  display_order?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  update_by?: Prisma.SortOrder
  created_by?: Prisma.SortOrder
}

export type tb_ms_user_typeAvgOrderByAggregateInput = {
  user_type_id?: Prisma.SortOrder
  display_order?: Prisma.SortOrder
}

export type tb_ms_user_typeMaxOrderByAggregateInput = {
  user_type_id?: Prisma.SortOrder
  user_type_code?: Prisma.SortOrder
  user_type_name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  default_role_code?: Prisma.SortOrder
  registration_allowed?: Prisma.SortOrder
  login_allowed?: Prisma.SortOrder
  require_identity_verify?: Prisma.SortOrder
  require_document?: Prisma.SortOrder
  is_internal_user?: Prisma.SortOrder
  record_status?: Prisma.SortOrder
  require_office_verify?: Prisma.SortOrder
  display_order?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  update_by?: Prisma.SortOrder
  created_by?: Prisma.SortOrder
}

export type tb_ms_user_typeMinOrderByAggregateInput = {
  user_type_id?: Prisma.SortOrder
  user_type_code?: Prisma.SortOrder
  user_type_name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  default_role_code?: Prisma.SortOrder
  registration_allowed?: Prisma.SortOrder
  login_allowed?: Prisma.SortOrder
  require_identity_verify?: Prisma.SortOrder
  require_document?: Prisma.SortOrder
  is_internal_user?: Prisma.SortOrder
  record_status?: Prisma.SortOrder
  require_office_verify?: Prisma.SortOrder
  display_order?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  update_by?: Prisma.SortOrder
  created_by?: Prisma.SortOrder
}

export type tb_ms_user_typeSumOrderByAggregateInput = {
  user_type_id?: Prisma.SortOrder
  display_order?: Prisma.SortOrder
}

export type Tb_ms_user_typeScalarRelationFilter = {
  is?: Prisma.tb_ms_user_typeWhereInput
  isNot?: Prisma.tb_ms_user_typeWhereInput
}

export type tb_ms_user_typeCreateNestedOneWithoutTb_userInput = {
  create?: Prisma.XOR<Prisma.tb_ms_user_typeCreateWithoutTb_userInput, Prisma.tb_ms_user_typeUncheckedCreateWithoutTb_userInput>
  connectOrCreate?: Prisma.tb_ms_user_typeCreateOrConnectWithoutTb_userInput
  connect?: Prisma.tb_ms_user_typeWhereUniqueInput
}

export type tb_ms_user_typeUpdateOneRequiredWithoutTb_userNestedInput = {
  create?: Prisma.XOR<Prisma.tb_ms_user_typeCreateWithoutTb_userInput, Prisma.tb_ms_user_typeUncheckedCreateWithoutTb_userInput>
  connectOrCreate?: Prisma.tb_ms_user_typeCreateOrConnectWithoutTb_userInput
  upsert?: Prisma.tb_ms_user_typeUpsertWithoutTb_userInput
  connect?: Prisma.tb_ms_user_typeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.tb_ms_user_typeUpdateToOneWithWhereWithoutTb_userInput, Prisma.tb_ms_user_typeUpdateWithoutTb_userInput>, Prisma.tb_ms_user_typeUncheckedUpdateWithoutTb_userInput>
}

export type tb_ms_user_typeCreateWithoutTb_userInput = {
  user_type_id?: bigint | number
  user_type_code: string
  user_type_name: string
  description?: string | null
  default_role_code?: string | null
  registration_allowed?: boolean
  login_allowed?: boolean
  require_identity_verify?: boolean
  require_document?: boolean
  is_internal_user?: boolean
  record_status?: string | null
  require_office_verify?: boolean | null
  display_order?: number | null
  created_at?: Date | string
  updated_at?: Date | string | null
  update_by?: string | null
  created_by?: string | null
}

export type tb_ms_user_typeUncheckedCreateWithoutTb_userInput = {
  user_type_id?: bigint | number
  user_type_code: string
  user_type_name: string
  description?: string | null
  default_role_code?: string | null
  registration_allowed?: boolean
  login_allowed?: boolean
  require_identity_verify?: boolean
  require_document?: boolean
  is_internal_user?: boolean
  record_status?: string | null
  require_office_verify?: boolean | null
  display_order?: number | null
  created_at?: Date | string
  updated_at?: Date | string | null
  update_by?: string | null
  created_by?: string | null
}

export type tb_ms_user_typeCreateOrConnectWithoutTb_userInput = {
  where: Prisma.tb_ms_user_typeWhereUniqueInput
  create: Prisma.XOR<Prisma.tb_ms_user_typeCreateWithoutTb_userInput, Prisma.tb_ms_user_typeUncheckedCreateWithoutTb_userInput>
}

export type tb_ms_user_typeUpsertWithoutTb_userInput = {
  update: Prisma.XOR<Prisma.tb_ms_user_typeUpdateWithoutTb_userInput, Prisma.tb_ms_user_typeUncheckedUpdateWithoutTb_userInput>
  create: Prisma.XOR<Prisma.tb_ms_user_typeCreateWithoutTb_userInput, Prisma.tb_ms_user_typeUncheckedCreateWithoutTb_userInput>
  where?: Prisma.tb_ms_user_typeWhereInput
}

export type tb_ms_user_typeUpdateToOneWithWhereWithoutTb_userInput = {
  where?: Prisma.tb_ms_user_typeWhereInput
  data: Prisma.XOR<Prisma.tb_ms_user_typeUpdateWithoutTb_userInput, Prisma.tb_ms_user_typeUncheckedUpdateWithoutTb_userInput>
}

export type tb_ms_user_typeUpdateWithoutTb_userInput = {
  user_type_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  user_type_code?: Prisma.StringFieldUpdateOperationsInput | string
  user_type_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  default_role_code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  registration_allowed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  login_allowed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  require_identity_verify?: Prisma.BoolFieldUpdateOperationsInput | boolean
  require_document?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_internal_user?: Prisma.BoolFieldUpdateOperationsInput | boolean
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  require_office_verify?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  display_order?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type tb_ms_user_typeUncheckedUpdateWithoutTb_userInput = {
  user_type_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  user_type_code?: Prisma.StringFieldUpdateOperationsInput | string
  user_type_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  default_role_code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  registration_allowed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  login_allowed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  require_identity_verify?: Prisma.BoolFieldUpdateOperationsInput | boolean
  require_document?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_internal_user?: Prisma.BoolFieldUpdateOperationsInput | boolean
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  require_office_verify?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  display_order?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type Tb_ms_user_typeCountOutputType
 */

export type Tb_ms_user_typeCountOutputType = {
  tb_user: number
}

export type Tb_ms_user_typeCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tb_user?: boolean | Tb_ms_user_typeCountOutputTypeCountTb_userArgs
}

/**
 * Tb_ms_user_typeCountOutputType without action
 */
export type Tb_ms_user_typeCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tb_ms_user_typeCountOutputType
   */
  select?: Prisma.Tb_ms_user_typeCountOutputTypeSelect<ExtArgs> | null
}

/**
 * Tb_ms_user_typeCountOutputType without action
 */
export type Tb_ms_user_typeCountOutputTypeCountTb_userArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.tb_userWhereInput
}


export type tb_ms_user_typeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_type_id?: boolean
  user_type_code?: boolean
  user_type_name?: boolean
  description?: boolean
  default_role_code?: boolean
  registration_allowed?: boolean
  login_allowed?: boolean
  require_identity_verify?: boolean
  require_document?: boolean
  is_internal_user?: boolean
  record_status?: boolean
  require_office_verify?: boolean
  display_order?: boolean
  created_at?: boolean
  updated_at?: boolean
  update_by?: boolean
  created_by?: boolean
  tb_user?: boolean | Prisma.tb_ms_user_type$tb_userArgs<ExtArgs>
  _count?: boolean | Prisma.Tb_ms_user_typeCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tb_ms_user_type"]>

export type tb_ms_user_typeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_type_id?: boolean
  user_type_code?: boolean
  user_type_name?: boolean
  description?: boolean
  default_role_code?: boolean
  registration_allowed?: boolean
  login_allowed?: boolean
  require_identity_verify?: boolean
  require_document?: boolean
  is_internal_user?: boolean
  record_status?: boolean
  require_office_verify?: boolean
  display_order?: boolean
  created_at?: boolean
  updated_at?: boolean
  update_by?: boolean
  created_by?: boolean
}, ExtArgs["result"]["tb_ms_user_type"]>

export type tb_ms_user_typeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_type_id?: boolean
  user_type_code?: boolean
  user_type_name?: boolean
  description?: boolean
  default_role_code?: boolean
  registration_allowed?: boolean
  login_allowed?: boolean
  require_identity_verify?: boolean
  require_document?: boolean
  is_internal_user?: boolean
  record_status?: boolean
  require_office_verify?: boolean
  display_order?: boolean
  created_at?: boolean
  updated_at?: boolean
  update_by?: boolean
  created_by?: boolean
}, ExtArgs["result"]["tb_ms_user_type"]>

export type tb_ms_user_typeSelectScalar = {
  user_type_id?: boolean
  user_type_code?: boolean
  user_type_name?: boolean
  description?: boolean
  default_role_code?: boolean
  registration_allowed?: boolean
  login_allowed?: boolean
  require_identity_verify?: boolean
  require_document?: boolean
  is_internal_user?: boolean
  record_status?: boolean
  require_office_verify?: boolean
  display_order?: boolean
  created_at?: boolean
  updated_at?: boolean
  update_by?: boolean
  created_by?: boolean
}

export type tb_ms_user_typeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"user_type_id" | "user_type_code" | "user_type_name" | "description" | "default_role_code" | "registration_allowed" | "login_allowed" | "require_identity_verify" | "require_document" | "is_internal_user" | "record_status" | "require_office_verify" | "display_order" | "created_at" | "updated_at" | "update_by" | "created_by", ExtArgs["result"]["tb_ms_user_type"]>
export type tb_ms_user_typeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tb_user?: boolean | Prisma.tb_ms_user_type$tb_userArgs<ExtArgs>
  _count?: boolean | Prisma.Tb_ms_user_typeCountOutputTypeDefaultArgs<ExtArgs>
}
export type tb_ms_user_typeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type tb_ms_user_typeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $tb_ms_user_typePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "tb_ms_user_type"
  objects: {
    tb_user: Prisma.$tb_userPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    user_type_id: bigint
    user_type_code: string
    user_type_name: string
    description: string | null
    default_role_code: string | null
    registration_allowed: boolean
    login_allowed: boolean
    require_identity_verify: boolean
    require_document: boolean
    is_internal_user: boolean
    record_status: string | null
    require_office_verify: boolean | null
    display_order: number | null
    created_at: Date
    updated_at: Date | null
    update_by: string | null
    created_by: string | null
  }, ExtArgs["result"]["tb_ms_user_type"]>
  composites: {}
}

export type tb_ms_user_typeGetPayload<S extends boolean | null | undefined | tb_ms_user_typeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$tb_ms_user_typePayload, S>

export type tb_ms_user_typeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<tb_ms_user_typeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Tb_ms_user_typeCountAggregateInputType | true
  }

export interface tb_ms_user_typeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['tb_ms_user_type'], meta: { name: 'tb_ms_user_type' } }
  /**
   * Find zero or one Tb_ms_user_type that matches the filter.
   * @param {tb_ms_user_typeFindUniqueArgs} args - Arguments to find a Tb_ms_user_type
   * @example
   * // Get one Tb_ms_user_type
   * const tb_ms_user_type = await prisma.tb_ms_user_type.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends tb_ms_user_typeFindUniqueArgs>(args: Prisma.SelectSubset<T, tb_ms_user_typeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__tb_ms_user_typeClient<runtime.Types.Result.GetResult<Prisma.$tb_ms_user_typePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Tb_ms_user_type that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {tb_ms_user_typeFindUniqueOrThrowArgs} args - Arguments to find a Tb_ms_user_type
   * @example
   * // Get one Tb_ms_user_type
   * const tb_ms_user_type = await prisma.tb_ms_user_type.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends tb_ms_user_typeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, tb_ms_user_typeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__tb_ms_user_typeClient<runtime.Types.Result.GetResult<Prisma.$tb_ms_user_typePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tb_ms_user_type that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {tb_ms_user_typeFindFirstArgs} args - Arguments to find a Tb_ms_user_type
   * @example
   * // Get one Tb_ms_user_type
   * const tb_ms_user_type = await prisma.tb_ms_user_type.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends tb_ms_user_typeFindFirstArgs>(args?: Prisma.SelectSubset<T, tb_ms_user_typeFindFirstArgs<ExtArgs>>): Prisma.Prisma__tb_ms_user_typeClient<runtime.Types.Result.GetResult<Prisma.$tb_ms_user_typePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tb_ms_user_type that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {tb_ms_user_typeFindFirstOrThrowArgs} args - Arguments to find a Tb_ms_user_type
   * @example
   * // Get one Tb_ms_user_type
   * const tb_ms_user_type = await prisma.tb_ms_user_type.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends tb_ms_user_typeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, tb_ms_user_typeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__tb_ms_user_typeClient<runtime.Types.Result.GetResult<Prisma.$tb_ms_user_typePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Tb_ms_user_types that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {tb_ms_user_typeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Tb_ms_user_types
   * const tb_ms_user_types = await prisma.tb_ms_user_type.findMany()
   * 
   * // Get first 10 Tb_ms_user_types
   * const tb_ms_user_types = await prisma.tb_ms_user_type.findMany({ take: 10 })
   * 
   * // Only select the `user_type_id`
   * const tb_ms_user_typeWithUser_type_idOnly = await prisma.tb_ms_user_type.findMany({ select: { user_type_id: true } })
   * 
   */
  findMany<T extends tb_ms_user_typeFindManyArgs>(args?: Prisma.SelectSubset<T, tb_ms_user_typeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$tb_ms_user_typePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Tb_ms_user_type.
   * @param {tb_ms_user_typeCreateArgs} args - Arguments to create a Tb_ms_user_type.
   * @example
   * // Create one Tb_ms_user_type
   * const Tb_ms_user_type = await prisma.tb_ms_user_type.create({
   *   data: {
   *     // ... data to create a Tb_ms_user_type
   *   }
   * })
   * 
   */
  create<T extends tb_ms_user_typeCreateArgs>(args: Prisma.SelectSubset<T, tb_ms_user_typeCreateArgs<ExtArgs>>): Prisma.Prisma__tb_ms_user_typeClient<runtime.Types.Result.GetResult<Prisma.$tb_ms_user_typePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Tb_ms_user_types.
   * @param {tb_ms_user_typeCreateManyArgs} args - Arguments to create many Tb_ms_user_types.
   * @example
   * // Create many Tb_ms_user_types
   * const tb_ms_user_type = await prisma.tb_ms_user_type.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends tb_ms_user_typeCreateManyArgs>(args?: Prisma.SelectSubset<T, tb_ms_user_typeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Tb_ms_user_types and returns the data saved in the database.
   * @param {tb_ms_user_typeCreateManyAndReturnArgs} args - Arguments to create many Tb_ms_user_types.
   * @example
   * // Create many Tb_ms_user_types
   * const tb_ms_user_type = await prisma.tb_ms_user_type.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Tb_ms_user_types and only return the `user_type_id`
   * const tb_ms_user_typeWithUser_type_idOnly = await prisma.tb_ms_user_type.createManyAndReturn({
   *   select: { user_type_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends tb_ms_user_typeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, tb_ms_user_typeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$tb_ms_user_typePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Tb_ms_user_type.
   * @param {tb_ms_user_typeDeleteArgs} args - Arguments to delete one Tb_ms_user_type.
   * @example
   * // Delete one Tb_ms_user_type
   * const Tb_ms_user_type = await prisma.tb_ms_user_type.delete({
   *   where: {
   *     // ... filter to delete one Tb_ms_user_type
   *   }
   * })
   * 
   */
  delete<T extends tb_ms_user_typeDeleteArgs>(args: Prisma.SelectSubset<T, tb_ms_user_typeDeleteArgs<ExtArgs>>): Prisma.Prisma__tb_ms_user_typeClient<runtime.Types.Result.GetResult<Prisma.$tb_ms_user_typePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Tb_ms_user_type.
   * @param {tb_ms_user_typeUpdateArgs} args - Arguments to update one Tb_ms_user_type.
   * @example
   * // Update one Tb_ms_user_type
   * const tb_ms_user_type = await prisma.tb_ms_user_type.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends tb_ms_user_typeUpdateArgs>(args: Prisma.SelectSubset<T, tb_ms_user_typeUpdateArgs<ExtArgs>>): Prisma.Prisma__tb_ms_user_typeClient<runtime.Types.Result.GetResult<Prisma.$tb_ms_user_typePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Tb_ms_user_types.
   * @param {tb_ms_user_typeDeleteManyArgs} args - Arguments to filter Tb_ms_user_types to delete.
   * @example
   * // Delete a few Tb_ms_user_types
   * const { count } = await prisma.tb_ms_user_type.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends tb_ms_user_typeDeleteManyArgs>(args?: Prisma.SelectSubset<T, tb_ms_user_typeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tb_ms_user_types.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {tb_ms_user_typeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Tb_ms_user_types
   * const tb_ms_user_type = await prisma.tb_ms_user_type.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends tb_ms_user_typeUpdateManyArgs>(args: Prisma.SelectSubset<T, tb_ms_user_typeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tb_ms_user_types and returns the data updated in the database.
   * @param {tb_ms_user_typeUpdateManyAndReturnArgs} args - Arguments to update many Tb_ms_user_types.
   * @example
   * // Update many Tb_ms_user_types
   * const tb_ms_user_type = await prisma.tb_ms_user_type.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Tb_ms_user_types and only return the `user_type_id`
   * const tb_ms_user_typeWithUser_type_idOnly = await prisma.tb_ms_user_type.updateManyAndReturn({
   *   select: { user_type_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends tb_ms_user_typeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, tb_ms_user_typeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$tb_ms_user_typePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Tb_ms_user_type.
   * @param {tb_ms_user_typeUpsertArgs} args - Arguments to update or create a Tb_ms_user_type.
   * @example
   * // Update or create a Tb_ms_user_type
   * const tb_ms_user_type = await prisma.tb_ms_user_type.upsert({
   *   create: {
   *     // ... data to create a Tb_ms_user_type
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Tb_ms_user_type we want to update
   *   }
   * })
   */
  upsert<T extends tb_ms_user_typeUpsertArgs>(args: Prisma.SelectSubset<T, tb_ms_user_typeUpsertArgs<ExtArgs>>): Prisma.Prisma__tb_ms_user_typeClient<runtime.Types.Result.GetResult<Prisma.$tb_ms_user_typePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Tb_ms_user_types.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {tb_ms_user_typeCountArgs} args - Arguments to filter Tb_ms_user_types to count.
   * @example
   * // Count the number of Tb_ms_user_types
   * const count = await prisma.tb_ms_user_type.count({
   *   where: {
   *     // ... the filter for the Tb_ms_user_types we want to count
   *   }
   * })
  **/
  count<T extends tb_ms_user_typeCountArgs>(
    args?: Prisma.Subset<T, tb_ms_user_typeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Tb_ms_user_typeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Tb_ms_user_type.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Tb_ms_user_typeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Tb_ms_user_typeAggregateArgs>(args: Prisma.Subset<T, Tb_ms_user_typeAggregateArgs>): Prisma.PrismaPromise<GetTb_ms_user_typeAggregateType<T>>

  /**
   * Group by Tb_ms_user_type.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {tb_ms_user_typeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends tb_ms_user_typeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: tb_ms_user_typeGroupByArgs['orderBy'] }
      : { orderBy?: tb_ms_user_typeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, tb_ms_user_typeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTb_ms_user_typeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the tb_ms_user_type model
 */
readonly fields: tb_ms_user_typeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for tb_ms_user_type.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__tb_ms_user_typeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tb_user<T extends Prisma.tb_ms_user_type$tb_userArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.tb_ms_user_type$tb_userArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$tb_userPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the tb_ms_user_type model
 */
export interface tb_ms_user_typeFieldRefs {
  readonly user_type_id: Prisma.FieldRef<"tb_ms_user_type", 'BigInt'>
  readonly user_type_code: Prisma.FieldRef<"tb_ms_user_type", 'String'>
  readonly user_type_name: Prisma.FieldRef<"tb_ms_user_type", 'String'>
  readonly description: Prisma.FieldRef<"tb_ms_user_type", 'String'>
  readonly default_role_code: Prisma.FieldRef<"tb_ms_user_type", 'String'>
  readonly registration_allowed: Prisma.FieldRef<"tb_ms_user_type", 'Boolean'>
  readonly login_allowed: Prisma.FieldRef<"tb_ms_user_type", 'Boolean'>
  readonly require_identity_verify: Prisma.FieldRef<"tb_ms_user_type", 'Boolean'>
  readonly require_document: Prisma.FieldRef<"tb_ms_user_type", 'Boolean'>
  readonly is_internal_user: Prisma.FieldRef<"tb_ms_user_type", 'Boolean'>
  readonly record_status: Prisma.FieldRef<"tb_ms_user_type", 'String'>
  readonly require_office_verify: Prisma.FieldRef<"tb_ms_user_type", 'Boolean'>
  readonly display_order: Prisma.FieldRef<"tb_ms_user_type", 'Int'>
  readonly created_at: Prisma.FieldRef<"tb_ms_user_type", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"tb_ms_user_type", 'DateTime'>
  readonly update_by: Prisma.FieldRef<"tb_ms_user_type", 'String'>
  readonly created_by: Prisma.FieldRef<"tb_ms_user_type", 'String'>
}
    

// Custom InputTypes
/**
 * tb_ms_user_type findUnique
 */
export type tb_ms_user_typeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_user_type
   */
  select?: Prisma.tb_ms_user_typeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_user_type
   */
  omit?: Prisma.tb_ms_user_typeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_user_typeInclude<ExtArgs> | null
  /**
   * Filter, which tb_ms_user_type to fetch.
   */
  where: Prisma.tb_ms_user_typeWhereUniqueInput
}

/**
 * tb_ms_user_type findUniqueOrThrow
 */
export type tb_ms_user_typeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_user_type
   */
  select?: Prisma.tb_ms_user_typeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_user_type
   */
  omit?: Prisma.tb_ms_user_typeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_user_typeInclude<ExtArgs> | null
  /**
   * Filter, which tb_ms_user_type to fetch.
   */
  where: Prisma.tb_ms_user_typeWhereUniqueInput
}

/**
 * tb_ms_user_type findFirst
 */
export type tb_ms_user_typeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_user_type
   */
  select?: Prisma.tb_ms_user_typeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_user_type
   */
  omit?: Prisma.tb_ms_user_typeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_user_typeInclude<ExtArgs> | null
  /**
   * Filter, which tb_ms_user_type to fetch.
   */
  where?: Prisma.tb_ms_user_typeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of tb_ms_user_types to fetch.
   */
  orderBy?: Prisma.tb_ms_user_typeOrderByWithRelationInput | Prisma.tb_ms_user_typeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for tb_ms_user_types.
   */
  cursor?: Prisma.tb_ms_user_typeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` tb_ms_user_types from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` tb_ms_user_types.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of tb_ms_user_types.
   */
  distinct?: Prisma.Tb_ms_user_typeScalarFieldEnum | Prisma.Tb_ms_user_typeScalarFieldEnum[]
}

/**
 * tb_ms_user_type findFirstOrThrow
 */
export type tb_ms_user_typeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_user_type
   */
  select?: Prisma.tb_ms_user_typeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_user_type
   */
  omit?: Prisma.tb_ms_user_typeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_user_typeInclude<ExtArgs> | null
  /**
   * Filter, which tb_ms_user_type to fetch.
   */
  where?: Prisma.tb_ms_user_typeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of tb_ms_user_types to fetch.
   */
  orderBy?: Prisma.tb_ms_user_typeOrderByWithRelationInput | Prisma.tb_ms_user_typeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for tb_ms_user_types.
   */
  cursor?: Prisma.tb_ms_user_typeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` tb_ms_user_types from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` tb_ms_user_types.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of tb_ms_user_types.
   */
  distinct?: Prisma.Tb_ms_user_typeScalarFieldEnum | Prisma.Tb_ms_user_typeScalarFieldEnum[]
}

/**
 * tb_ms_user_type findMany
 */
export type tb_ms_user_typeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_user_type
   */
  select?: Prisma.tb_ms_user_typeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_user_type
   */
  omit?: Prisma.tb_ms_user_typeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_user_typeInclude<ExtArgs> | null
  /**
   * Filter, which tb_ms_user_types to fetch.
   */
  where?: Prisma.tb_ms_user_typeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of tb_ms_user_types to fetch.
   */
  orderBy?: Prisma.tb_ms_user_typeOrderByWithRelationInput | Prisma.tb_ms_user_typeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing tb_ms_user_types.
   */
  cursor?: Prisma.tb_ms_user_typeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` tb_ms_user_types from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` tb_ms_user_types.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of tb_ms_user_types.
   */
  distinct?: Prisma.Tb_ms_user_typeScalarFieldEnum | Prisma.Tb_ms_user_typeScalarFieldEnum[]
}

/**
 * tb_ms_user_type create
 */
export type tb_ms_user_typeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_user_type
   */
  select?: Prisma.tb_ms_user_typeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_user_type
   */
  omit?: Prisma.tb_ms_user_typeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_user_typeInclude<ExtArgs> | null
  /**
   * The data needed to create a tb_ms_user_type.
   */
  data: Prisma.XOR<Prisma.tb_ms_user_typeCreateInput, Prisma.tb_ms_user_typeUncheckedCreateInput>
}

/**
 * tb_ms_user_type createMany
 */
export type tb_ms_user_typeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many tb_ms_user_types.
   */
  data: Prisma.tb_ms_user_typeCreateManyInput | Prisma.tb_ms_user_typeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * tb_ms_user_type createManyAndReturn
 */
export type tb_ms_user_typeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_user_type
   */
  select?: Prisma.tb_ms_user_typeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_user_type
   */
  omit?: Prisma.tb_ms_user_typeOmit<ExtArgs> | null
  /**
   * The data used to create many tb_ms_user_types.
   */
  data: Prisma.tb_ms_user_typeCreateManyInput | Prisma.tb_ms_user_typeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * tb_ms_user_type update
 */
export type tb_ms_user_typeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_user_type
   */
  select?: Prisma.tb_ms_user_typeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_user_type
   */
  omit?: Prisma.tb_ms_user_typeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_user_typeInclude<ExtArgs> | null
  /**
   * The data needed to update a tb_ms_user_type.
   */
  data: Prisma.XOR<Prisma.tb_ms_user_typeUpdateInput, Prisma.tb_ms_user_typeUncheckedUpdateInput>
  /**
   * Choose, which tb_ms_user_type to update.
   */
  where: Prisma.tb_ms_user_typeWhereUniqueInput
}

/**
 * tb_ms_user_type updateMany
 */
export type tb_ms_user_typeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update tb_ms_user_types.
   */
  data: Prisma.XOR<Prisma.tb_ms_user_typeUpdateManyMutationInput, Prisma.tb_ms_user_typeUncheckedUpdateManyInput>
  /**
   * Filter which tb_ms_user_types to update
   */
  where?: Prisma.tb_ms_user_typeWhereInput
  /**
   * Limit how many tb_ms_user_types to update.
   */
  limit?: number
}

/**
 * tb_ms_user_type updateManyAndReturn
 */
export type tb_ms_user_typeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_user_type
   */
  select?: Prisma.tb_ms_user_typeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_user_type
   */
  omit?: Prisma.tb_ms_user_typeOmit<ExtArgs> | null
  /**
   * The data used to update tb_ms_user_types.
   */
  data: Prisma.XOR<Prisma.tb_ms_user_typeUpdateManyMutationInput, Prisma.tb_ms_user_typeUncheckedUpdateManyInput>
  /**
   * Filter which tb_ms_user_types to update
   */
  where?: Prisma.tb_ms_user_typeWhereInput
  /**
   * Limit how many tb_ms_user_types to update.
   */
  limit?: number
}

/**
 * tb_ms_user_type upsert
 */
export type tb_ms_user_typeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_user_type
   */
  select?: Prisma.tb_ms_user_typeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_user_type
   */
  omit?: Prisma.tb_ms_user_typeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_user_typeInclude<ExtArgs> | null
  /**
   * The filter to search for the tb_ms_user_type to update in case it exists.
   */
  where: Prisma.tb_ms_user_typeWhereUniqueInput
  /**
   * In case the tb_ms_user_type found by the `where` argument doesn't exist, create a new tb_ms_user_type with this data.
   */
  create: Prisma.XOR<Prisma.tb_ms_user_typeCreateInput, Prisma.tb_ms_user_typeUncheckedCreateInput>
  /**
   * In case the tb_ms_user_type was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.tb_ms_user_typeUpdateInput, Prisma.tb_ms_user_typeUncheckedUpdateInput>
}

/**
 * tb_ms_user_type delete
 */
export type tb_ms_user_typeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_user_type
   */
  select?: Prisma.tb_ms_user_typeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_user_type
   */
  omit?: Prisma.tb_ms_user_typeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_user_typeInclude<ExtArgs> | null
  /**
   * Filter which tb_ms_user_type to delete.
   */
  where: Prisma.tb_ms_user_typeWhereUniqueInput
}

/**
 * tb_ms_user_type deleteMany
 */
export type tb_ms_user_typeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which tb_ms_user_types to delete
   */
  where?: Prisma.tb_ms_user_typeWhereInput
  /**
   * Limit how many tb_ms_user_types to delete.
   */
  limit?: number
}

/**
 * tb_ms_user_type.tb_user
 */
export type tb_ms_user_type$tb_userArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_user
   */
  select?: Prisma.tb_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_user
   */
  omit?: Prisma.tb_userOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_userInclude<ExtArgs> | null
  where?: Prisma.tb_userWhereInput
  orderBy?: Prisma.tb_userOrderByWithRelationInput | Prisma.tb_userOrderByWithRelationInput[]
  cursor?: Prisma.tb_userWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Tb_userScalarFieldEnum | Prisma.Tb_userScalarFieldEnum[]
}

/**
 * tb_ms_user_type without action
 */
export type tb_ms_user_typeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_user_type
   */
  select?: Prisma.tb_ms_user_typeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_user_type
   */
  omit?: Prisma.tb_ms_user_typeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_user_typeInclude<ExtArgs> | null
}
