
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `tb_ms_province` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model tb_ms_province
 * This model or at least one of its fields has comments in the database, and requires an additional setup for migrations: Read more: https://pris.ly/d/database-comments
 */
export type tb_ms_provinceModel = runtime.Types.Result.DefaultSelection<Prisma.$tb_ms_provincePayload>

export type AggregateTb_ms_province = {
  _count: Tb_ms_provinceCountAggregateOutputType | null
  _min: Tb_ms_provinceMinAggregateOutputType | null
  _max: Tb_ms_provinceMaxAggregateOutputType | null
}

export type Tb_ms_provinceMinAggregateOutputType = {
  province_id: string | null
  province_name: string | null
  created_at: Date | null
  updated_at: Date | null
  update_by: string | null
  created_by: string | null
  record_status: string | null
}

export type Tb_ms_provinceMaxAggregateOutputType = {
  province_id: string | null
  province_name: string | null
  created_at: Date | null
  updated_at: Date | null
  update_by: string | null
  created_by: string | null
  record_status: string | null
}

export type Tb_ms_provinceCountAggregateOutputType = {
  province_id: number
  province_name: number
  created_at: number
  updated_at: number
  update_by: number
  created_by: number
  record_status: number
  _all: number
}


export type Tb_ms_provinceMinAggregateInputType = {
  province_id?: true
  province_name?: true
  created_at?: true
  updated_at?: true
  update_by?: true
  created_by?: true
  record_status?: true
}

export type Tb_ms_provinceMaxAggregateInputType = {
  province_id?: true
  province_name?: true
  created_at?: true
  updated_at?: true
  update_by?: true
  created_by?: true
  record_status?: true
}

export type Tb_ms_provinceCountAggregateInputType = {
  province_id?: true
  province_name?: true
  created_at?: true
  updated_at?: true
  update_by?: true
  created_by?: true
  record_status?: true
  _all?: true
}

export type Tb_ms_provinceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which tb_ms_province to aggregate.
   */
  where?: Prisma.tb_ms_provinceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of tb_ms_provinces to fetch.
   */
  orderBy?: Prisma.tb_ms_provinceOrderByWithRelationInput | Prisma.tb_ms_provinceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.tb_ms_provinceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` tb_ms_provinces from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` tb_ms_provinces.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned tb_ms_provinces
  **/
  _count?: true | Tb_ms_provinceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Tb_ms_provinceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Tb_ms_provinceMaxAggregateInputType
}

export type GetTb_ms_provinceAggregateType<T extends Tb_ms_provinceAggregateArgs> = {
      [P in keyof T & keyof AggregateTb_ms_province]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTb_ms_province[P]>
    : Prisma.GetScalarType<T[P], AggregateTb_ms_province[P]>
}




export type tb_ms_provinceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.tb_ms_provinceWhereInput
  orderBy?: Prisma.tb_ms_provinceOrderByWithAggregationInput | Prisma.tb_ms_provinceOrderByWithAggregationInput[]
  by: Prisma.Tb_ms_provinceScalarFieldEnum[] | Prisma.Tb_ms_provinceScalarFieldEnum
  having?: Prisma.tb_ms_provinceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Tb_ms_provinceCountAggregateInputType | true
  _min?: Tb_ms_provinceMinAggregateInputType
  _max?: Tb_ms_provinceMaxAggregateInputType
}

export type Tb_ms_provinceGroupByOutputType = {
  province_id: string
  province_name: string
  created_at: Date
  updated_at: Date | null
  update_by: string | null
  created_by: string | null
  record_status: string | null
  _count: Tb_ms_provinceCountAggregateOutputType | null
  _min: Tb_ms_provinceMinAggregateOutputType | null
  _max: Tb_ms_provinceMaxAggregateOutputType | null
}

export type GetTb_ms_provinceGroupByPayload<T extends tb_ms_provinceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Tb_ms_provinceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Tb_ms_provinceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Tb_ms_provinceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Tb_ms_provinceGroupByOutputType[P]>
      }
    >
  >



export type tb_ms_provinceWhereInput = {
  AND?: Prisma.tb_ms_provinceWhereInput | Prisma.tb_ms_provinceWhereInput[]
  OR?: Prisma.tb_ms_provinceWhereInput[]
  NOT?: Prisma.tb_ms_provinceWhereInput | Prisma.tb_ms_provinceWhereInput[]
  province_id?: Prisma.StringFilter<"tb_ms_province"> | string
  province_name?: Prisma.StringFilter<"tb_ms_province"> | string
  created_at?: Prisma.DateTimeFilter<"tb_ms_province"> | Date | string
  updated_at?: Prisma.DateTimeNullableFilter<"tb_ms_province"> | Date | string | null
  update_by?: Prisma.UuidNullableFilter<"tb_ms_province"> | string | null
  created_by?: Prisma.UuidNullableFilter<"tb_ms_province"> | string | null
  record_status?: Prisma.StringNullableFilter<"tb_ms_province"> | string | null
  tb_ms_amphur?: Prisma.Tb_ms_amphurListRelationFilter
}

export type tb_ms_provinceOrderByWithRelationInput = {
  province_id?: Prisma.SortOrder
  province_name?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  update_by?: Prisma.SortOrderInput | Prisma.SortOrder
  created_by?: Prisma.SortOrderInput | Prisma.SortOrder
  record_status?: Prisma.SortOrderInput | Prisma.SortOrder
  tb_ms_amphur?: Prisma.tb_ms_amphurOrderByRelationAggregateInput
}

export type tb_ms_provinceWhereUniqueInput = Prisma.AtLeast<{
  province_id?: string
  AND?: Prisma.tb_ms_provinceWhereInput | Prisma.tb_ms_provinceWhereInput[]
  OR?: Prisma.tb_ms_provinceWhereInput[]
  NOT?: Prisma.tb_ms_provinceWhereInput | Prisma.tb_ms_provinceWhereInput[]
  province_name?: Prisma.StringFilter<"tb_ms_province"> | string
  created_at?: Prisma.DateTimeFilter<"tb_ms_province"> | Date | string
  updated_at?: Prisma.DateTimeNullableFilter<"tb_ms_province"> | Date | string | null
  update_by?: Prisma.UuidNullableFilter<"tb_ms_province"> | string | null
  created_by?: Prisma.UuidNullableFilter<"tb_ms_province"> | string | null
  record_status?: Prisma.StringNullableFilter<"tb_ms_province"> | string | null
  tb_ms_amphur?: Prisma.Tb_ms_amphurListRelationFilter
}, "province_id">

export type tb_ms_provinceOrderByWithAggregationInput = {
  province_id?: Prisma.SortOrder
  province_name?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  update_by?: Prisma.SortOrderInput | Prisma.SortOrder
  created_by?: Prisma.SortOrderInput | Prisma.SortOrder
  record_status?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.tb_ms_provinceCountOrderByAggregateInput
  _max?: Prisma.tb_ms_provinceMaxOrderByAggregateInput
  _min?: Prisma.tb_ms_provinceMinOrderByAggregateInput
}

export type tb_ms_provinceScalarWhereWithAggregatesInput = {
  AND?: Prisma.tb_ms_provinceScalarWhereWithAggregatesInput | Prisma.tb_ms_provinceScalarWhereWithAggregatesInput[]
  OR?: Prisma.tb_ms_provinceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.tb_ms_provinceScalarWhereWithAggregatesInput | Prisma.tb_ms_provinceScalarWhereWithAggregatesInput[]
  province_id?: Prisma.StringWithAggregatesFilter<"tb_ms_province"> | string
  province_name?: Prisma.StringWithAggregatesFilter<"tb_ms_province"> | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"tb_ms_province"> | Date | string
  updated_at?: Prisma.DateTimeNullableWithAggregatesFilter<"tb_ms_province"> | Date | string | null
  update_by?: Prisma.UuidNullableWithAggregatesFilter<"tb_ms_province"> | string | null
  created_by?: Prisma.UuidNullableWithAggregatesFilter<"tb_ms_province"> | string | null
  record_status?: Prisma.StringNullableWithAggregatesFilter<"tb_ms_province"> | string | null
}

export type tb_ms_provinceCreateInput = {
  province_id: string
  province_name: string
  created_at?: Date | string
  updated_at?: Date | string | null
  update_by?: string | null
  created_by?: string | null
  record_status?: string | null
  tb_ms_amphur?: Prisma.tb_ms_amphurCreateNestedManyWithoutTb_ms_provinceInput
}

export type tb_ms_provinceUncheckedCreateInput = {
  province_id: string
  province_name: string
  created_at?: Date | string
  updated_at?: Date | string | null
  update_by?: string | null
  created_by?: string | null
  record_status?: string | null
  tb_ms_amphur?: Prisma.tb_ms_amphurUncheckedCreateNestedManyWithoutTb_ms_provinceInput
}

export type tb_ms_provinceUpdateInput = {
  province_id?: Prisma.StringFieldUpdateOperationsInput | string
  province_name?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tb_ms_amphur?: Prisma.tb_ms_amphurUpdateManyWithoutTb_ms_provinceNestedInput
}

export type tb_ms_provinceUncheckedUpdateInput = {
  province_id?: Prisma.StringFieldUpdateOperationsInput | string
  province_name?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tb_ms_amphur?: Prisma.tb_ms_amphurUncheckedUpdateManyWithoutTb_ms_provinceNestedInput
}

export type tb_ms_provinceCreateManyInput = {
  province_id: string
  province_name: string
  created_at?: Date | string
  updated_at?: Date | string | null
  update_by?: string | null
  created_by?: string | null
  record_status?: string | null
}

export type tb_ms_provinceUpdateManyMutationInput = {
  province_id?: Prisma.StringFieldUpdateOperationsInput | string
  province_name?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type tb_ms_provinceUncheckedUpdateManyInput = {
  province_id?: Prisma.StringFieldUpdateOperationsInput | string
  province_name?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type Tb_ms_provinceScalarRelationFilter = {
  is?: Prisma.tb_ms_provinceWhereInput
  isNot?: Prisma.tb_ms_provinceWhereInput
}

export type tb_ms_provinceCountOrderByAggregateInput = {
  province_id?: Prisma.SortOrder
  province_name?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  update_by?: Prisma.SortOrder
  created_by?: Prisma.SortOrder
  record_status?: Prisma.SortOrder
}

export type tb_ms_provinceMaxOrderByAggregateInput = {
  province_id?: Prisma.SortOrder
  province_name?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  update_by?: Prisma.SortOrder
  created_by?: Prisma.SortOrder
  record_status?: Prisma.SortOrder
}

export type tb_ms_provinceMinOrderByAggregateInput = {
  province_id?: Prisma.SortOrder
  province_name?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  update_by?: Prisma.SortOrder
  created_by?: Prisma.SortOrder
  record_status?: Prisma.SortOrder
}

export type tb_ms_provinceCreateNestedOneWithoutTb_ms_amphurInput = {
  create?: Prisma.XOR<Prisma.tb_ms_provinceCreateWithoutTb_ms_amphurInput, Prisma.tb_ms_provinceUncheckedCreateWithoutTb_ms_amphurInput>
  connectOrCreate?: Prisma.tb_ms_provinceCreateOrConnectWithoutTb_ms_amphurInput
  connect?: Prisma.tb_ms_provinceWhereUniqueInput
}

export type tb_ms_provinceUpdateOneRequiredWithoutTb_ms_amphurNestedInput = {
  create?: Prisma.XOR<Prisma.tb_ms_provinceCreateWithoutTb_ms_amphurInput, Prisma.tb_ms_provinceUncheckedCreateWithoutTb_ms_amphurInput>
  connectOrCreate?: Prisma.tb_ms_provinceCreateOrConnectWithoutTb_ms_amphurInput
  upsert?: Prisma.tb_ms_provinceUpsertWithoutTb_ms_amphurInput
  connect?: Prisma.tb_ms_provinceWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.tb_ms_provinceUpdateToOneWithWhereWithoutTb_ms_amphurInput, Prisma.tb_ms_provinceUpdateWithoutTb_ms_amphurInput>, Prisma.tb_ms_provinceUncheckedUpdateWithoutTb_ms_amphurInput>
}

export type tb_ms_provinceCreateWithoutTb_ms_amphurInput = {
  province_id: string
  province_name: string
  created_at?: Date | string
  updated_at?: Date | string | null
  update_by?: string | null
  created_by?: string | null
  record_status?: string | null
}

export type tb_ms_provinceUncheckedCreateWithoutTb_ms_amphurInput = {
  province_id: string
  province_name: string
  created_at?: Date | string
  updated_at?: Date | string | null
  update_by?: string | null
  created_by?: string | null
  record_status?: string | null
}

export type tb_ms_provinceCreateOrConnectWithoutTb_ms_amphurInput = {
  where: Prisma.tb_ms_provinceWhereUniqueInput
  create: Prisma.XOR<Prisma.tb_ms_provinceCreateWithoutTb_ms_amphurInput, Prisma.tb_ms_provinceUncheckedCreateWithoutTb_ms_amphurInput>
}

export type tb_ms_provinceUpsertWithoutTb_ms_amphurInput = {
  update: Prisma.XOR<Prisma.tb_ms_provinceUpdateWithoutTb_ms_amphurInput, Prisma.tb_ms_provinceUncheckedUpdateWithoutTb_ms_amphurInput>
  create: Prisma.XOR<Prisma.tb_ms_provinceCreateWithoutTb_ms_amphurInput, Prisma.tb_ms_provinceUncheckedCreateWithoutTb_ms_amphurInput>
  where?: Prisma.tb_ms_provinceWhereInput
}

export type tb_ms_provinceUpdateToOneWithWhereWithoutTb_ms_amphurInput = {
  where?: Prisma.tb_ms_provinceWhereInput
  data: Prisma.XOR<Prisma.tb_ms_provinceUpdateWithoutTb_ms_amphurInput, Prisma.tb_ms_provinceUncheckedUpdateWithoutTb_ms_amphurInput>
}

export type tb_ms_provinceUpdateWithoutTb_ms_amphurInput = {
  province_id?: Prisma.StringFieldUpdateOperationsInput | string
  province_name?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type tb_ms_provinceUncheckedUpdateWithoutTb_ms_amphurInput = {
  province_id?: Prisma.StringFieldUpdateOperationsInput | string
  province_name?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type Tb_ms_provinceCountOutputType
 */

export type Tb_ms_provinceCountOutputType = {
  tb_ms_amphur: number
}

export type Tb_ms_provinceCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tb_ms_amphur?: boolean | Tb_ms_provinceCountOutputTypeCountTb_ms_amphurArgs
}

/**
 * Tb_ms_provinceCountOutputType without action
 */
export type Tb_ms_provinceCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tb_ms_provinceCountOutputType
   */
  select?: Prisma.Tb_ms_provinceCountOutputTypeSelect<ExtArgs> | null
}

/**
 * Tb_ms_provinceCountOutputType without action
 */
export type Tb_ms_provinceCountOutputTypeCountTb_ms_amphurArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.tb_ms_amphurWhereInput
}


export type tb_ms_provinceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  province_id?: boolean
  province_name?: boolean
  created_at?: boolean
  updated_at?: boolean
  update_by?: boolean
  created_by?: boolean
  record_status?: boolean
  tb_ms_amphur?: boolean | Prisma.tb_ms_province$tb_ms_amphurArgs<ExtArgs>
  _count?: boolean | Prisma.Tb_ms_provinceCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tb_ms_province"]>

export type tb_ms_provinceSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  province_id?: boolean
  province_name?: boolean
  created_at?: boolean
  updated_at?: boolean
  update_by?: boolean
  created_by?: boolean
  record_status?: boolean
}, ExtArgs["result"]["tb_ms_province"]>

export type tb_ms_provinceSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  province_id?: boolean
  province_name?: boolean
  created_at?: boolean
  updated_at?: boolean
  update_by?: boolean
  created_by?: boolean
  record_status?: boolean
}, ExtArgs["result"]["tb_ms_province"]>

export type tb_ms_provinceSelectScalar = {
  province_id?: boolean
  province_name?: boolean
  created_at?: boolean
  updated_at?: boolean
  update_by?: boolean
  created_by?: boolean
  record_status?: boolean
}

export type tb_ms_provinceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"province_id" | "province_name" | "created_at" | "updated_at" | "update_by" | "created_by" | "record_status", ExtArgs["result"]["tb_ms_province"]>
export type tb_ms_provinceInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tb_ms_amphur?: boolean | Prisma.tb_ms_province$tb_ms_amphurArgs<ExtArgs>
  _count?: boolean | Prisma.Tb_ms_provinceCountOutputTypeDefaultArgs<ExtArgs>
}
export type tb_ms_provinceIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type tb_ms_provinceIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $tb_ms_provincePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "tb_ms_province"
  objects: {
    tb_ms_amphur: Prisma.$tb_ms_amphurPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    province_id: string
    province_name: string
    created_at: Date
    updated_at: Date | null
    update_by: string | null
    created_by: string | null
    record_status: string | null
  }, ExtArgs["result"]["tb_ms_province"]>
  composites: {}
}

export type tb_ms_provinceGetPayload<S extends boolean | null | undefined | tb_ms_provinceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$tb_ms_provincePayload, S>

export type tb_ms_provinceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<tb_ms_provinceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Tb_ms_provinceCountAggregateInputType | true
  }

export interface tb_ms_provinceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['tb_ms_province'], meta: { name: 'tb_ms_province' } }
  /**
   * Find zero or one Tb_ms_province that matches the filter.
   * @param {tb_ms_provinceFindUniqueArgs} args - Arguments to find a Tb_ms_province
   * @example
   * // Get one Tb_ms_province
   * const tb_ms_province = await prisma.tb_ms_province.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends tb_ms_provinceFindUniqueArgs>(args: Prisma.SelectSubset<T, tb_ms_provinceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__tb_ms_provinceClient<runtime.Types.Result.GetResult<Prisma.$tb_ms_provincePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Tb_ms_province that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {tb_ms_provinceFindUniqueOrThrowArgs} args - Arguments to find a Tb_ms_province
   * @example
   * // Get one Tb_ms_province
   * const tb_ms_province = await prisma.tb_ms_province.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends tb_ms_provinceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, tb_ms_provinceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__tb_ms_provinceClient<runtime.Types.Result.GetResult<Prisma.$tb_ms_provincePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tb_ms_province that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {tb_ms_provinceFindFirstArgs} args - Arguments to find a Tb_ms_province
   * @example
   * // Get one Tb_ms_province
   * const tb_ms_province = await prisma.tb_ms_province.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends tb_ms_provinceFindFirstArgs>(args?: Prisma.SelectSubset<T, tb_ms_provinceFindFirstArgs<ExtArgs>>): Prisma.Prisma__tb_ms_provinceClient<runtime.Types.Result.GetResult<Prisma.$tb_ms_provincePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tb_ms_province that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {tb_ms_provinceFindFirstOrThrowArgs} args - Arguments to find a Tb_ms_province
   * @example
   * // Get one Tb_ms_province
   * const tb_ms_province = await prisma.tb_ms_province.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends tb_ms_provinceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, tb_ms_provinceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__tb_ms_provinceClient<runtime.Types.Result.GetResult<Prisma.$tb_ms_provincePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Tb_ms_provinces that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {tb_ms_provinceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Tb_ms_provinces
   * const tb_ms_provinces = await prisma.tb_ms_province.findMany()
   * 
   * // Get first 10 Tb_ms_provinces
   * const tb_ms_provinces = await prisma.tb_ms_province.findMany({ take: 10 })
   * 
   * // Only select the `province_id`
   * const tb_ms_provinceWithProvince_idOnly = await prisma.tb_ms_province.findMany({ select: { province_id: true } })
   * 
   */
  findMany<T extends tb_ms_provinceFindManyArgs>(args?: Prisma.SelectSubset<T, tb_ms_provinceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$tb_ms_provincePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Tb_ms_province.
   * @param {tb_ms_provinceCreateArgs} args - Arguments to create a Tb_ms_province.
   * @example
   * // Create one Tb_ms_province
   * const Tb_ms_province = await prisma.tb_ms_province.create({
   *   data: {
   *     // ... data to create a Tb_ms_province
   *   }
   * })
   * 
   */
  create<T extends tb_ms_provinceCreateArgs>(args: Prisma.SelectSubset<T, tb_ms_provinceCreateArgs<ExtArgs>>): Prisma.Prisma__tb_ms_provinceClient<runtime.Types.Result.GetResult<Prisma.$tb_ms_provincePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Tb_ms_provinces.
   * @param {tb_ms_provinceCreateManyArgs} args - Arguments to create many Tb_ms_provinces.
   * @example
   * // Create many Tb_ms_provinces
   * const tb_ms_province = await prisma.tb_ms_province.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends tb_ms_provinceCreateManyArgs>(args?: Prisma.SelectSubset<T, tb_ms_provinceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Tb_ms_provinces and returns the data saved in the database.
   * @param {tb_ms_provinceCreateManyAndReturnArgs} args - Arguments to create many Tb_ms_provinces.
   * @example
   * // Create many Tb_ms_provinces
   * const tb_ms_province = await prisma.tb_ms_province.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Tb_ms_provinces and only return the `province_id`
   * const tb_ms_provinceWithProvince_idOnly = await prisma.tb_ms_province.createManyAndReturn({
   *   select: { province_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends tb_ms_provinceCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, tb_ms_provinceCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$tb_ms_provincePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Tb_ms_province.
   * @param {tb_ms_provinceDeleteArgs} args - Arguments to delete one Tb_ms_province.
   * @example
   * // Delete one Tb_ms_province
   * const Tb_ms_province = await prisma.tb_ms_province.delete({
   *   where: {
   *     // ... filter to delete one Tb_ms_province
   *   }
   * })
   * 
   */
  delete<T extends tb_ms_provinceDeleteArgs>(args: Prisma.SelectSubset<T, tb_ms_provinceDeleteArgs<ExtArgs>>): Prisma.Prisma__tb_ms_provinceClient<runtime.Types.Result.GetResult<Prisma.$tb_ms_provincePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Tb_ms_province.
   * @param {tb_ms_provinceUpdateArgs} args - Arguments to update one Tb_ms_province.
   * @example
   * // Update one Tb_ms_province
   * const tb_ms_province = await prisma.tb_ms_province.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends tb_ms_provinceUpdateArgs>(args: Prisma.SelectSubset<T, tb_ms_provinceUpdateArgs<ExtArgs>>): Prisma.Prisma__tb_ms_provinceClient<runtime.Types.Result.GetResult<Prisma.$tb_ms_provincePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Tb_ms_provinces.
   * @param {tb_ms_provinceDeleteManyArgs} args - Arguments to filter Tb_ms_provinces to delete.
   * @example
   * // Delete a few Tb_ms_provinces
   * const { count } = await prisma.tb_ms_province.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends tb_ms_provinceDeleteManyArgs>(args?: Prisma.SelectSubset<T, tb_ms_provinceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tb_ms_provinces.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {tb_ms_provinceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Tb_ms_provinces
   * const tb_ms_province = await prisma.tb_ms_province.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends tb_ms_provinceUpdateManyArgs>(args: Prisma.SelectSubset<T, tb_ms_provinceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tb_ms_provinces and returns the data updated in the database.
   * @param {tb_ms_provinceUpdateManyAndReturnArgs} args - Arguments to update many Tb_ms_provinces.
   * @example
   * // Update many Tb_ms_provinces
   * const tb_ms_province = await prisma.tb_ms_province.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Tb_ms_provinces and only return the `province_id`
   * const tb_ms_provinceWithProvince_idOnly = await prisma.tb_ms_province.updateManyAndReturn({
   *   select: { province_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends tb_ms_provinceUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, tb_ms_provinceUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$tb_ms_provincePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Tb_ms_province.
   * @param {tb_ms_provinceUpsertArgs} args - Arguments to update or create a Tb_ms_province.
   * @example
   * // Update or create a Tb_ms_province
   * const tb_ms_province = await prisma.tb_ms_province.upsert({
   *   create: {
   *     // ... data to create a Tb_ms_province
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Tb_ms_province we want to update
   *   }
   * })
   */
  upsert<T extends tb_ms_provinceUpsertArgs>(args: Prisma.SelectSubset<T, tb_ms_provinceUpsertArgs<ExtArgs>>): Prisma.Prisma__tb_ms_provinceClient<runtime.Types.Result.GetResult<Prisma.$tb_ms_provincePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Tb_ms_provinces.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {tb_ms_provinceCountArgs} args - Arguments to filter Tb_ms_provinces to count.
   * @example
   * // Count the number of Tb_ms_provinces
   * const count = await prisma.tb_ms_province.count({
   *   where: {
   *     // ... the filter for the Tb_ms_provinces we want to count
   *   }
   * })
  **/
  count<T extends tb_ms_provinceCountArgs>(
    args?: Prisma.Subset<T, tb_ms_provinceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Tb_ms_provinceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Tb_ms_province.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Tb_ms_provinceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Tb_ms_provinceAggregateArgs>(args: Prisma.Subset<T, Tb_ms_provinceAggregateArgs>): Prisma.PrismaPromise<GetTb_ms_provinceAggregateType<T>>

  /**
   * Group by Tb_ms_province.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {tb_ms_provinceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends tb_ms_provinceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: tb_ms_provinceGroupByArgs['orderBy'] }
      : { orderBy?: tb_ms_provinceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, tb_ms_provinceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTb_ms_provinceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the tb_ms_province model
 */
readonly fields: tb_ms_provinceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for tb_ms_province.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__tb_ms_provinceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tb_ms_amphur<T extends Prisma.tb_ms_province$tb_ms_amphurArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.tb_ms_province$tb_ms_amphurArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$tb_ms_amphurPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the tb_ms_province model
 */
export interface tb_ms_provinceFieldRefs {
  readonly province_id: Prisma.FieldRef<"tb_ms_province", 'String'>
  readonly province_name: Prisma.FieldRef<"tb_ms_province", 'String'>
  readonly created_at: Prisma.FieldRef<"tb_ms_province", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"tb_ms_province", 'DateTime'>
  readonly update_by: Prisma.FieldRef<"tb_ms_province", 'String'>
  readonly created_by: Prisma.FieldRef<"tb_ms_province", 'String'>
  readonly record_status: Prisma.FieldRef<"tb_ms_province", 'String'>
}
    

// Custom InputTypes
/**
 * tb_ms_province findUnique
 */
export type tb_ms_provinceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_province
   */
  select?: Prisma.tb_ms_provinceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_province
   */
  omit?: Prisma.tb_ms_provinceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_provinceInclude<ExtArgs> | null
  /**
   * Filter, which tb_ms_province to fetch.
   */
  where: Prisma.tb_ms_provinceWhereUniqueInput
}

/**
 * tb_ms_province findUniqueOrThrow
 */
export type tb_ms_provinceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_province
   */
  select?: Prisma.tb_ms_provinceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_province
   */
  omit?: Prisma.tb_ms_provinceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_provinceInclude<ExtArgs> | null
  /**
   * Filter, which tb_ms_province to fetch.
   */
  where: Prisma.tb_ms_provinceWhereUniqueInput
}

/**
 * tb_ms_province findFirst
 */
export type tb_ms_provinceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_province
   */
  select?: Prisma.tb_ms_provinceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_province
   */
  omit?: Prisma.tb_ms_provinceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_provinceInclude<ExtArgs> | null
  /**
   * Filter, which tb_ms_province to fetch.
   */
  where?: Prisma.tb_ms_provinceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of tb_ms_provinces to fetch.
   */
  orderBy?: Prisma.tb_ms_provinceOrderByWithRelationInput | Prisma.tb_ms_provinceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for tb_ms_provinces.
   */
  cursor?: Prisma.tb_ms_provinceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` tb_ms_provinces from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` tb_ms_provinces.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of tb_ms_provinces.
   */
  distinct?: Prisma.Tb_ms_provinceScalarFieldEnum | Prisma.Tb_ms_provinceScalarFieldEnum[]
}

/**
 * tb_ms_province findFirstOrThrow
 */
export type tb_ms_provinceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_province
   */
  select?: Prisma.tb_ms_provinceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_province
   */
  omit?: Prisma.tb_ms_provinceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_provinceInclude<ExtArgs> | null
  /**
   * Filter, which tb_ms_province to fetch.
   */
  where?: Prisma.tb_ms_provinceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of tb_ms_provinces to fetch.
   */
  orderBy?: Prisma.tb_ms_provinceOrderByWithRelationInput | Prisma.tb_ms_provinceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for tb_ms_provinces.
   */
  cursor?: Prisma.tb_ms_provinceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` tb_ms_provinces from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` tb_ms_provinces.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of tb_ms_provinces.
   */
  distinct?: Prisma.Tb_ms_provinceScalarFieldEnum | Prisma.Tb_ms_provinceScalarFieldEnum[]
}

/**
 * tb_ms_province findMany
 */
export type tb_ms_provinceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_province
   */
  select?: Prisma.tb_ms_provinceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_province
   */
  omit?: Prisma.tb_ms_provinceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_provinceInclude<ExtArgs> | null
  /**
   * Filter, which tb_ms_provinces to fetch.
   */
  where?: Prisma.tb_ms_provinceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of tb_ms_provinces to fetch.
   */
  orderBy?: Prisma.tb_ms_provinceOrderByWithRelationInput | Prisma.tb_ms_provinceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing tb_ms_provinces.
   */
  cursor?: Prisma.tb_ms_provinceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` tb_ms_provinces from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` tb_ms_provinces.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of tb_ms_provinces.
   */
  distinct?: Prisma.Tb_ms_provinceScalarFieldEnum | Prisma.Tb_ms_provinceScalarFieldEnum[]
}

/**
 * tb_ms_province create
 */
export type tb_ms_provinceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_province
   */
  select?: Prisma.tb_ms_provinceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_province
   */
  omit?: Prisma.tb_ms_provinceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_provinceInclude<ExtArgs> | null
  /**
   * The data needed to create a tb_ms_province.
   */
  data: Prisma.XOR<Prisma.tb_ms_provinceCreateInput, Prisma.tb_ms_provinceUncheckedCreateInput>
}

/**
 * tb_ms_province createMany
 */
export type tb_ms_provinceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many tb_ms_provinces.
   */
  data: Prisma.tb_ms_provinceCreateManyInput | Prisma.tb_ms_provinceCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * tb_ms_province createManyAndReturn
 */
export type tb_ms_provinceCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_province
   */
  select?: Prisma.tb_ms_provinceSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_province
   */
  omit?: Prisma.tb_ms_provinceOmit<ExtArgs> | null
  /**
   * The data used to create many tb_ms_provinces.
   */
  data: Prisma.tb_ms_provinceCreateManyInput | Prisma.tb_ms_provinceCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * tb_ms_province update
 */
export type tb_ms_provinceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_province
   */
  select?: Prisma.tb_ms_provinceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_province
   */
  omit?: Prisma.tb_ms_provinceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_provinceInclude<ExtArgs> | null
  /**
   * The data needed to update a tb_ms_province.
   */
  data: Prisma.XOR<Prisma.tb_ms_provinceUpdateInput, Prisma.tb_ms_provinceUncheckedUpdateInput>
  /**
   * Choose, which tb_ms_province to update.
   */
  where: Prisma.tb_ms_provinceWhereUniqueInput
}

/**
 * tb_ms_province updateMany
 */
export type tb_ms_provinceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update tb_ms_provinces.
   */
  data: Prisma.XOR<Prisma.tb_ms_provinceUpdateManyMutationInput, Prisma.tb_ms_provinceUncheckedUpdateManyInput>
  /**
   * Filter which tb_ms_provinces to update
   */
  where?: Prisma.tb_ms_provinceWhereInput
  /**
   * Limit how many tb_ms_provinces to update.
   */
  limit?: number
}

/**
 * tb_ms_province updateManyAndReturn
 */
export type tb_ms_provinceUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_province
   */
  select?: Prisma.tb_ms_provinceSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_province
   */
  omit?: Prisma.tb_ms_provinceOmit<ExtArgs> | null
  /**
   * The data used to update tb_ms_provinces.
   */
  data: Prisma.XOR<Prisma.tb_ms_provinceUpdateManyMutationInput, Prisma.tb_ms_provinceUncheckedUpdateManyInput>
  /**
   * Filter which tb_ms_provinces to update
   */
  where?: Prisma.tb_ms_provinceWhereInput
  /**
   * Limit how many tb_ms_provinces to update.
   */
  limit?: number
}

/**
 * tb_ms_province upsert
 */
export type tb_ms_provinceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_province
   */
  select?: Prisma.tb_ms_provinceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_province
   */
  omit?: Prisma.tb_ms_provinceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_provinceInclude<ExtArgs> | null
  /**
   * The filter to search for the tb_ms_province to update in case it exists.
   */
  where: Prisma.tb_ms_provinceWhereUniqueInput
  /**
   * In case the tb_ms_province found by the `where` argument doesn't exist, create a new tb_ms_province with this data.
   */
  create: Prisma.XOR<Prisma.tb_ms_provinceCreateInput, Prisma.tb_ms_provinceUncheckedCreateInput>
  /**
   * In case the tb_ms_province was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.tb_ms_provinceUpdateInput, Prisma.tb_ms_provinceUncheckedUpdateInput>
}

/**
 * tb_ms_province delete
 */
export type tb_ms_provinceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_province
   */
  select?: Prisma.tb_ms_provinceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_province
   */
  omit?: Prisma.tb_ms_provinceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_provinceInclude<ExtArgs> | null
  /**
   * Filter which tb_ms_province to delete.
   */
  where: Prisma.tb_ms_provinceWhereUniqueInput
}

/**
 * tb_ms_province deleteMany
 */
export type tb_ms_provinceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which tb_ms_provinces to delete
   */
  where?: Prisma.tb_ms_provinceWhereInput
  /**
   * Limit how many tb_ms_provinces to delete.
   */
  limit?: number
}

/**
 * tb_ms_province.tb_ms_amphur
 */
export type tb_ms_province$tb_ms_amphurArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_amphur
   */
  select?: Prisma.tb_ms_amphurSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_amphur
   */
  omit?: Prisma.tb_ms_amphurOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_amphurInclude<ExtArgs> | null
  where?: Prisma.tb_ms_amphurWhereInput
  orderBy?: Prisma.tb_ms_amphurOrderByWithRelationInput | Prisma.tb_ms_amphurOrderByWithRelationInput[]
  cursor?: Prisma.tb_ms_amphurWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Tb_ms_amphurScalarFieldEnum | Prisma.Tb_ms_amphurScalarFieldEnum[]
}

/**
 * tb_ms_province without action
 */
export type tb_ms_provinceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_province
   */
  select?: Prisma.tb_ms_provinceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_province
   */
  omit?: Prisma.tb_ms_provinceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_provinceInclude<ExtArgs> | null
}
