
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `tb_ms_method` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model tb_ms_method
 * This model or at least one of its fields has comments in the database, and requires an additional setup for migrations: Read more: https://pris.ly/d/database-comments
 */
export type tb_ms_methodModel = runtime.Types.Result.DefaultSelection<Prisma.$tb_ms_methodPayload>

export type AggregateTb_ms_method = {
  _count: Tb_ms_methodCountAggregateOutputType | null
  _avg: Tb_ms_methodAvgAggregateOutputType | null
  _sum: Tb_ms_methodSumAggregateOutputType | null
  _min: Tb_ms_methodMinAggregateOutputType | null
  _max: Tb_ms_methodMaxAggregateOutputType | null
}

export type Tb_ms_methodAvgAggregateOutputType = {
  method_id: number | null
  display_order: number | null
}

export type Tb_ms_methodSumAggregateOutputType = {
  method_id: bigint | null
  display_order: number | null
}

export type Tb_ms_methodMinAggregateOutputType = {
  method_id: bigint | null
  method_code: string | null
  method_name: string | null
  description: string | null
  display_order: number | null
  is_enable: boolean | null
  created_at: Date | null
  created_by: string | null
  updated_at: Date | null
  update_by: string | null
  record_status: string | null
}

export type Tb_ms_methodMaxAggregateOutputType = {
  method_id: bigint | null
  method_code: string | null
  method_name: string | null
  description: string | null
  display_order: number | null
  is_enable: boolean | null
  created_at: Date | null
  created_by: string | null
  updated_at: Date | null
  update_by: string | null
  record_status: string | null
}

export type Tb_ms_methodCountAggregateOutputType = {
  method_id: number
  method_code: number
  method_name: number
  description: number
  display_order: number
  is_enable: number
  created_at: number
  created_by: number
  updated_at: number
  update_by: number
  record_status: number
  _all: number
}


export type Tb_ms_methodAvgAggregateInputType = {
  method_id?: true
  display_order?: true
}

export type Tb_ms_methodSumAggregateInputType = {
  method_id?: true
  display_order?: true
}

export type Tb_ms_methodMinAggregateInputType = {
  method_id?: true
  method_code?: true
  method_name?: true
  description?: true
  display_order?: true
  is_enable?: true
  created_at?: true
  created_by?: true
  updated_at?: true
  update_by?: true
  record_status?: true
}

export type Tb_ms_methodMaxAggregateInputType = {
  method_id?: true
  method_code?: true
  method_name?: true
  description?: true
  display_order?: true
  is_enable?: true
  created_at?: true
  created_by?: true
  updated_at?: true
  update_by?: true
  record_status?: true
}

export type Tb_ms_methodCountAggregateInputType = {
  method_id?: true
  method_code?: true
  method_name?: true
  description?: true
  display_order?: true
  is_enable?: true
  created_at?: true
  created_by?: true
  updated_at?: true
  update_by?: true
  record_status?: true
  _all?: true
}

export type Tb_ms_methodAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which tb_ms_method to aggregate.
   */
  where?: Prisma.tb_ms_methodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of tb_ms_methods to fetch.
   */
  orderBy?: Prisma.tb_ms_methodOrderByWithRelationInput | Prisma.tb_ms_methodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.tb_ms_methodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` tb_ms_methods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` tb_ms_methods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned tb_ms_methods
  **/
  _count?: true | Tb_ms_methodCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Tb_ms_methodAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Tb_ms_methodSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Tb_ms_methodMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Tb_ms_methodMaxAggregateInputType
}

export type GetTb_ms_methodAggregateType<T extends Tb_ms_methodAggregateArgs> = {
      [P in keyof T & keyof AggregateTb_ms_method]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTb_ms_method[P]>
    : Prisma.GetScalarType<T[P], AggregateTb_ms_method[P]>
}




export type tb_ms_methodGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.tb_ms_methodWhereInput
  orderBy?: Prisma.tb_ms_methodOrderByWithAggregationInput | Prisma.tb_ms_methodOrderByWithAggregationInput[]
  by: Prisma.Tb_ms_methodScalarFieldEnum[] | Prisma.Tb_ms_methodScalarFieldEnum
  having?: Prisma.tb_ms_methodScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Tb_ms_methodCountAggregateInputType | true
  _avg?: Tb_ms_methodAvgAggregateInputType
  _sum?: Tb_ms_methodSumAggregateInputType
  _min?: Tb_ms_methodMinAggregateInputType
  _max?: Tb_ms_methodMaxAggregateInputType
}

export type Tb_ms_methodGroupByOutputType = {
  method_id: bigint
  method_code: string
  method_name: string
  description: string | null
  display_order: number | null
  is_enable: boolean | null
  created_at: Date
  created_by: string | null
  updated_at: Date | null
  update_by: string | null
  record_status: string | null
  _count: Tb_ms_methodCountAggregateOutputType | null
  _avg: Tb_ms_methodAvgAggregateOutputType | null
  _sum: Tb_ms_methodSumAggregateOutputType | null
  _min: Tb_ms_methodMinAggregateOutputType | null
  _max: Tb_ms_methodMaxAggregateOutputType | null
}

export type GetTb_ms_methodGroupByPayload<T extends tb_ms_methodGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Tb_ms_methodGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Tb_ms_methodGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Tb_ms_methodGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Tb_ms_methodGroupByOutputType[P]>
      }
    >
  >



export type tb_ms_methodWhereInput = {
  AND?: Prisma.tb_ms_methodWhereInput | Prisma.tb_ms_methodWhereInput[]
  OR?: Prisma.tb_ms_methodWhereInput[]
  NOT?: Prisma.tb_ms_methodWhereInput | Prisma.tb_ms_methodWhereInput[]
  method_id?: Prisma.BigIntFilter<"tb_ms_method"> | bigint | number
  method_code?: Prisma.StringFilter<"tb_ms_method"> | string
  method_name?: Prisma.StringFilter<"tb_ms_method"> | string
  description?: Prisma.StringNullableFilter<"tb_ms_method"> | string | null
  display_order?: Prisma.IntNullableFilter<"tb_ms_method"> | number | null
  is_enable?: Prisma.BoolNullableFilter<"tb_ms_method"> | boolean | null
  created_at?: Prisma.DateTimeFilter<"tb_ms_method"> | Date | string
  created_by?: Prisma.UuidNullableFilter<"tb_ms_method"> | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"tb_ms_method"> | Date | string | null
  update_by?: Prisma.UuidNullableFilter<"tb_ms_method"> | string | null
  record_status?: Prisma.StringNullableFilter<"tb_ms_method"> | string | null
  tb_log_access_session?: Prisma.Tb_log_access_sessionListRelationFilter
}

export type tb_ms_methodOrderByWithRelationInput = {
  method_id?: Prisma.SortOrder
  method_code?: Prisma.SortOrder
  method_name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  display_order?: Prisma.SortOrderInput | Prisma.SortOrder
  is_enable?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  created_by?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  update_by?: Prisma.SortOrderInput | Prisma.SortOrder
  record_status?: Prisma.SortOrderInput | Prisma.SortOrder
  tb_log_access_session?: Prisma.tb_log_access_sessionOrderByRelationAggregateInput
}

export type tb_ms_methodWhereUniqueInput = Prisma.AtLeast<{
  method_id?: bigint | number
  AND?: Prisma.tb_ms_methodWhereInput | Prisma.tb_ms_methodWhereInput[]
  OR?: Prisma.tb_ms_methodWhereInput[]
  NOT?: Prisma.tb_ms_methodWhereInput | Prisma.tb_ms_methodWhereInput[]
  method_code?: Prisma.StringFilter<"tb_ms_method"> | string
  method_name?: Prisma.StringFilter<"tb_ms_method"> | string
  description?: Prisma.StringNullableFilter<"tb_ms_method"> | string | null
  display_order?: Prisma.IntNullableFilter<"tb_ms_method"> | number | null
  is_enable?: Prisma.BoolNullableFilter<"tb_ms_method"> | boolean | null
  created_at?: Prisma.DateTimeFilter<"tb_ms_method"> | Date | string
  created_by?: Prisma.UuidNullableFilter<"tb_ms_method"> | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"tb_ms_method"> | Date | string | null
  update_by?: Prisma.UuidNullableFilter<"tb_ms_method"> | string | null
  record_status?: Prisma.StringNullableFilter<"tb_ms_method"> | string | null
  tb_log_access_session?: Prisma.Tb_log_access_sessionListRelationFilter
}, "method_id">

export type tb_ms_methodOrderByWithAggregationInput = {
  method_id?: Prisma.SortOrder
  method_code?: Prisma.SortOrder
  method_name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  display_order?: Prisma.SortOrderInput | Prisma.SortOrder
  is_enable?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  created_by?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  update_by?: Prisma.SortOrderInput | Prisma.SortOrder
  record_status?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.tb_ms_methodCountOrderByAggregateInput
  _avg?: Prisma.tb_ms_methodAvgOrderByAggregateInput
  _max?: Prisma.tb_ms_methodMaxOrderByAggregateInput
  _min?: Prisma.tb_ms_methodMinOrderByAggregateInput
  _sum?: Prisma.tb_ms_methodSumOrderByAggregateInput
}

export type tb_ms_methodScalarWhereWithAggregatesInput = {
  AND?: Prisma.tb_ms_methodScalarWhereWithAggregatesInput | Prisma.tb_ms_methodScalarWhereWithAggregatesInput[]
  OR?: Prisma.tb_ms_methodScalarWhereWithAggregatesInput[]
  NOT?: Prisma.tb_ms_methodScalarWhereWithAggregatesInput | Prisma.tb_ms_methodScalarWhereWithAggregatesInput[]
  method_id?: Prisma.BigIntWithAggregatesFilter<"tb_ms_method"> | bigint | number
  method_code?: Prisma.StringWithAggregatesFilter<"tb_ms_method"> | string
  method_name?: Prisma.StringWithAggregatesFilter<"tb_ms_method"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"tb_ms_method"> | string | null
  display_order?: Prisma.IntNullableWithAggregatesFilter<"tb_ms_method"> | number | null
  is_enable?: Prisma.BoolNullableWithAggregatesFilter<"tb_ms_method"> | boolean | null
  created_at?: Prisma.DateTimeWithAggregatesFilter<"tb_ms_method"> | Date | string
  created_by?: Prisma.UuidNullableWithAggregatesFilter<"tb_ms_method"> | string | null
  updated_at?: Prisma.DateTimeNullableWithAggregatesFilter<"tb_ms_method"> | Date | string | null
  update_by?: Prisma.UuidNullableWithAggregatesFilter<"tb_ms_method"> | string | null
  record_status?: Prisma.StringNullableWithAggregatesFilter<"tb_ms_method"> | string | null
}

export type tb_ms_methodCreateInput = {
  method_id?: bigint | number
  method_code: string
  method_name: string
  description?: string | null
  display_order?: number | null
  is_enable?: boolean | null
  created_at?: Date | string
  created_by?: string | null
  updated_at?: Date | string | null
  update_by?: string | null
  record_status?: string | null
  tb_log_access_session?: Prisma.tb_log_access_sessionCreateNestedManyWithoutTb_ms_methodInput
}

export type tb_ms_methodUncheckedCreateInput = {
  method_id?: bigint | number
  method_code: string
  method_name: string
  description?: string | null
  display_order?: number | null
  is_enable?: boolean | null
  created_at?: Date | string
  created_by?: string | null
  updated_at?: Date | string | null
  update_by?: string | null
  record_status?: string | null
  tb_log_access_session?: Prisma.tb_log_access_sessionUncheckedCreateNestedManyWithoutTb_ms_methodInput
}

export type tb_ms_methodUpdateInput = {
  method_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  method_code?: Prisma.StringFieldUpdateOperationsInput | string
  method_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  display_order?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  is_enable?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tb_log_access_session?: Prisma.tb_log_access_sessionUpdateManyWithoutTb_ms_methodNestedInput
}

export type tb_ms_methodUncheckedUpdateInput = {
  method_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  method_code?: Prisma.StringFieldUpdateOperationsInput | string
  method_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  display_order?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  is_enable?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tb_log_access_session?: Prisma.tb_log_access_sessionUncheckedUpdateManyWithoutTb_ms_methodNestedInput
}

export type tb_ms_methodCreateManyInput = {
  method_id?: bigint | number
  method_code: string
  method_name: string
  description?: string | null
  display_order?: number | null
  is_enable?: boolean | null
  created_at?: Date | string
  created_by?: string | null
  updated_at?: Date | string | null
  update_by?: string | null
  record_status?: string | null
}

export type tb_ms_methodUpdateManyMutationInput = {
  method_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  method_code?: Prisma.StringFieldUpdateOperationsInput | string
  method_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  display_order?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  is_enable?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type tb_ms_methodUncheckedUpdateManyInput = {
  method_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  method_code?: Prisma.StringFieldUpdateOperationsInput | string
  method_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  display_order?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  is_enable?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type Tb_ms_methodNullableScalarRelationFilter = {
  is?: Prisma.tb_ms_methodWhereInput | null
  isNot?: Prisma.tb_ms_methodWhereInput | null
}

export type tb_ms_methodCountOrderByAggregateInput = {
  method_id?: Prisma.SortOrder
  method_code?: Prisma.SortOrder
  method_name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  display_order?: Prisma.SortOrder
  is_enable?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  created_by?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  update_by?: Prisma.SortOrder
  record_status?: Prisma.SortOrder
}

export type tb_ms_methodAvgOrderByAggregateInput = {
  method_id?: Prisma.SortOrder
  display_order?: Prisma.SortOrder
}

export type tb_ms_methodMaxOrderByAggregateInput = {
  method_id?: Prisma.SortOrder
  method_code?: Prisma.SortOrder
  method_name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  display_order?: Prisma.SortOrder
  is_enable?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  created_by?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  update_by?: Prisma.SortOrder
  record_status?: Prisma.SortOrder
}

export type tb_ms_methodMinOrderByAggregateInput = {
  method_id?: Prisma.SortOrder
  method_code?: Prisma.SortOrder
  method_name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  display_order?: Prisma.SortOrder
  is_enable?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  created_by?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  update_by?: Prisma.SortOrder
  record_status?: Prisma.SortOrder
}

export type tb_ms_methodSumOrderByAggregateInput = {
  method_id?: Prisma.SortOrder
  display_order?: Prisma.SortOrder
}

export type tb_ms_methodCreateNestedOneWithoutTb_log_access_sessionInput = {
  create?: Prisma.XOR<Prisma.tb_ms_methodCreateWithoutTb_log_access_sessionInput, Prisma.tb_ms_methodUncheckedCreateWithoutTb_log_access_sessionInput>
  connectOrCreate?: Prisma.tb_ms_methodCreateOrConnectWithoutTb_log_access_sessionInput
  connect?: Prisma.tb_ms_methodWhereUniqueInput
}

export type tb_ms_methodUpdateOneWithoutTb_log_access_sessionNestedInput = {
  create?: Prisma.XOR<Prisma.tb_ms_methodCreateWithoutTb_log_access_sessionInput, Prisma.tb_ms_methodUncheckedCreateWithoutTb_log_access_sessionInput>
  connectOrCreate?: Prisma.tb_ms_methodCreateOrConnectWithoutTb_log_access_sessionInput
  upsert?: Prisma.tb_ms_methodUpsertWithoutTb_log_access_sessionInput
  disconnect?: Prisma.tb_ms_methodWhereInput | boolean
  delete?: Prisma.tb_ms_methodWhereInput | boolean
  connect?: Prisma.tb_ms_methodWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.tb_ms_methodUpdateToOneWithWhereWithoutTb_log_access_sessionInput, Prisma.tb_ms_methodUpdateWithoutTb_log_access_sessionInput>, Prisma.tb_ms_methodUncheckedUpdateWithoutTb_log_access_sessionInput>
}

export type tb_ms_methodCreateWithoutTb_log_access_sessionInput = {
  method_id?: bigint | number
  method_code: string
  method_name: string
  description?: string | null
  display_order?: number | null
  is_enable?: boolean | null
  created_at?: Date | string
  created_by?: string | null
  updated_at?: Date | string | null
  update_by?: string | null
  record_status?: string | null
}

export type tb_ms_methodUncheckedCreateWithoutTb_log_access_sessionInput = {
  method_id?: bigint | number
  method_code: string
  method_name: string
  description?: string | null
  display_order?: number | null
  is_enable?: boolean | null
  created_at?: Date | string
  created_by?: string | null
  updated_at?: Date | string | null
  update_by?: string | null
  record_status?: string | null
}

export type tb_ms_methodCreateOrConnectWithoutTb_log_access_sessionInput = {
  where: Prisma.tb_ms_methodWhereUniqueInput
  create: Prisma.XOR<Prisma.tb_ms_methodCreateWithoutTb_log_access_sessionInput, Prisma.tb_ms_methodUncheckedCreateWithoutTb_log_access_sessionInput>
}

export type tb_ms_methodUpsertWithoutTb_log_access_sessionInput = {
  update: Prisma.XOR<Prisma.tb_ms_methodUpdateWithoutTb_log_access_sessionInput, Prisma.tb_ms_methodUncheckedUpdateWithoutTb_log_access_sessionInput>
  create: Prisma.XOR<Prisma.tb_ms_methodCreateWithoutTb_log_access_sessionInput, Prisma.tb_ms_methodUncheckedCreateWithoutTb_log_access_sessionInput>
  where?: Prisma.tb_ms_methodWhereInput
}

export type tb_ms_methodUpdateToOneWithWhereWithoutTb_log_access_sessionInput = {
  where?: Prisma.tb_ms_methodWhereInput
  data: Prisma.XOR<Prisma.tb_ms_methodUpdateWithoutTb_log_access_sessionInput, Prisma.tb_ms_methodUncheckedUpdateWithoutTb_log_access_sessionInput>
}

export type tb_ms_methodUpdateWithoutTb_log_access_sessionInput = {
  method_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  method_code?: Prisma.StringFieldUpdateOperationsInput | string
  method_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  display_order?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  is_enable?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type tb_ms_methodUncheckedUpdateWithoutTb_log_access_sessionInput = {
  method_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  method_code?: Prisma.StringFieldUpdateOperationsInput | string
  method_name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  display_order?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  is_enable?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type Tb_ms_methodCountOutputType
 */

export type Tb_ms_methodCountOutputType = {
  tb_log_access_session: number
}

export type Tb_ms_methodCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tb_log_access_session?: boolean | Tb_ms_methodCountOutputTypeCountTb_log_access_sessionArgs
}

/**
 * Tb_ms_methodCountOutputType without action
 */
export type Tb_ms_methodCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tb_ms_methodCountOutputType
   */
  select?: Prisma.Tb_ms_methodCountOutputTypeSelect<ExtArgs> | null
}

/**
 * Tb_ms_methodCountOutputType without action
 */
export type Tb_ms_methodCountOutputTypeCountTb_log_access_sessionArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.tb_log_access_sessionWhereInput
}


export type tb_ms_methodSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  method_id?: boolean
  method_code?: boolean
  method_name?: boolean
  description?: boolean
  display_order?: boolean
  is_enable?: boolean
  created_at?: boolean
  created_by?: boolean
  updated_at?: boolean
  update_by?: boolean
  record_status?: boolean
  tb_log_access_session?: boolean | Prisma.tb_ms_method$tb_log_access_sessionArgs<ExtArgs>
  _count?: boolean | Prisma.Tb_ms_methodCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tb_ms_method"]>

export type tb_ms_methodSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  method_id?: boolean
  method_code?: boolean
  method_name?: boolean
  description?: boolean
  display_order?: boolean
  is_enable?: boolean
  created_at?: boolean
  created_by?: boolean
  updated_at?: boolean
  update_by?: boolean
  record_status?: boolean
}, ExtArgs["result"]["tb_ms_method"]>

export type tb_ms_methodSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  method_id?: boolean
  method_code?: boolean
  method_name?: boolean
  description?: boolean
  display_order?: boolean
  is_enable?: boolean
  created_at?: boolean
  created_by?: boolean
  updated_at?: boolean
  update_by?: boolean
  record_status?: boolean
}, ExtArgs["result"]["tb_ms_method"]>

export type tb_ms_methodSelectScalar = {
  method_id?: boolean
  method_code?: boolean
  method_name?: boolean
  description?: boolean
  display_order?: boolean
  is_enable?: boolean
  created_at?: boolean
  created_by?: boolean
  updated_at?: boolean
  update_by?: boolean
  record_status?: boolean
}

export type tb_ms_methodOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"method_id" | "method_code" | "method_name" | "description" | "display_order" | "is_enable" | "created_at" | "created_by" | "updated_at" | "update_by" | "record_status", ExtArgs["result"]["tb_ms_method"]>
export type tb_ms_methodInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tb_log_access_session?: boolean | Prisma.tb_ms_method$tb_log_access_sessionArgs<ExtArgs>
  _count?: boolean | Prisma.Tb_ms_methodCountOutputTypeDefaultArgs<ExtArgs>
}
export type tb_ms_methodIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type tb_ms_methodIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $tb_ms_methodPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "tb_ms_method"
  objects: {
    tb_log_access_session: Prisma.$tb_log_access_sessionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    method_id: bigint
    method_code: string
    method_name: string
    description: string | null
    display_order: number | null
    is_enable: boolean | null
    created_at: Date
    created_by: string | null
    updated_at: Date | null
    update_by: string | null
    record_status: string | null
  }, ExtArgs["result"]["tb_ms_method"]>
  composites: {}
}

export type tb_ms_methodGetPayload<S extends boolean | null | undefined | tb_ms_methodDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$tb_ms_methodPayload, S>

export type tb_ms_methodCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<tb_ms_methodFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Tb_ms_methodCountAggregateInputType | true
  }

export interface tb_ms_methodDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['tb_ms_method'], meta: { name: 'tb_ms_method' } }
  /**
   * Find zero or one Tb_ms_method that matches the filter.
   * @param {tb_ms_methodFindUniqueArgs} args - Arguments to find a Tb_ms_method
   * @example
   * // Get one Tb_ms_method
   * const tb_ms_method = await prisma.tb_ms_method.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends tb_ms_methodFindUniqueArgs>(args: Prisma.SelectSubset<T, tb_ms_methodFindUniqueArgs<ExtArgs>>): Prisma.Prisma__tb_ms_methodClient<runtime.Types.Result.GetResult<Prisma.$tb_ms_methodPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Tb_ms_method that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {tb_ms_methodFindUniqueOrThrowArgs} args - Arguments to find a Tb_ms_method
   * @example
   * // Get one Tb_ms_method
   * const tb_ms_method = await prisma.tb_ms_method.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends tb_ms_methodFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, tb_ms_methodFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__tb_ms_methodClient<runtime.Types.Result.GetResult<Prisma.$tb_ms_methodPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tb_ms_method that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {tb_ms_methodFindFirstArgs} args - Arguments to find a Tb_ms_method
   * @example
   * // Get one Tb_ms_method
   * const tb_ms_method = await prisma.tb_ms_method.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends tb_ms_methodFindFirstArgs>(args?: Prisma.SelectSubset<T, tb_ms_methodFindFirstArgs<ExtArgs>>): Prisma.Prisma__tb_ms_methodClient<runtime.Types.Result.GetResult<Prisma.$tb_ms_methodPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tb_ms_method that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {tb_ms_methodFindFirstOrThrowArgs} args - Arguments to find a Tb_ms_method
   * @example
   * // Get one Tb_ms_method
   * const tb_ms_method = await prisma.tb_ms_method.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends tb_ms_methodFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, tb_ms_methodFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__tb_ms_methodClient<runtime.Types.Result.GetResult<Prisma.$tb_ms_methodPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Tb_ms_methods that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {tb_ms_methodFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Tb_ms_methods
   * const tb_ms_methods = await prisma.tb_ms_method.findMany()
   * 
   * // Get first 10 Tb_ms_methods
   * const tb_ms_methods = await prisma.tb_ms_method.findMany({ take: 10 })
   * 
   * // Only select the `method_id`
   * const tb_ms_methodWithMethod_idOnly = await prisma.tb_ms_method.findMany({ select: { method_id: true } })
   * 
   */
  findMany<T extends tb_ms_methodFindManyArgs>(args?: Prisma.SelectSubset<T, tb_ms_methodFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$tb_ms_methodPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Tb_ms_method.
   * @param {tb_ms_methodCreateArgs} args - Arguments to create a Tb_ms_method.
   * @example
   * // Create one Tb_ms_method
   * const Tb_ms_method = await prisma.tb_ms_method.create({
   *   data: {
   *     // ... data to create a Tb_ms_method
   *   }
   * })
   * 
   */
  create<T extends tb_ms_methodCreateArgs>(args: Prisma.SelectSubset<T, tb_ms_methodCreateArgs<ExtArgs>>): Prisma.Prisma__tb_ms_methodClient<runtime.Types.Result.GetResult<Prisma.$tb_ms_methodPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Tb_ms_methods.
   * @param {tb_ms_methodCreateManyArgs} args - Arguments to create many Tb_ms_methods.
   * @example
   * // Create many Tb_ms_methods
   * const tb_ms_method = await prisma.tb_ms_method.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends tb_ms_methodCreateManyArgs>(args?: Prisma.SelectSubset<T, tb_ms_methodCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Tb_ms_methods and returns the data saved in the database.
   * @param {tb_ms_methodCreateManyAndReturnArgs} args - Arguments to create many Tb_ms_methods.
   * @example
   * // Create many Tb_ms_methods
   * const tb_ms_method = await prisma.tb_ms_method.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Tb_ms_methods and only return the `method_id`
   * const tb_ms_methodWithMethod_idOnly = await prisma.tb_ms_method.createManyAndReturn({
   *   select: { method_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends tb_ms_methodCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, tb_ms_methodCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$tb_ms_methodPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Tb_ms_method.
   * @param {tb_ms_methodDeleteArgs} args - Arguments to delete one Tb_ms_method.
   * @example
   * // Delete one Tb_ms_method
   * const Tb_ms_method = await prisma.tb_ms_method.delete({
   *   where: {
   *     // ... filter to delete one Tb_ms_method
   *   }
   * })
   * 
   */
  delete<T extends tb_ms_methodDeleteArgs>(args: Prisma.SelectSubset<T, tb_ms_methodDeleteArgs<ExtArgs>>): Prisma.Prisma__tb_ms_methodClient<runtime.Types.Result.GetResult<Prisma.$tb_ms_methodPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Tb_ms_method.
   * @param {tb_ms_methodUpdateArgs} args - Arguments to update one Tb_ms_method.
   * @example
   * // Update one Tb_ms_method
   * const tb_ms_method = await prisma.tb_ms_method.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends tb_ms_methodUpdateArgs>(args: Prisma.SelectSubset<T, tb_ms_methodUpdateArgs<ExtArgs>>): Prisma.Prisma__tb_ms_methodClient<runtime.Types.Result.GetResult<Prisma.$tb_ms_methodPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Tb_ms_methods.
   * @param {tb_ms_methodDeleteManyArgs} args - Arguments to filter Tb_ms_methods to delete.
   * @example
   * // Delete a few Tb_ms_methods
   * const { count } = await prisma.tb_ms_method.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends tb_ms_methodDeleteManyArgs>(args?: Prisma.SelectSubset<T, tb_ms_methodDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tb_ms_methods.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {tb_ms_methodUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Tb_ms_methods
   * const tb_ms_method = await prisma.tb_ms_method.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends tb_ms_methodUpdateManyArgs>(args: Prisma.SelectSubset<T, tb_ms_methodUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tb_ms_methods and returns the data updated in the database.
   * @param {tb_ms_methodUpdateManyAndReturnArgs} args - Arguments to update many Tb_ms_methods.
   * @example
   * // Update many Tb_ms_methods
   * const tb_ms_method = await prisma.tb_ms_method.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Tb_ms_methods and only return the `method_id`
   * const tb_ms_methodWithMethod_idOnly = await prisma.tb_ms_method.updateManyAndReturn({
   *   select: { method_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends tb_ms_methodUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, tb_ms_methodUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$tb_ms_methodPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Tb_ms_method.
   * @param {tb_ms_methodUpsertArgs} args - Arguments to update or create a Tb_ms_method.
   * @example
   * // Update or create a Tb_ms_method
   * const tb_ms_method = await prisma.tb_ms_method.upsert({
   *   create: {
   *     // ... data to create a Tb_ms_method
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Tb_ms_method we want to update
   *   }
   * })
   */
  upsert<T extends tb_ms_methodUpsertArgs>(args: Prisma.SelectSubset<T, tb_ms_methodUpsertArgs<ExtArgs>>): Prisma.Prisma__tb_ms_methodClient<runtime.Types.Result.GetResult<Prisma.$tb_ms_methodPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Tb_ms_methods.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {tb_ms_methodCountArgs} args - Arguments to filter Tb_ms_methods to count.
   * @example
   * // Count the number of Tb_ms_methods
   * const count = await prisma.tb_ms_method.count({
   *   where: {
   *     // ... the filter for the Tb_ms_methods we want to count
   *   }
   * })
  **/
  count<T extends tb_ms_methodCountArgs>(
    args?: Prisma.Subset<T, tb_ms_methodCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Tb_ms_methodCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Tb_ms_method.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Tb_ms_methodAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Tb_ms_methodAggregateArgs>(args: Prisma.Subset<T, Tb_ms_methodAggregateArgs>): Prisma.PrismaPromise<GetTb_ms_methodAggregateType<T>>

  /**
   * Group by Tb_ms_method.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {tb_ms_methodGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends tb_ms_methodGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: tb_ms_methodGroupByArgs['orderBy'] }
      : { orderBy?: tb_ms_methodGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, tb_ms_methodGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTb_ms_methodGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the tb_ms_method model
 */
readonly fields: tb_ms_methodFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for tb_ms_method.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__tb_ms_methodClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tb_log_access_session<T extends Prisma.tb_ms_method$tb_log_access_sessionArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.tb_ms_method$tb_log_access_sessionArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$tb_log_access_sessionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the tb_ms_method model
 */
export interface tb_ms_methodFieldRefs {
  readonly method_id: Prisma.FieldRef<"tb_ms_method", 'BigInt'>
  readonly method_code: Prisma.FieldRef<"tb_ms_method", 'String'>
  readonly method_name: Prisma.FieldRef<"tb_ms_method", 'String'>
  readonly description: Prisma.FieldRef<"tb_ms_method", 'String'>
  readonly display_order: Prisma.FieldRef<"tb_ms_method", 'Int'>
  readonly is_enable: Prisma.FieldRef<"tb_ms_method", 'Boolean'>
  readonly created_at: Prisma.FieldRef<"tb_ms_method", 'DateTime'>
  readonly created_by: Prisma.FieldRef<"tb_ms_method", 'String'>
  readonly updated_at: Prisma.FieldRef<"tb_ms_method", 'DateTime'>
  readonly update_by: Prisma.FieldRef<"tb_ms_method", 'String'>
  readonly record_status: Prisma.FieldRef<"tb_ms_method", 'String'>
}
    

// Custom InputTypes
/**
 * tb_ms_method findUnique
 */
export type tb_ms_methodFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_method
   */
  select?: Prisma.tb_ms_methodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_method
   */
  omit?: Prisma.tb_ms_methodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_methodInclude<ExtArgs> | null
  /**
   * Filter, which tb_ms_method to fetch.
   */
  where: Prisma.tb_ms_methodWhereUniqueInput
}

/**
 * tb_ms_method findUniqueOrThrow
 */
export type tb_ms_methodFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_method
   */
  select?: Prisma.tb_ms_methodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_method
   */
  omit?: Prisma.tb_ms_methodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_methodInclude<ExtArgs> | null
  /**
   * Filter, which tb_ms_method to fetch.
   */
  where: Prisma.tb_ms_methodWhereUniqueInput
}

/**
 * tb_ms_method findFirst
 */
export type tb_ms_methodFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_method
   */
  select?: Prisma.tb_ms_methodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_method
   */
  omit?: Prisma.tb_ms_methodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_methodInclude<ExtArgs> | null
  /**
   * Filter, which tb_ms_method to fetch.
   */
  where?: Prisma.tb_ms_methodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of tb_ms_methods to fetch.
   */
  orderBy?: Prisma.tb_ms_methodOrderByWithRelationInput | Prisma.tb_ms_methodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for tb_ms_methods.
   */
  cursor?: Prisma.tb_ms_methodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` tb_ms_methods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` tb_ms_methods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of tb_ms_methods.
   */
  distinct?: Prisma.Tb_ms_methodScalarFieldEnum | Prisma.Tb_ms_methodScalarFieldEnum[]
}

/**
 * tb_ms_method findFirstOrThrow
 */
export type tb_ms_methodFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_method
   */
  select?: Prisma.tb_ms_methodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_method
   */
  omit?: Prisma.tb_ms_methodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_methodInclude<ExtArgs> | null
  /**
   * Filter, which tb_ms_method to fetch.
   */
  where?: Prisma.tb_ms_methodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of tb_ms_methods to fetch.
   */
  orderBy?: Prisma.tb_ms_methodOrderByWithRelationInput | Prisma.tb_ms_methodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for tb_ms_methods.
   */
  cursor?: Prisma.tb_ms_methodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` tb_ms_methods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` tb_ms_methods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of tb_ms_methods.
   */
  distinct?: Prisma.Tb_ms_methodScalarFieldEnum | Prisma.Tb_ms_methodScalarFieldEnum[]
}

/**
 * tb_ms_method findMany
 */
export type tb_ms_methodFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_method
   */
  select?: Prisma.tb_ms_methodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_method
   */
  omit?: Prisma.tb_ms_methodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_methodInclude<ExtArgs> | null
  /**
   * Filter, which tb_ms_methods to fetch.
   */
  where?: Prisma.tb_ms_methodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of tb_ms_methods to fetch.
   */
  orderBy?: Prisma.tb_ms_methodOrderByWithRelationInput | Prisma.tb_ms_methodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing tb_ms_methods.
   */
  cursor?: Prisma.tb_ms_methodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` tb_ms_methods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` tb_ms_methods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of tb_ms_methods.
   */
  distinct?: Prisma.Tb_ms_methodScalarFieldEnum | Prisma.Tb_ms_methodScalarFieldEnum[]
}

/**
 * tb_ms_method create
 */
export type tb_ms_methodCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_method
   */
  select?: Prisma.tb_ms_methodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_method
   */
  omit?: Prisma.tb_ms_methodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_methodInclude<ExtArgs> | null
  /**
   * The data needed to create a tb_ms_method.
   */
  data: Prisma.XOR<Prisma.tb_ms_methodCreateInput, Prisma.tb_ms_methodUncheckedCreateInput>
}

/**
 * tb_ms_method createMany
 */
export type tb_ms_methodCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many tb_ms_methods.
   */
  data: Prisma.tb_ms_methodCreateManyInput | Prisma.tb_ms_methodCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * tb_ms_method createManyAndReturn
 */
export type tb_ms_methodCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_method
   */
  select?: Prisma.tb_ms_methodSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_method
   */
  omit?: Prisma.tb_ms_methodOmit<ExtArgs> | null
  /**
   * The data used to create many tb_ms_methods.
   */
  data: Prisma.tb_ms_methodCreateManyInput | Prisma.tb_ms_methodCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * tb_ms_method update
 */
export type tb_ms_methodUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_method
   */
  select?: Prisma.tb_ms_methodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_method
   */
  omit?: Prisma.tb_ms_methodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_methodInclude<ExtArgs> | null
  /**
   * The data needed to update a tb_ms_method.
   */
  data: Prisma.XOR<Prisma.tb_ms_methodUpdateInput, Prisma.tb_ms_methodUncheckedUpdateInput>
  /**
   * Choose, which tb_ms_method to update.
   */
  where: Prisma.tb_ms_methodWhereUniqueInput
}

/**
 * tb_ms_method updateMany
 */
export type tb_ms_methodUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update tb_ms_methods.
   */
  data: Prisma.XOR<Prisma.tb_ms_methodUpdateManyMutationInput, Prisma.tb_ms_methodUncheckedUpdateManyInput>
  /**
   * Filter which tb_ms_methods to update
   */
  where?: Prisma.tb_ms_methodWhereInput
  /**
   * Limit how many tb_ms_methods to update.
   */
  limit?: number
}

/**
 * tb_ms_method updateManyAndReturn
 */
export type tb_ms_methodUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_method
   */
  select?: Prisma.tb_ms_methodSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_method
   */
  omit?: Prisma.tb_ms_methodOmit<ExtArgs> | null
  /**
   * The data used to update tb_ms_methods.
   */
  data: Prisma.XOR<Prisma.tb_ms_methodUpdateManyMutationInput, Prisma.tb_ms_methodUncheckedUpdateManyInput>
  /**
   * Filter which tb_ms_methods to update
   */
  where?: Prisma.tb_ms_methodWhereInput
  /**
   * Limit how many tb_ms_methods to update.
   */
  limit?: number
}

/**
 * tb_ms_method upsert
 */
export type tb_ms_methodUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_method
   */
  select?: Prisma.tb_ms_methodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_method
   */
  omit?: Prisma.tb_ms_methodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_methodInclude<ExtArgs> | null
  /**
   * The filter to search for the tb_ms_method to update in case it exists.
   */
  where: Prisma.tb_ms_methodWhereUniqueInput
  /**
   * In case the tb_ms_method found by the `where` argument doesn't exist, create a new tb_ms_method with this data.
   */
  create: Prisma.XOR<Prisma.tb_ms_methodCreateInput, Prisma.tb_ms_methodUncheckedCreateInput>
  /**
   * In case the tb_ms_method was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.tb_ms_methodUpdateInput, Prisma.tb_ms_methodUncheckedUpdateInput>
}

/**
 * tb_ms_method delete
 */
export type tb_ms_methodDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_method
   */
  select?: Prisma.tb_ms_methodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_method
   */
  omit?: Prisma.tb_ms_methodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_methodInclude<ExtArgs> | null
  /**
   * Filter which tb_ms_method to delete.
   */
  where: Prisma.tb_ms_methodWhereUniqueInput
}

/**
 * tb_ms_method deleteMany
 */
export type tb_ms_methodDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which tb_ms_methods to delete
   */
  where?: Prisma.tb_ms_methodWhereInput
  /**
   * Limit how many tb_ms_methods to delete.
   */
  limit?: number
}

/**
 * tb_ms_method.tb_log_access_session
 */
export type tb_ms_method$tb_log_access_sessionArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_log_access_session
   */
  select?: Prisma.tb_log_access_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_log_access_session
   */
  omit?: Prisma.tb_log_access_sessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_log_access_sessionInclude<ExtArgs> | null
  where?: Prisma.tb_log_access_sessionWhereInput
  orderBy?: Prisma.tb_log_access_sessionOrderByWithRelationInput | Prisma.tb_log_access_sessionOrderByWithRelationInput[]
  cursor?: Prisma.tb_log_access_sessionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Tb_log_access_sessionScalarFieldEnum | Prisma.Tb_log_access_sessionScalarFieldEnum[]
}

/**
 * tb_ms_method without action
 */
export type tb_ms_methodDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_ms_method
   */
  select?: Prisma.tb_ms_methodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_ms_method
   */
  omit?: Prisma.tb_ms_methodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_ms_methodInclude<ExtArgs> | null
}
