
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `tb_user_address` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model tb_user_address
 * This model or at least one of its fields has comments in the database, and requires an additional setup for migrations: Read more: https://pris.ly/d/database-comments
 */
export type tb_user_addressModel = runtime.Types.Result.DefaultSelection<Prisma.$tb_user_addressPayload>

export type AggregateTb_user_address = {
  _count: Tb_user_addressCountAggregateOutputType | null
  _avg: Tb_user_addressAvgAggregateOutputType | null
  _sum: Tb_user_addressSumAggregateOutputType | null
  _min: Tb_user_addressMinAggregateOutputType | null
  _max: Tb_user_addressMaxAggregateOutputType | null
}

export type Tb_user_addressAvgAggregateOutputType = {
  address_type: number | null
  tambol_code: number | null
  amphur_code: number | null
  province_code: number | null
}

export type Tb_user_addressSumAggregateOutputType = {
  address_type: number | null
  tambol_code: number | null
  amphur_code: number | null
  province_code: number | null
}

export type Tb_user_addressMinAggregateOutputType = {
  user_address_id: string | null
  user_id: string | null
  address_type: number | null
  home_no: string | null
  moo: string | null
  alley: string | null
  soi: string | null
  road: string | null
  tambol_code: number | null
  tambol_name: string | null
  amphur_code: number | null
  amphur_name: string | null
  province_code: number | null
  province_name: string | null
  remark: string | null
  is_visible: boolean | null
  created_at: Date | null
  updated_at: Date | null
  update_by: string | null
  created_by: string | null
  record_status: string | null
  post_code: string | null
  tel_no: string | null
}

export type Tb_user_addressMaxAggregateOutputType = {
  user_address_id: string | null
  user_id: string | null
  address_type: number | null
  home_no: string | null
  moo: string | null
  alley: string | null
  soi: string | null
  road: string | null
  tambol_code: number | null
  tambol_name: string | null
  amphur_code: number | null
  amphur_name: string | null
  province_code: number | null
  province_name: string | null
  remark: string | null
  is_visible: boolean | null
  created_at: Date | null
  updated_at: Date | null
  update_by: string | null
  created_by: string | null
  record_status: string | null
  post_code: string | null
  tel_no: string | null
}

export type Tb_user_addressCountAggregateOutputType = {
  user_address_id: number
  user_id: number
  address_type: number
  home_no: number
  moo: number
  alley: number
  soi: number
  road: number
  tambol_code: number
  tambol_name: number
  amphur_code: number
  amphur_name: number
  province_code: number
  province_name: number
  remark: number
  is_visible: number
  created_at: number
  updated_at: number
  update_by: number
  created_by: number
  record_status: number
  post_code: number
  tel_no: number
  _all: number
}


export type Tb_user_addressAvgAggregateInputType = {
  address_type?: true
  tambol_code?: true
  amphur_code?: true
  province_code?: true
}

export type Tb_user_addressSumAggregateInputType = {
  address_type?: true
  tambol_code?: true
  amphur_code?: true
  province_code?: true
}

export type Tb_user_addressMinAggregateInputType = {
  user_address_id?: true
  user_id?: true
  address_type?: true
  home_no?: true
  moo?: true
  alley?: true
  soi?: true
  road?: true
  tambol_code?: true
  tambol_name?: true
  amphur_code?: true
  amphur_name?: true
  province_code?: true
  province_name?: true
  remark?: true
  is_visible?: true
  created_at?: true
  updated_at?: true
  update_by?: true
  created_by?: true
  record_status?: true
  post_code?: true
  tel_no?: true
}

export type Tb_user_addressMaxAggregateInputType = {
  user_address_id?: true
  user_id?: true
  address_type?: true
  home_no?: true
  moo?: true
  alley?: true
  soi?: true
  road?: true
  tambol_code?: true
  tambol_name?: true
  amphur_code?: true
  amphur_name?: true
  province_code?: true
  province_name?: true
  remark?: true
  is_visible?: true
  created_at?: true
  updated_at?: true
  update_by?: true
  created_by?: true
  record_status?: true
  post_code?: true
  tel_no?: true
}

export type Tb_user_addressCountAggregateInputType = {
  user_address_id?: true
  user_id?: true
  address_type?: true
  home_no?: true
  moo?: true
  alley?: true
  soi?: true
  road?: true
  tambol_code?: true
  tambol_name?: true
  amphur_code?: true
  amphur_name?: true
  province_code?: true
  province_name?: true
  remark?: true
  is_visible?: true
  created_at?: true
  updated_at?: true
  update_by?: true
  created_by?: true
  record_status?: true
  post_code?: true
  tel_no?: true
  _all?: true
}

export type Tb_user_addressAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which tb_user_address to aggregate.
   */
  where?: Prisma.tb_user_addressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of tb_user_addresses to fetch.
   */
  orderBy?: Prisma.tb_user_addressOrderByWithRelationInput | Prisma.tb_user_addressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.tb_user_addressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` tb_user_addresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` tb_user_addresses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned tb_user_addresses
  **/
  _count?: true | Tb_user_addressCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Tb_user_addressAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Tb_user_addressSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Tb_user_addressMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Tb_user_addressMaxAggregateInputType
}

export type GetTb_user_addressAggregateType<T extends Tb_user_addressAggregateArgs> = {
      [P in keyof T & keyof AggregateTb_user_address]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTb_user_address[P]>
    : Prisma.GetScalarType<T[P], AggregateTb_user_address[P]>
}




export type tb_user_addressGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.tb_user_addressWhereInput
  orderBy?: Prisma.tb_user_addressOrderByWithAggregationInput | Prisma.tb_user_addressOrderByWithAggregationInput[]
  by: Prisma.Tb_user_addressScalarFieldEnum[] | Prisma.Tb_user_addressScalarFieldEnum
  having?: Prisma.tb_user_addressScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Tb_user_addressCountAggregateInputType | true
  _avg?: Tb_user_addressAvgAggregateInputType
  _sum?: Tb_user_addressSumAggregateInputType
  _min?: Tb_user_addressMinAggregateInputType
  _max?: Tb_user_addressMaxAggregateInputType
}

export type Tb_user_addressGroupByOutputType = {
  user_address_id: string
  user_id: string
  address_type: number | null
  home_no: string | null
  moo: string | null
  alley: string | null
  soi: string | null
  road: string | null
  tambol_code: number | null
  tambol_name: string | null
  amphur_code: number | null
  amphur_name: string | null
  province_code: number | null
  province_name: string | null
  remark: string | null
  is_visible: boolean | null
  created_at: Date
  updated_at: Date | null
  update_by: string | null
  created_by: string | null
  record_status: string | null
  post_code: string | null
  tel_no: string | null
  _count: Tb_user_addressCountAggregateOutputType | null
  _avg: Tb_user_addressAvgAggregateOutputType | null
  _sum: Tb_user_addressSumAggregateOutputType | null
  _min: Tb_user_addressMinAggregateOutputType | null
  _max: Tb_user_addressMaxAggregateOutputType | null
}

export type GetTb_user_addressGroupByPayload<T extends tb_user_addressGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Tb_user_addressGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Tb_user_addressGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Tb_user_addressGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Tb_user_addressGroupByOutputType[P]>
      }
    >
  >



export type tb_user_addressWhereInput = {
  AND?: Prisma.tb_user_addressWhereInput | Prisma.tb_user_addressWhereInput[]
  OR?: Prisma.tb_user_addressWhereInput[]
  NOT?: Prisma.tb_user_addressWhereInput | Prisma.tb_user_addressWhereInput[]
  user_address_id?: Prisma.UuidFilter<"tb_user_address"> | string
  user_id?: Prisma.UuidFilter<"tb_user_address"> | string
  address_type?: Prisma.IntNullableFilter<"tb_user_address"> | number | null
  home_no?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  moo?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  alley?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  soi?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  road?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  tambol_code?: Prisma.IntNullableFilter<"tb_user_address"> | number | null
  tambol_name?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  amphur_code?: Prisma.IntNullableFilter<"tb_user_address"> | number | null
  amphur_name?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  province_code?: Prisma.IntNullableFilter<"tb_user_address"> | number | null
  province_name?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  remark?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  is_visible?: Prisma.BoolNullableFilter<"tb_user_address"> | boolean | null
  created_at?: Prisma.DateTimeFilter<"tb_user_address"> | Date | string
  updated_at?: Prisma.DateTimeNullableFilter<"tb_user_address"> | Date | string | null
  update_by?: Prisma.UuidNullableFilter<"tb_user_address"> | string | null
  created_by?: Prisma.UuidNullableFilter<"tb_user_address"> | string | null
  record_status?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  post_code?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  tel_no?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  tb_user?: Prisma.XOR<Prisma.Tb_userScalarRelationFilter, Prisma.tb_userWhereInput>
}

export type tb_user_addressOrderByWithRelationInput = {
  user_address_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  address_type?: Prisma.SortOrderInput | Prisma.SortOrder
  home_no?: Prisma.SortOrderInput | Prisma.SortOrder
  moo?: Prisma.SortOrderInput | Prisma.SortOrder
  alley?: Prisma.SortOrderInput | Prisma.SortOrder
  soi?: Prisma.SortOrderInput | Prisma.SortOrder
  road?: Prisma.SortOrderInput | Prisma.SortOrder
  tambol_code?: Prisma.SortOrderInput | Prisma.SortOrder
  tambol_name?: Prisma.SortOrderInput | Prisma.SortOrder
  amphur_code?: Prisma.SortOrderInput | Prisma.SortOrder
  amphur_name?: Prisma.SortOrderInput | Prisma.SortOrder
  province_code?: Prisma.SortOrderInput | Prisma.SortOrder
  province_name?: Prisma.SortOrderInput | Prisma.SortOrder
  remark?: Prisma.SortOrderInput | Prisma.SortOrder
  is_visible?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  update_by?: Prisma.SortOrderInput | Prisma.SortOrder
  created_by?: Prisma.SortOrderInput | Prisma.SortOrder
  record_status?: Prisma.SortOrderInput | Prisma.SortOrder
  post_code?: Prisma.SortOrderInput | Prisma.SortOrder
  tel_no?: Prisma.SortOrderInput | Prisma.SortOrder
  tb_user?: Prisma.tb_userOrderByWithRelationInput
}

export type tb_user_addressWhereUniqueInput = Prisma.AtLeast<{
  user_address_id?: string
  AND?: Prisma.tb_user_addressWhereInput | Prisma.tb_user_addressWhereInput[]
  OR?: Prisma.tb_user_addressWhereInput[]
  NOT?: Prisma.tb_user_addressWhereInput | Prisma.tb_user_addressWhereInput[]
  user_id?: Prisma.UuidFilter<"tb_user_address"> | string
  address_type?: Prisma.IntNullableFilter<"tb_user_address"> | number | null
  home_no?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  moo?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  alley?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  soi?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  road?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  tambol_code?: Prisma.IntNullableFilter<"tb_user_address"> | number | null
  tambol_name?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  amphur_code?: Prisma.IntNullableFilter<"tb_user_address"> | number | null
  amphur_name?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  province_code?: Prisma.IntNullableFilter<"tb_user_address"> | number | null
  province_name?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  remark?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  is_visible?: Prisma.BoolNullableFilter<"tb_user_address"> | boolean | null
  created_at?: Prisma.DateTimeFilter<"tb_user_address"> | Date | string
  updated_at?: Prisma.DateTimeNullableFilter<"tb_user_address"> | Date | string | null
  update_by?: Prisma.UuidNullableFilter<"tb_user_address"> | string | null
  created_by?: Prisma.UuidNullableFilter<"tb_user_address"> | string | null
  record_status?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  post_code?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  tel_no?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  tb_user?: Prisma.XOR<Prisma.Tb_userScalarRelationFilter, Prisma.tb_userWhereInput>
}, "user_address_id">

export type tb_user_addressOrderByWithAggregationInput = {
  user_address_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  address_type?: Prisma.SortOrderInput | Prisma.SortOrder
  home_no?: Prisma.SortOrderInput | Prisma.SortOrder
  moo?: Prisma.SortOrderInput | Prisma.SortOrder
  alley?: Prisma.SortOrderInput | Prisma.SortOrder
  soi?: Prisma.SortOrderInput | Prisma.SortOrder
  road?: Prisma.SortOrderInput | Prisma.SortOrder
  tambol_code?: Prisma.SortOrderInput | Prisma.SortOrder
  tambol_name?: Prisma.SortOrderInput | Prisma.SortOrder
  amphur_code?: Prisma.SortOrderInput | Prisma.SortOrder
  amphur_name?: Prisma.SortOrderInput | Prisma.SortOrder
  province_code?: Prisma.SortOrderInput | Prisma.SortOrder
  province_name?: Prisma.SortOrderInput | Prisma.SortOrder
  remark?: Prisma.SortOrderInput | Prisma.SortOrder
  is_visible?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  update_by?: Prisma.SortOrderInput | Prisma.SortOrder
  created_by?: Prisma.SortOrderInput | Prisma.SortOrder
  record_status?: Prisma.SortOrderInput | Prisma.SortOrder
  post_code?: Prisma.SortOrderInput | Prisma.SortOrder
  tel_no?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.tb_user_addressCountOrderByAggregateInput
  _avg?: Prisma.tb_user_addressAvgOrderByAggregateInput
  _max?: Prisma.tb_user_addressMaxOrderByAggregateInput
  _min?: Prisma.tb_user_addressMinOrderByAggregateInput
  _sum?: Prisma.tb_user_addressSumOrderByAggregateInput
}

export type tb_user_addressScalarWhereWithAggregatesInput = {
  AND?: Prisma.tb_user_addressScalarWhereWithAggregatesInput | Prisma.tb_user_addressScalarWhereWithAggregatesInput[]
  OR?: Prisma.tb_user_addressScalarWhereWithAggregatesInput[]
  NOT?: Prisma.tb_user_addressScalarWhereWithAggregatesInput | Prisma.tb_user_addressScalarWhereWithAggregatesInput[]
  user_address_id?: Prisma.UuidWithAggregatesFilter<"tb_user_address"> | string
  user_id?: Prisma.UuidWithAggregatesFilter<"tb_user_address"> | string
  address_type?: Prisma.IntNullableWithAggregatesFilter<"tb_user_address"> | number | null
  home_no?: Prisma.StringNullableWithAggregatesFilter<"tb_user_address"> | string | null
  moo?: Prisma.StringNullableWithAggregatesFilter<"tb_user_address"> | string | null
  alley?: Prisma.StringNullableWithAggregatesFilter<"tb_user_address"> | string | null
  soi?: Prisma.StringNullableWithAggregatesFilter<"tb_user_address"> | string | null
  road?: Prisma.StringNullableWithAggregatesFilter<"tb_user_address"> | string | null
  tambol_code?: Prisma.IntNullableWithAggregatesFilter<"tb_user_address"> | number | null
  tambol_name?: Prisma.StringNullableWithAggregatesFilter<"tb_user_address"> | string | null
  amphur_code?: Prisma.IntNullableWithAggregatesFilter<"tb_user_address"> | number | null
  amphur_name?: Prisma.StringNullableWithAggregatesFilter<"tb_user_address"> | string | null
  province_code?: Prisma.IntNullableWithAggregatesFilter<"tb_user_address"> | number | null
  province_name?: Prisma.StringNullableWithAggregatesFilter<"tb_user_address"> | string | null
  remark?: Prisma.StringNullableWithAggregatesFilter<"tb_user_address"> | string | null
  is_visible?: Prisma.BoolNullableWithAggregatesFilter<"tb_user_address"> | boolean | null
  created_at?: Prisma.DateTimeWithAggregatesFilter<"tb_user_address"> | Date | string
  updated_at?: Prisma.DateTimeNullableWithAggregatesFilter<"tb_user_address"> | Date | string | null
  update_by?: Prisma.UuidNullableWithAggregatesFilter<"tb_user_address"> | string | null
  created_by?: Prisma.UuidNullableWithAggregatesFilter<"tb_user_address"> | string | null
  record_status?: Prisma.StringNullableWithAggregatesFilter<"tb_user_address"> | string | null
  post_code?: Prisma.StringNullableWithAggregatesFilter<"tb_user_address"> | string | null
  tel_no?: Prisma.StringNullableWithAggregatesFilter<"tb_user_address"> | string | null
}

export type tb_user_addressCreateInput = {
  user_address_id?: string
  address_type?: number | null
  home_no?: string | null
  moo?: string | null
  alley?: string | null
  soi?: string | null
  road?: string | null
  tambol_code?: number | null
  tambol_name?: string | null
  amphur_code?: number | null
  amphur_name?: string | null
  province_code?: number | null
  province_name?: string | null
  remark?: string | null
  is_visible?: boolean | null
  created_at?: Date | string
  updated_at?: Date | string | null
  update_by?: string | null
  created_by?: string | null
  record_status?: string | null
  post_code?: string | null
  tel_no?: string | null
  tb_user: Prisma.tb_userCreateNestedOneWithoutTb_user_addressInput
}

export type tb_user_addressUncheckedCreateInput = {
  user_address_id?: string
  user_id: string
  address_type?: number | null
  home_no?: string | null
  moo?: string | null
  alley?: string | null
  soi?: string | null
  road?: string | null
  tambol_code?: number | null
  tambol_name?: string | null
  amphur_code?: number | null
  amphur_name?: string | null
  province_code?: number | null
  province_name?: string | null
  remark?: string | null
  is_visible?: boolean | null
  created_at?: Date | string
  updated_at?: Date | string | null
  update_by?: string | null
  created_by?: string | null
  record_status?: string | null
  post_code?: string | null
  tel_no?: string | null
}

export type tb_user_addressUpdateInput = {
  user_address_id?: Prisma.StringFieldUpdateOperationsInput | string
  address_type?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  home_no?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  moo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  alley?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  soi?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  road?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tambol_code?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tambol_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amphur_code?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  amphur_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  province_code?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  province_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  remark?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_visible?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  post_code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tel_no?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tb_user?: Prisma.tb_userUpdateOneRequiredWithoutTb_user_addressNestedInput
}

export type tb_user_addressUncheckedUpdateInput = {
  user_address_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  address_type?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  home_no?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  moo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  alley?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  soi?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  road?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tambol_code?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tambol_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amphur_code?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  amphur_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  province_code?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  province_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  remark?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_visible?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  post_code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tel_no?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type tb_user_addressCreateManyInput = {
  user_address_id?: string
  user_id: string
  address_type?: number | null
  home_no?: string | null
  moo?: string | null
  alley?: string | null
  soi?: string | null
  road?: string | null
  tambol_code?: number | null
  tambol_name?: string | null
  amphur_code?: number | null
  amphur_name?: string | null
  province_code?: number | null
  province_name?: string | null
  remark?: string | null
  is_visible?: boolean | null
  created_at?: Date | string
  updated_at?: Date | string | null
  update_by?: string | null
  created_by?: string | null
  record_status?: string | null
  post_code?: string | null
  tel_no?: string | null
}

export type tb_user_addressUpdateManyMutationInput = {
  user_address_id?: Prisma.StringFieldUpdateOperationsInput | string
  address_type?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  home_no?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  moo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  alley?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  soi?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  road?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tambol_code?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tambol_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amphur_code?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  amphur_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  province_code?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  province_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  remark?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_visible?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  post_code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tel_no?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type tb_user_addressUncheckedUpdateManyInput = {
  user_address_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  address_type?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  home_no?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  moo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  alley?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  soi?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  road?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tambol_code?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tambol_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amphur_code?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  amphur_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  province_code?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  province_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  remark?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_visible?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  post_code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tel_no?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type Tb_user_addressListRelationFilter = {
  every?: Prisma.tb_user_addressWhereInput
  some?: Prisma.tb_user_addressWhereInput
  none?: Prisma.tb_user_addressWhereInput
}

export type tb_user_addressOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type tb_user_addressCountOrderByAggregateInput = {
  user_address_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  address_type?: Prisma.SortOrder
  home_no?: Prisma.SortOrder
  moo?: Prisma.SortOrder
  alley?: Prisma.SortOrder
  soi?: Prisma.SortOrder
  road?: Prisma.SortOrder
  tambol_code?: Prisma.SortOrder
  tambol_name?: Prisma.SortOrder
  amphur_code?: Prisma.SortOrder
  amphur_name?: Prisma.SortOrder
  province_code?: Prisma.SortOrder
  province_name?: Prisma.SortOrder
  remark?: Prisma.SortOrder
  is_visible?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  update_by?: Prisma.SortOrder
  created_by?: Prisma.SortOrder
  record_status?: Prisma.SortOrder
  post_code?: Prisma.SortOrder
  tel_no?: Prisma.SortOrder
}

export type tb_user_addressAvgOrderByAggregateInput = {
  address_type?: Prisma.SortOrder
  tambol_code?: Prisma.SortOrder
  amphur_code?: Prisma.SortOrder
  province_code?: Prisma.SortOrder
}

export type tb_user_addressMaxOrderByAggregateInput = {
  user_address_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  address_type?: Prisma.SortOrder
  home_no?: Prisma.SortOrder
  moo?: Prisma.SortOrder
  alley?: Prisma.SortOrder
  soi?: Prisma.SortOrder
  road?: Prisma.SortOrder
  tambol_code?: Prisma.SortOrder
  tambol_name?: Prisma.SortOrder
  amphur_code?: Prisma.SortOrder
  amphur_name?: Prisma.SortOrder
  province_code?: Prisma.SortOrder
  province_name?: Prisma.SortOrder
  remark?: Prisma.SortOrder
  is_visible?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  update_by?: Prisma.SortOrder
  created_by?: Prisma.SortOrder
  record_status?: Prisma.SortOrder
  post_code?: Prisma.SortOrder
  tel_no?: Prisma.SortOrder
}

export type tb_user_addressMinOrderByAggregateInput = {
  user_address_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  address_type?: Prisma.SortOrder
  home_no?: Prisma.SortOrder
  moo?: Prisma.SortOrder
  alley?: Prisma.SortOrder
  soi?: Prisma.SortOrder
  road?: Prisma.SortOrder
  tambol_code?: Prisma.SortOrder
  tambol_name?: Prisma.SortOrder
  amphur_code?: Prisma.SortOrder
  amphur_name?: Prisma.SortOrder
  province_code?: Prisma.SortOrder
  province_name?: Prisma.SortOrder
  remark?: Prisma.SortOrder
  is_visible?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  update_by?: Prisma.SortOrder
  created_by?: Prisma.SortOrder
  record_status?: Prisma.SortOrder
  post_code?: Prisma.SortOrder
  tel_no?: Prisma.SortOrder
}

export type tb_user_addressSumOrderByAggregateInput = {
  address_type?: Prisma.SortOrder
  tambol_code?: Prisma.SortOrder
  amphur_code?: Prisma.SortOrder
  province_code?: Prisma.SortOrder
}

export type tb_user_addressCreateNestedManyWithoutTb_userInput = {
  create?: Prisma.XOR<Prisma.tb_user_addressCreateWithoutTb_userInput, Prisma.tb_user_addressUncheckedCreateWithoutTb_userInput> | Prisma.tb_user_addressCreateWithoutTb_userInput[] | Prisma.tb_user_addressUncheckedCreateWithoutTb_userInput[]
  connectOrCreate?: Prisma.tb_user_addressCreateOrConnectWithoutTb_userInput | Prisma.tb_user_addressCreateOrConnectWithoutTb_userInput[]
  createMany?: Prisma.tb_user_addressCreateManyTb_userInputEnvelope
  connect?: Prisma.tb_user_addressWhereUniqueInput | Prisma.tb_user_addressWhereUniqueInput[]
}

export type tb_user_addressUncheckedCreateNestedManyWithoutTb_userInput = {
  create?: Prisma.XOR<Prisma.tb_user_addressCreateWithoutTb_userInput, Prisma.tb_user_addressUncheckedCreateWithoutTb_userInput> | Prisma.tb_user_addressCreateWithoutTb_userInput[] | Prisma.tb_user_addressUncheckedCreateWithoutTb_userInput[]
  connectOrCreate?: Prisma.tb_user_addressCreateOrConnectWithoutTb_userInput | Prisma.tb_user_addressCreateOrConnectWithoutTb_userInput[]
  createMany?: Prisma.tb_user_addressCreateManyTb_userInputEnvelope
  connect?: Prisma.tb_user_addressWhereUniqueInput | Prisma.tb_user_addressWhereUniqueInput[]
}

export type tb_user_addressUpdateManyWithoutTb_userNestedInput = {
  create?: Prisma.XOR<Prisma.tb_user_addressCreateWithoutTb_userInput, Prisma.tb_user_addressUncheckedCreateWithoutTb_userInput> | Prisma.tb_user_addressCreateWithoutTb_userInput[] | Prisma.tb_user_addressUncheckedCreateWithoutTb_userInput[]
  connectOrCreate?: Prisma.tb_user_addressCreateOrConnectWithoutTb_userInput | Prisma.tb_user_addressCreateOrConnectWithoutTb_userInput[]
  upsert?: Prisma.tb_user_addressUpsertWithWhereUniqueWithoutTb_userInput | Prisma.tb_user_addressUpsertWithWhereUniqueWithoutTb_userInput[]
  createMany?: Prisma.tb_user_addressCreateManyTb_userInputEnvelope
  set?: Prisma.tb_user_addressWhereUniqueInput | Prisma.tb_user_addressWhereUniqueInput[]
  disconnect?: Prisma.tb_user_addressWhereUniqueInput | Prisma.tb_user_addressWhereUniqueInput[]
  delete?: Prisma.tb_user_addressWhereUniqueInput | Prisma.tb_user_addressWhereUniqueInput[]
  connect?: Prisma.tb_user_addressWhereUniqueInput | Prisma.tb_user_addressWhereUniqueInput[]
  update?: Prisma.tb_user_addressUpdateWithWhereUniqueWithoutTb_userInput | Prisma.tb_user_addressUpdateWithWhereUniqueWithoutTb_userInput[]
  updateMany?: Prisma.tb_user_addressUpdateManyWithWhereWithoutTb_userInput | Prisma.tb_user_addressUpdateManyWithWhereWithoutTb_userInput[]
  deleteMany?: Prisma.tb_user_addressScalarWhereInput | Prisma.tb_user_addressScalarWhereInput[]
}

export type tb_user_addressUncheckedUpdateManyWithoutTb_userNestedInput = {
  create?: Prisma.XOR<Prisma.tb_user_addressCreateWithoutTb_userInput, Prisma.tb_user_addressUncheckedCreateWithoutTb_userInput> | Prisma.tb_user_addressCreateWithoutTb_userInput[] | Prisma.tb_user_addressUncheckedCreateWithoutTb_userInput[]
  connectOrCreate?: Prisma.tb_user_addressCreateOrConnectWithoutTb_userInput | Prisma.tb_user_addressCreateOrConnectWithoutTb_userInput[]
  upsert?: Prisma.tb_user_addressUpsertWithWhereUniqueWithoutTb_userInput | Prisma.tb_user_addressUpsertWithWhereUniqueWithoutTb_userInput[]
  createMany?: Prisma.tb_user_addressCreateManyTb_userInputEnvelope
  set?: Prisma.tb_user_addressWhereUniqueInput | Prisma.tb_user_addressWhereUniqueInput[]
  disconnect?: Prisma.tb_user_addressWhereUniqueInput | Prisma.tb_user_addressWhereUniqueInput[]
  delete?: Prisma.tb_user_addressWhereUniqueInput | Prisma.tb_user_addressWhereUniqueInput[]
  connect?: Prisma.tb_user_addressWhereUniqueInput | Prisma.tb_user_addressWhereUniqueInput[]
  update?: Prisma.tb_user_addressUpdateWithWhereUniqueWithoutTb_userInput | Prisma.tb_user_addressUpdateWithWhereUniqueWithoutTb_userInput[]
  updateMany?: Prisma.tb_user_addressUpdateManyWithWhereWithoutTb_userInput | Prisma.tb_user_addressUpdateManyWithWhereWithoutTb_userInput[]
  deleteMany?: Prisma.tb_user_addressScalarWhereInput | Prisma.tb_user_addressScalarWhereInput[]
}

export type tb_user_addressCreateWithoutTb_userInput = {
  user_address_id?: string
  address_type?: number | null
  home_no?: string | null
  moo?: string | null
  alley?: string | null
  soi?: string | null
  road?: string | null
  tambol_code?: number | null
  tambol_name?: string | null
  amphur_code?: number | null
  amphur_name?: string | null
  province_code?: number | null
  province_name?: string | null
  remark?: string | null
  is_visible?: boolean | null
  created_at?: Date | string
  updated_at?: Date | string | null
  update_by?: string | null
  created_by?: string | null
  record_status?: string | null
  post_code?: string | null
  tel_no?: string | null
}

export type tb_user_addressUncheckedCreateWithoutTb_userInput = {
  user_address_id?: string
  address_type?: number | null
  home_no?: string | null
  moo?: string | null
  alley?: string | null
  soi?: string | null
  road?: string | null
  tambol_code?: number | null
  tambol_name?: string | null
  amphur_code?: number | null
  amphur_name?: string | null
  province_code?: number | null
  province_name?: string | null
  remark?: string | null
  is_visible?: boolean | null
  created_at?: Date | string
  updated_at?: Date | string | null
  update_by?: string | null
  created_by?: string | null
  record_status?: string | null
  post_code?: string | null
  tel_no?: string | null
}

export type tb_user_addressCreateOrConnectWithoutTb_userInput = {
  where: Prisma.tb_user_addressWhereUniqueInput
  create: Prisma.XOR<Prisma.tb_user_addressCreateWithoutTb_userInput, Prisma.tb_user_addressUncheckedCreateWithoutTb_userInput>
}

export type tb_user_addressCreateManyTb_userInputEnvelope = {
  data: Prisma.tb_user_addressCreateManyTb_userInput | Prisma.tb_user_addressCreateManyTb_userInput[]
  skipDuplicates?: boolean
}

export type tb_user_addressUpsertWithWhereUniqueWithoutTb_userInput = {
  where: Prisma.tb_user_addressWhereUniqueInput
  update: Prisma.XOR<Prisma.tb_user_addressUpdateWithoutTb_userInput, Prisma.tb_user_addressUncheckedUpdateWithoutTb_userInput>
  create: Prisma.XOR<Prisma.tb_user_addressCreateWithoutTb_userInput, Prisma.tb_user_addressUncheckedCreateWithoutTb_userInput>
}

export type tb_user_addressUpdateWithWhereUniqueWithoutTb_userInput = {
  where: Prisma.tb_user_addressWhereUniqueInput
  data: Prisma.XOR<Prisma.tb_user_addressUpdateWithoutTb_userInput, Prisma.tb_user_addressUncheckedUpdateWithoutTb_userInput>
}

export type tb_user_addressUpdateManyWithWhereWithoutTb_userInput = {
  where: Prisma.tb_user_addressScalarWhereInput
  data: Prisma.XOR<Prisma.tb_user_addressUpdateManyMutationInput, Prisma.tb_user_addressUncheckedUpdateManyWithoutTb_userInput>
}

export type tb_user_addressScalarWhereInput = {
  AND?: Prisma.tb_user_addressScalarWhereInput | Prisma.tb_user_addressScalarWhereInput[]
  OR?: Prisma.tb_user_addressScalarWhereInput[]
  NOT?: Prisma.tb_user_addressScalarWhereInput | Prisma.tb_user_addressScalarWhereInput[]
  user_address_id?: Prisma.UuidFilter<"tb_user_address"> | string
  user_id?: Prisma.UuidFilter<"tb_user_address"> | string
  address_type?: Prisma.IntNullableFilter<"tb_user_address"> | number | null
  home_no?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  moo?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  alley?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  soi?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  road?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  tambol_code?: Prisma.IntNullableFilter<"tb_user_address"> | number | null
  tambol_name?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  amphur_code?: Prisma.IntNullableFilter<"tb_user_address"> | number | null
  amphur_name?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  province_code?: Prisma.IntNullableFilter<"tb_user_address"> | number | null
  province_name?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  remark?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  is_visible?: Prisma.BoolNullableFilter<"tb_user_address"> | boolean | null
  created_at?: Prisma.DateTimeFilter<"tb_user_address"> | Date | string
  updated_at?: Prisma.DateTimeNullableFilter<"tb_user_address"> | Date | string | null
  update_by?: Prisma.UuidNullableFilter<"tb_user_address"> | string | null
  created_by?: Prisma.UuidNullableFilter<"tb_user_address"> | string | null
  record_status?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  post_code?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
  tel_no?: Prisma.StringNullableFilter<"tb_user_address"> | string | null
}

export type tb_user_addressCreateManyTb_userInput = {
  user_address_id?: string
  address_type?: number | null
  home_no?: string | null
  moo?: string | null
  alley?: string | null
  soi?: string | null
  road?: string | null
  tambol_code?: number | null
  tambol_name?: string | null
  amphur_code?: number | null
  amphur_name?: string | null
  province_code?: number | null
  province_name?: string | null
  remark?: string | null
  is_visible?: boolean | null
  created_at?: Date | string
  updated_at?: Date | string | null
  update_by?: string | null
  created_by?: string | null
  record_status?: string | null
  post_code?: string | null
  tel_no?: string | null
}

export type tb_user_addressUpdateWithoutTb_userInput = {
  user_address_id?: Prisma.StringFieldUpdateOperationsInput | string
  address_type?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  home_no?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  moo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  alley?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  soi?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  road?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tambol_code?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tambol_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amphur_code?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  amphur_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  province_code?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  province_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  remark?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_visible?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  post_code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tel_no?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type tb_user_addressUncheckedUpdateWithoutTb_userInput = {
  user_address_id?: Prisma.StringFieldUpdateOperationsInput | string
  address_type?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  home_no?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  moo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  alley?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  soi?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  road?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tambol_code?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tambol_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amphur_code?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  amphur_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  province_code?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  province_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  remark?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_visible?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  post_code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tel_no?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type tb_user_addressUncheckedUpdateManyWithoutTb_userInput = {
  user_address_id?: Prisma.StringFieldUpdateOperationsInput | string
  address_type?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  home_no?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  moo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  alley?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  soi?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  road?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tambol_code?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tambol_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amphur_code?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  amphur_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  province_code?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  province_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  remark?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_visible?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  update_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  record_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  post_code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tel_no?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type tb_user_addressSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_address_id?: boolean
  user_id?: boolean
  address_type?: boolean
  home_no?: boolean
  moo?: boolean
  alley?: boolean
  soi?: boolean
  road?: boolean
  tambol_code?: boolean
  tambol_name?: boolean
  amphur_code?: boolean
  amphur_name?: boolean
  province_code?: boolean
  province_name?: boolean
  remark?: boolean
  is_visible?: boolean
  created_at?: boolean
  updated_at?: boolean
  update_by?: boolean
  created_by?: boolean
  record_status?: boolean
  post_code?: boolean
  tel_no?: boolean
  tb_user?: boolean | Prisma.tb_userDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tb_user_address"]>

export type tb_user_addressSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_address_id?: boolean
  user_id?: boolean
  address_type?: boolean
  home_no?: boolean
  moo?: boolean
  alley?: boolean
  soi?: boolean
  road?: boolean
  tambol_code?: boolean
  tambol_name?: boolean
  amphur_code?: boolean
  amphur_name?: boolean
  province_code?: boolean
  province_name?: boolean
  remark?: boolean
  is_visible?: boolean
  created_at?: boolean
  updated_at?: boolean
  update_by?: boolean
  created_by?: boolean
  record_status?: boolean
  post_code?: boolean
  tel_no?: boolean
  tb_user?: boolean | Prisma.tb_userDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tb_user_address"]>

export type tb_user_addressSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_address_id?: boolean
  user_id?: boolean
  address_type?: boolean
  home_no?: boolean
  moo?: boolean
  alley?: boolean
  soi?: boolean
  road?: boolean
  tambol_code?: boolean
  tambol_name?: boolean
  amphur_code?: boolean
  amphur_name?: boolean
  province_code?: boolean
  province_name?: boolean
  remark?: boolean
  is_visible?: boolean
  created_at?: boolean
  updated_at?: boolean
  update_by?: boolean
  created_by?: boolean
  record_status?: boolean
  post_code?: boolean
  tel_no?: boolean
  tb_user?: boolean | Prisma.tb_userDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tb_user_address"]>

export type tb_user_addressSelectScalar = {
  user_address_id?: boolean
  user_id?: boolean
  address_type?: boolean
  home_no?: boolean
  moo?: boolean
  alley?: boolean
  soi?: boolean
  road?: boolean
  tambol_code?: boolean
  tambol_name?: boolean
  amphur_code?: boolean
  amphur_name?: boolean
  province_code?: boolean
  province_name?: boolean
  remark?: boolean
  is_visible?: boolean
  created_at?: boolean
  updated_at?: boolean
  update_by?: boolean
  created_by?: boolean
  record_status?: boolean
  post_code?: boolean
  tel_no?: boolean
}

export type tb_user_addressOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"user_address_id" | "user_id" | "address_type" | "home_no" | "moo" | "alley" | "soi" | "road" | "tambol_code" | "tambol_name" | "amphur_code" | "amphur_name" | "province_code" | "province_name" | "remark" | "is_visible" | "created_at" | "updated_at" | "update_by" | "created_by" | "record_status" | "post_code" | "tel_no", ExtArgs["result"]["tb_user_address"]>
export type tb_user_addressInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tb_user?: boolean | Prisma.tb_userDefaultArgs<ExtArgs>
}
export type tb_user_addressIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tb_user?: boolean | Prisma.tb_userDefaultArgs<ExtArgs>
}
export type tb_user_addressIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tb_user?: boolean | Prisma.tb_userDefaultArgs<ExtArgs>
}

export type $tb_user_addressPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "tb_user_address"
  objects: {
    tb_user: Prisma.$tb_userPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    user_address_id: string
    user_id: string
    address_type: number | null
    home_no: string | null
    moo: string | null
    alley: string | null
    soi: string | null
    road: string | null
    tambol_code: number | null
    tambol_name: string | null
    amphur_code: number | null
    amphur_name: string | null
    province_code: number | null
    province_name: string | null
    remark: string | null
    is_visible: boolean | null
    created_at: Date
    updated_at: Date | null
    update_by: string | null
    created_by: string | null
    record_status: string | null
    post_code: string | null
    tel_no: string | null
  }, ExtArgs["result"]["tb_user_address"]>
  composites: {}
}

export type tb_user_addressGetPayload<S extends boolean | null | undefined | tb_user_addressDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$tb_user_addressPayload, S>

export type tb_user_addressCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<tb_user_addressFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Tb_user_addressCountAggregateInputType | true
  }

export interface tb_user_addressDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['tb_user_address'], meta: { name: 'tb_user_address' } }
  /**
   * Find zero or one Tb_user_address that matches the filter.
   * @param {tb_user_addressFindUniqueArgs} args - Arguments to find a Tb_user_address
   * @example
   * // Get one Tb_user_address
   * const tb_user_address = await prisma.tb_user_address.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends tb_user_addressFindUniqueArgs>(args: Prisma.SelectSubset<T, tb_user_addressFindUniqueArgs<ExtArgs>>): Prisma.Prisma__tb_user_addressClient<runtime.Types.Result.GetResult<Prisma.$tb_user_addressPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Tb_user_address that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {tb_user_addressFindUniqueOrThrowArgs} args - Arguments to find a Tb_user_address
   * @example
   * // Get one Tb_user_address
   * const tb_user_address = await prisma.tb_user_address.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends tb_user_addressFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, tb_user_addressFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__tb_user_addressClient<runtime.Types.Result.GetResult<Prisma.$tb_user_addressPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tb_user_address that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {tb_user_addressFindFirstArgs} args - Arguments to find a Tb_user_address
   * @example
   * // Get one Tb_user_address
   * const tb_user_address = await prisma.tb_user_address.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends tb_user_addressFindFirstArgs>(args?: Prisma.SelectSubset<T, tb_user_addressFindFirstArgs<ExtArgs>>): Prisma.Prisma__tb_user_addressClient<runtime.Types.Result.GetResult<Prisma.$tb_user_addressPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tb_user_address that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {tb_user_addressFindFirstOrThrowArgs} args - Arguments to find a Tb_user_address
   * @example
   * // Get one Tb_user_address
   * const tb_user_address = await prisma.tb_user_address.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends tb_user_addressFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, tb_user_addressFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__tb_user_addressClient<runtime.Types.Result.GetResult<Prisma.$tb_user_addressPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Tb_user_addresses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {tb_user_addressFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Tb_user_addresses
   * const tb_user_addresses = await prisma.tb_user_address.findMany()
   * 
   * // Get first 10 Tb_user_addresses
   * const tb_user_addresses = await prisma.tb_user_address.findMany({ take: 10 })
   * 
   * // Only select the `user_address_id`
   * const tb_user_addressWithUser_address_idOnly = await prisma.tb_user_address.findMany({ select: { user_address_id: true } })
   * 
   */
  findMany<T extends tb_user_addressFindManyArgs>(args?: Prisma.SelectSubset<T, tb_user_addressFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$tb_user_addressPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Tb_user_address.
   * @param {tb_user_addressCreateArgs} args - Arguments to create a Tb_user_address.
   * @example
   * // Create one Tb_user_address
   * const Tb_user_address = await prisma.tb_user_address.create({
   *   data: {
   *     // ... data to create a Tb_user_address
   *   }
   * })
   * 
   */
  create<T extends tb_user_addressCreateArgs>(args: Prisma.SelectSubset<T, tb_user_addressCreateArgs<ExtArgs>>): Prisma.Prisma__tb_user_addressClient<runtime.Types.Result.GetResult<Prisma.$tb_user_addressPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Tb_user_addresses.
   * @param {tb_user_addressCreateManyArgs} args - Arguments to create many Tb_user_addresses.
   * @example
   * // Create many Tb_user_addresses
   * const tb_user_address = await prisma.tb_user_address.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends tb_user_addressCreateManyArgs>(args?: Prisma.SelectSubset<T, tb_user_addressCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Tb_user_addresses and returns the data saved in the database.
   * @param {tb_user_addressCreateManyAndReturnArgs} args - Arguments to create many Tb_user_addresses.
   * @example
   * // Create many Tb_user_addresses
   * const tb_user_address = await prisma.tb_user_address.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Tb_user_addresses and only return the `user_address_id`
   * const tb_user_addressWithUser_address_idOnly = await prisma.tb_user_address.createManyAndReturn({
   *   select: { user_address_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends tb_user_addressCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, tb_user_addressCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$tb_user_addressPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Tb_user_address.
   * @param {tb_user_addressDeleteArgs} args - Arguments to delete one Tb_user_address.
   * @example
   * // Delete one Tb_user_address
   * const Tb_user_address = await prisma.tb_user_address.delete({
   *   where: {
   *     // ... filter to delete one Tb_user_address
   *   }
   * })
   * 
   */
  delete<T extends tb_user_addressDeleteArgs>(args: Prisma.SelectSubset<T, tb_user_addressDeleteArgs<ExtArgs>>): Prisma.Prisma__tb_user_addressClient<runtime.Types.Result.GetResult<Prisma.$tb_user_addressPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Tb_user_address.
   * @param {tb_user_addressUpdateArgs} args - Arguments to update one Tb_user_address.
   * @example
   * // Update one Tb_user_address
   * const tb_user_address = await prisma.tb_user_address.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends tb_user_addressUpdateArgs>(args: Prisma.SelectSubset<T, tb_user_addressUpdateArgs<ExtArgs>>): Prisma.Prisma__tb_user_addressClient<runtime.Types.Result.GetResult<Prisma.$tb_user_addressPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Tb_user_addresses.
   * @param {tb_user_addressDeleteManyArgs} args - Arguments to filter Tb_user_addresses to delete.
   * @example
   * // Delete a few Tb_user_addresses
   * const { count } = await prisma.tb_user_address.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends tb_user_addressDeleteManyArgs>(args?: Prisma.SelectSubset<T, tb_user_addressDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tb_user_addresses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {tb_user_addressUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Tb_user_addresses
   * const tb_user_address = await prisma.tb_user_address.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends tb_user_addressUpdateManyArgs>(args: Prisma.SelectSubset<T, tb_user_addressUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tb_user_addresses and returns the data updated in the database.
   * @param {tb_user_addressUpdateManyAndReturnArgs} args - Arguments to update many Tb_user_addresses.
   * @example
   * // Update many Tb_user_addresses
   * const tb_user_address = await prisma.tb_user_address.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Tb_user_addresses and only return the `user_address_id`
   * const tb_user_addressWithUser_address_idOnly = await prisma.tb_user_address.updateManyAndReturn({
   *   select: { user_address_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends tb_user_addressUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, tb_user_addressUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$tb_user_addressPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Tb_user_address.
   * @param {tb_user_addressUpsertArgs} args - Arguments to update or create a Tb_user_address.
   * @example
   * // Update or create a Tb_user_address
   * const tb_user_address = await prisma.tb_user_address.upsert({
   *   create: {
   *     // ... data to create a Tb_user_address
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Tb_user_address we want to update
   *   }
   * })
   */
  upsert<T extends tb_user_addressUpsertArgs>(args: Prisma.SelectSubset<T, tb_user_addressUpsertArgs<ExtArgs>>): Prisma.Prisma__tb_user_addressClient<runtime.Types.Result.GetResult<Prisma.$tb_user_addressPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Tb_user_addresses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {tb_user_addressCountArgs} args - Arguments to filter Tb_user_addresses to count.
   * @example
   * // Count the number of Tb_user_addresses
   * const count = await prisma.tb_user_address.count({
   *   where: {
   *     // ... the filter for the Tb_user_addresses we want to count
   *   }
   * })
  **/
  count<T extends tb_user_addressCountArgs>(
    args?: Prisma.Subset<T, tb_user_addressCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Tb_user_addressCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Tb_user_address.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Tb_user_addressAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Tb_user_addressAggregateArgs>(args: Prisma.Subset<T, Tb_user_addressAggregateArgs>): Prisma.PrismaPromise<GetTb_user_addressAggregateType<T>>

  /**
   * Group by Tb_user_address.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {tb_user_addressGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends tb_user_addressGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: tb_user_addressGroupByArgs['orderBy'] }
      : { orderBy?: tb_user_addressGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, tb_user_addressGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTb_user_addressGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the tb_user_address model
 */
readonly fields: tb_user_addressFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for tb_user_address.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__tb_user_addressClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tb_user<T extends Prisma.tb_userDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.tb_userDefaultArgs<ExtArgs>>): Prisma.Prisma__tb_userClient<runtime.Types.Result.GetResult<Prisma.$tb_userPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the tb_user_address model
 */
export interface tb_user_addressFieldRefs {
  readonly user_address_id: Prisma.FieldRef<"tb_user_address", 'String'>
  readonly user_id: Prisma.FieldRef<"tb_user_address", 'String'>
  readonly address_type: Prisma.FieldRef<"tb_user_address", 'Int'>
  readonly home_no: Prisma.FieldRef<"tb_user_address", 'String'>
  readonly moo: Prisma.FieldRef<"tb_user_address", 'String'>
  readonly alley: Prisma.FieldRef<"tb_user_address", 'String'>
  readonly soi: Prisma.FieldRef<"tb_user_address", 'String'>
  readonly road: Prisma.FieldRef<"tb_user_address", 'String'>
  readonly tambol_code: Prisma.FieldRef<"tb_user_address", 'Int'>
  readonly tambol_name: Prisma.FieldRef<"tb_user_address", 'String'>
  readonly amphur_code: Prisma.FieldRef<"tb_user_address", 'Int'>
  readonly amphur_name: Prisma.FieldRef<"tb_user_address", 'String'>
  readonly province_code: Prisma.FieldRef<"tb_user_address", 'Int'>
  readonly province_name: Prisma.FieldRef<"tb_user_address", 'String'>
  readonly remark: Prisma.FieldRef<"tb_user_address", 'String'>
  readonly is_visible: Prisma.FieldRef<"tb_user_address", 'Boolean'>
  readonly created_at: Prisma.FieldRef<"tb_user_address", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"tb_user_address", 'DateTime'>
  readonly update_by: Prisma.FieldRef<"tb_user_address", 'String'>
  readonly created_by: Prisma.FieldRef<"tb_user_address", 'String'>
  readonly record_status: Prisma.FieldRef<"tb_user_address", 'String'>
  readonly post_code: Prisma.FieldRef<"tb_user_address", 'String'>
  readonly tel_no: Prisma.FieldRef<"tb_user_address", 'String'>
}
    

// Custom InputTypes
/**
 * tb_user_address findUnique
 */
export type tb_user_addressFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_user_address
   */
  select?: Prisma.tb_user_addressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_user_address
   */
  omit?: Prisma.tb_user_addressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_user_addressInclude<ExtArgs> | null
  /**
   * Filter, which tb_user_address to fetch.
   */
  where: Prisma.tb_user_addressWhereUniqueInput
}

/**
 * tb_user_address findUniqueOrThrow
 */
export type tb_user_addressFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_user_address
   */
  select?: Prisma.tb_user_addressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_user_address
   */
  omit?: Prisma.tb_user_addressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_user_addressInclude<ExtArgs> | null
  /**
   * Filter, which tb_user_address to fetch.
   */
  where: Prisma.tb_user_addressWhereUniqueInput
}

/**
 * tb_user_address findFirst
 */
export type tb_user_addressFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_user_address
   */
  select?: Prisma.tb_user_addressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_user_address
   */
  omit?: Prisma.tb_user_addressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_user_addressInclude<ExtArgs> | null
  /**
   * Filter, which tb_user_address to fetch.
   */
  where?: Prisma.tb_user_addressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of tb_user_addresses to fetch.
   */
  orderBy?: Prisma.tb_user_addressOrderByWithRelationInput | Prisma.tb_user_addressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for tb_user_addresses.
   */
  cursor?: Prisma.tb_user_addressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` tb_user_addresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` tb_user_addresses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of tb_user_addresses.
   */
  distinct?: Prisma.Tb_user_addressScalarFieldEnum | Prisma.Tb_user_addressScalarFieldEnum[]
}

/**
 * tb_user_address findFirstOrThrow
 */
export type tb_user_addressFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_user_address
   */
  select?: Prisma.tb_user_addressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_user_address
   */
  omit?: Prisma.tb_user_addressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_user_addressInclude<ExtArgs> | null
  /**
   * Filter, which tb_user_address to fetch.
   */
  where?: Prisma.tb_user_addressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of tb_user_addresses to fetch.
   */
  orderBy?: Prisma.tb_user_addressOrderByWithRelationInput | Prisma.tb_user_addressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for tb_user_addresses.
   */
  cursor?: Prisma.tb_user_addressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` tb_user_addresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` tb_user_addresses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of tb_user_addresses.
   */
  distinct?: Prisma.Tb_user_addressScalarFieldEnum | Prisma.Tb_user_addressScalarFieldEnum[]
}

/**
 * tb_user_address findMany
 */
export type tb_user_addressFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_user_address
   */
  select?: Prisma.tb_user_addressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_user_address
   */
  omit?: Prisma.tb_user_addressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_user_addressInclude<ExtArgs> | null
  /**
   * Filter, which tb_user_addresses to fetch.
   */
  where?: Prisma.tb_user_addressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of tb_user_addresses to fetch.
   */
  orderBy?: Prisma.tb_user_addressOrderByWithRelationInput | Prisma.tb_user_addressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing tb_user_addresses.
   */
  cursor?: Prisma.tb_user_addressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` tb_user_addresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` tb_user_addresses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of tb_user_addresses.
   */
  distinct?: Prisma.Tb_user_addressScalarFieldEnum | Prisma.Tb_user_addressScalarFieldEnum[]
}

/**
 * tb_user_address create
 */
export type tb_user_addressCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_user_address
   */
  select?: Prisma.tb_user_addressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_user_address
   */
  omit?: Prisma.tb_user_addressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_user_addressInclude<ExtArgs> | null
  /**
   * The data needed to create a tb_user_address.
   */
  data: Prisma.XOR<Prisma.tb_user_addressCreateInput, Prisma.tb_user_addressUncheckedCreateInput>
}

/**
 * tb_user_address createMany
 */
export type tb_user_addressCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many tb_user_addresses.
   */
  data: Prisma.tb_user_addressCreateManyInput | Prisma.tb_user_addressCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * tb_user_address createManyAndReturn
 */
export type tb_user_addressCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_user_address
   */
  select?: Prisma.tb_user_addressSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the tb_user_address
   */
  omit?: Prisma.tb_user_addressOmit<ExtArgs> | null
  /**
   * The data used to create many tb_user_addresses.
   */
  data: Prisma.tb_user_addressCreateManyInput | Prisma.tb_user_addressCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_user_addressIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * tb_user_address update
 */
export type tb_user_addressUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_user_address
   */
  select?: Prisma.tb_user_addressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_user_address
   */
  omit?: Prisma.tb_user_addressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_user_addressInclude<ExtArgs> | null
  /**
   * The data needed to update a tb_user_address.
   */
  data: Prisma.XOR<Prisma.tb_user_addressUpdateInput, Prisma.tb_user_addressUncheckedUpdateInput>
  /**
   * Choose, which tb_user_address to update.
   */
  where: Prisma.tb_user_addressWhereUniqueInput
}

/**
 * tb_user_address updateMany
 */
export type tb_user_addressUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update tb_user_addresses.
   */
  data: Prisma.XOR<Prisma.tb_user_addressUpdateManyMutationInput, Prisma.tb_user_addressUncheckedUpdateManyInput>
  /**
   * Filter which tb_user_addresses to update
   */
  where?: Prisma.tb_user_addressWhereInput
  /**
   * Limit how many tb_user_addresses to update.
   */
  limit?: number
}

/**
 * tb_user_address updateManyAndReturn
 */
export type tb_user_addressUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_user_address
   */
  select?: Prisma.tb_user_addressSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the tb_user_address
   */
  omit?: Prisma.tb_user_addressOmit<ExtArgs> | null
  /**
   * The data used to update tb_user_addresses.
   */
  data: Prisma.XOR<Prisma.tb_user_addressUpdateManyMutationInput, Prisma.tb_user_addressUncheckedUpdateManyInput>
  /**
   * Filter which tb_user_addresses to update
   */
  where?: Prisma.tb_user_addressWhereInput
  /**
   * Limit how many tb_user_addresses to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_user_addressIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * tb_user_address upsert
 */
export type tb_user_addressUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_user_address
   */
  select?: Prisma.tb_user_addressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_user_address
   */
  omit?: Prisma.tb_user_addressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_user_addressInclude<ExtArgs> | null
  /**
   * The filter to search for the tb_user_address to update in case it exists.
   */
  where: Prisma.tb_user_addressWhereUniqueInput
  /**
   * In case the tb_user_address found by the `where` argument doesn't exist, create a new tb_user_address with this data.
   */
  create: Prisma.XOR<Prisma.tb_user_addressCreateInput, Prisma.tb_user_addressUncheckedCreateInput>
  /**
   * In case the tb_user_address was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.tb_user_addressUpdateInput, Prisma.tb_user_addressUncheckedUpdateInput>
}

/**
 * tb_user_address delete
 */
export type tb_user_addressDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_user_address
   */
  select?: Prisma.tb_user_addressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_user_address
   */
  omit?: Prisma.tb_user_addressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_user_addressInclude<ExtArgs> | null
  /**
   * Filter which tb_user_address to delete.
   */
  where: Prisma.tb_user_addressWhereUniqueInput
}

/**
 * tb_user_address deleteMany
 */
export type tb_user_addressDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which tb_user_addresses to delete
   */
  where?: Prisma.tb_user_addressWhereInput
  /**
   * Limit how many tb_user_addresses to delete.
   */
  limit?: number
}

/**
 * tb_user_address without action
 */
export type tb_user_addressDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tb_user_address
   */
  select?: Prisma.tb_user_addressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tb_user_address
   */
  omit?: Prisma.tb_user_addressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.tb_user_addressInclude<ExtArgs> | null
}
