import { TbAccount } from './tbAccount.entity';
import { TbLegalEntityRepresent } from './tbLegalEntityRepresent.entity';
import { TbLogAccessSession } from './tbLogAccessSession.entity';
import { TbRegistAttach } from './tbRegistAttach.entity';
import { TbMsChannel } from './tbMsChannel.entity';
import { TbMsUserType } from './tbMsUserType.entity';
import { TbUserAddress } from './tbUserAddress.entity';
import { TbUserConsent } from './tbUserConsent.entity';
import { TbUserRole } from './tbUserRole.entity';
import { TbUserVerfity } from './tbUserVerfity.entity';

export class TbUser {
  user_id!: string;
  user_type_id!: bigint;
  register_channel_id!: bigint | null;
  person_id!: string | null;
  title!: string | null;
  given_name!: string | null;
  middle_name!: string | null;
  family_name!: string | null;
  title_en!: string | null;
  given_name_en!: string | null;
  middle_name_en!: string | null;
  family_name_en!: string | null;
  birth_date!: Date | null;
  date_of_expiry!: Date | null;
  ial_level!: string | null;
  legal_code!: string | null;
  legal_name!: string | null;
  land_office_id!: string | null;
  land_office_name!: string | null;
  land_office_position!: string | null;
  private_office_id!: string | null;
  private_office_name!: string | null;
  email!: string | null;
  is_email_verified!: boolean | null;
  mobile_no!: string | null;
  verfity_at!: Date | null;
  is_verify!: boolean | null;
  user_status!: string;
  created_at!: Date;
  updated_at!: Date | null;
  update_by!: string | null;
  created_by!: string | null;
  record_status!: string | null;
  tb_account?: TbAccount[];
  tb_legal_entity_represent?: TbLegalEntityRepresent[];
  tb_log_access_session?: TbLogAccessSession[];
  tb_regist_attach?: TbRegistAttach[];
  tb_ms_channel?: TbMsChannel | null;
  tb_ms_user_type?: TbMsUserType;
  tb_user_address?: TbUserAddress[];
  tb_user_consent?: TbUserConsent[];
  tb_user_role_tb_user_role_assigned_byTotb_user?: TbUserRole[];
  tb_user_role_tb_user_role_user_idTotb_user?: TbUserRole[];
  tb_user_verfity?: TbUserVerfity[];
}
